### ISSUE TITLE
Inline function with reified type parameter in @JsonClass breaks codegen on >= 1.9.0

### ISSUE THREAD

**Issue by mannodermaus** [square/moshi#1008]
The following model class definition fails with Moshi 1.9.0 and above:

```kotlin
@JsonClass(generateAdapter = true)
data class Model(@Json(name = "id") val id: String) {
    inline fun <reified T> inlineMethod(named: String): T? = null
}
```

The fields on the class & the body of its inline function are irrelevant - instead, it seems like the presence of the `reified` keyword will cause Moshi's codegen to fail with the following message:

```
e: [kapt] An exception occurred: java.util.NoSuchElementException: Key 0 is missing in the map.
	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:294)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toFunSpec(KotlinPoetMetadataSpecs.kt:543)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.access$toFunSpec(KotlinPoetMetadataSpecs.kt:1)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs$toTypeSpec$26.invoke(KotlinPoetMetadataSpecs.kt:429)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs$toTypeSpec$26.invoke(KotlinPoetMetadataSpecs.kt)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
	at com.squareup.kotlinpoet.TypeSpec$Builder.addFunctions(TypeSpec.kt:786)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:403)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:173)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec$default(KotlinPoetMetadataSpecs.kt:171)
	at com.squareup.moshi.kotlin.codegen.MetadataKt.targetType(metadata.kt:153)
	at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.adapterGenerator(JsonClassCodegenProcessor.kt:133)
	at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.process(JsonClassCodegenProcessor.kt:107)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
(More kapt stuff below this line...)
```

On 1.8.0, code generation and compilation are successful.

As a workaround, the `reified inline fun` can be defined outside of the model class, as an extension function:

```kotlin
@JsonClass(generateAdapter = true)
data class Model(@Json(name = "id") val id: String)

// This works
inline fun <reified T> Model.inlineMethod(named: String): T? = null
```

**Comment by ZacSweers** [comment]
Can you try the master snapshot and 1.9.1? We fixed an issue around type
variables last week.

**Comment by mannodermaus** [comment]
Neither `1.9.1` nor the latest `1.10.0-SNAPSHOT` seem to change anything about the failure, unfortunately. The stack trace is unchanged compared to the error using `1.9.0` as well.

**Comment by DanielClayton** [comment]
I'm also seeing something similar with the `out` variance annotation:
```
@JsonClass(generateAdapter = true)
data class NodeGlobalApiResponse<out T>
```

This was working in `1.8.0`, but in `1.9.1` I'm getting a compile-time error:
`Type parameter T is declared as 'out' but occurs in 'invariant' position in type JsonAdapter<NodeGlobalApiResponse<T>>`

**Comment by ZacSweers** [comment]
@mannodermaus since this is a KotlinPoet issue, do you mind filing there? We'll need to start there

@DanielClayton yours looks like a separate issue. Can you please post a separate issue with the full stacktrace? Also whether or not you tested the current master snapshot

**Comment by mannodermaus** [comment]
@ZacSweers Thanks! I raised it on KotlinPoet as https://github.com/square/kotlinpoet/issues/829.

**Comment by ZacSweers** [comment]
@DanielClayton I've extracted your issue to a separate issue in #1009 and opened a PR for it in #1010.

**Comment by mannodermaus** [comment]
I can confirm that the latest `1.10.0-SNAPSHOT` resolves this issue. As soon as `1.9.2` hits jcenter, I will upgrade to that version. Thank you for the quick turnaround!
