### ISSUE TITLE
Error on nullable lists on 1.9.1

### ISSUE THREAD

**Issue by fabioCollini** [square/moshi#1019]
Nullable lists seems to be not supported in version 1.9.1. Executing this test:

```kotlin
@JsonClass(generateAdapter = true)
data class MyClass(
        val list: List<Int>?,
        val nullableList: List<Int?>?
)

class NullableIntListTest {
    @Test
    fun parsingTest() {
        val adapter = Moshi.Builder().build().adapter<MyClass>(MyClass::class.java)
        adapter.fromJson("""{
            "list": null,
            "nullableList": null
        }""")
    }
}
```

I get this error on 1.9.1:

```
com.squareup.moshi.JsonDataException: Non-null value 'list' was null at $.list

at com.squareup.moshi.internal.Util.unexpectedNull(Util.java:621)
at com.nytimes.android.MyClassJsonAdapter.fromJson(MyClassJsonAdapter.kt:39)
```

The same test works using moshi 1.8.0

**Comment by ZacSweers** [comment]
This is fixed on master and will be available in the next release. You can verify by trying the latest snapshot release

**Comment by fabioCollini** [comment]
Great, thanks a lot!
