### ISSUE TITLE
Exception when generating adapters: Unexpected type variable T

### ISSUE THREAD

**Issue by Wasky** [square/moshi#1046]
Moshi version: 1.9.0, 1.9.1, 1.9.2 (on previous versions it works fine)

The following code causes Gradle build failed with exception:

```kotlin
open class Response<T> {
    var data: T? = null
}

class Person(val name: String)

@JsonClass(generateAdapter = true)
class PersonResponse : Response<Person>()
```
Exception:

```
[kapt] An exception occurred: java.lang.IllegalStateException: Unexpected type variable T
	at com.squareup.moshi.kotlin.codegen.api.AdapterGenerator$generateType$typeRenderer$1.renderTypeVariable(AdapterGenerator.kt:162)
	at com.squareup.moshi.kotlin.codegen.api.TypeRenderer.render(TypeRenderer.kt:100)
	at com.squareup.moshi.kotlin.codegen.api.TypeRenderer.render$default(TypeRenderer.kt:43)
	at com.squareup.moshi.kotlin.codegen.api.TypeRenderer.renderObjectType(TypeRenderer.kt:110)
	at com.squareup.moshi.kotlin.codegen.api.TypeRenderer.render(TypeRenderer.kt:45)
	at com.squareup.moshi.kotlin.codegen.api.TypeRenderer.render$default(TypeRenderer.kt:43)
        (...)
```

**Comment by ZacSweers** [comment]
Thanks for the repro steps! Still take a look

**Comment by ZacSweers** [comment]
Still digging into this, it looks like with the new kotlinpoet metadata backend we only see the data property as `T` and not its materialized `Person` type. On 1.8.0 we generated

```kotlin
// Code generated by moshi-kotlin-codegen. Do not edit.
package com.squareup.moshi.kotlin.codgen

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonDataException
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import java.lang.NullPointerException
import kotlin.String

class GeneratedAdaptersTest_PersonResponseJsonAdapter(moshi: Moshi) : JsonAdapter<GeneratedAdaptersTest.PersonResponse>() {
    private val options: JsonReader.Options = JsonReader.Options.of("data")

    private val personAdapter: JsonAdapter<GeneratedAdaptersTest.Person> =
            moshi.adapter<GeneratedAdaptersTest.Person>(GeneratedAdaptersTest.Person::class.java, kotlin.collections.emptySet(), "data")

    override fun toString(): String = "GeneratedJsonAdapter(GeneratedAdaptersTest.PersonResponse)"

    override fun fromJson(reader: JsonReader): GeneratedAdaptersTest.PersonResponse {
        var data: GeneratedAdaptersTest.Person? = null
        reader.beginObject()
        while (reader.hasNext()) {
            when (reader.selectName(options)) {
                0 -> data = personAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'data' was null at ${reader.path}")
                -1 -> {
                    // Unknown name, skip it.
                    reader.skipName()
                    reader.skipValue()
                }
            }
        }
        reader.endObject()
        var result = GeneratedAdaptersTest.PersonResponse()
        result.data = data ?: result.data
        return result
    }

    override fun toJson(writer: JsonWriter, value: GeneratedAdaptersTest.PersonResponse?) {
        if (value == null) {
            throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
        }
        writer.beginObject()
        writer.name("data")
        personAdapter.toJson(writer, value.data)
        writer.endObject()
    }
}
```

**Comment by ZacSweers** [comment]
Got this working! #1080
