### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by PramodGarg** [square/moshi#1060]
Getting 

> java.lang.IllegalArgumentException: Unable to create converter for class feature.bankaccounts.data.model.AccountExpenseResponse

only once the proguard is enabled, works fine without it.

**Stacktrace**:

> java.lang.IllegalArgumentException: Unable to create converter for class feature.bankaccounts.data.model.AccountExpenseResponse
  ..
  ..
 Caused by: java.lang.RuntimeException: Failed to find the generated JsonAdapter class 
     at i.p.b.w.b.a(SourceFile:542)
     at i.p.b.t$b.a(SourceFile:60)
     at i.p.b.s.a(SourceFile:138)
     at i.p.b.s.a(SourceFile:98)
     at w.w.b.a.responseBodyConverter(SourceFile:91)
     at com.wealth.core.rest.data.api.MoshiMigrationConverter.responseBodyConverter(
     at w.r.a(SourceFile:330)
     at w.r.b(SourceFile:313)
     at w.h.a(SourceFile:113)
 	... 101 more
 Caused by: java.lang.ClassNotFoundException: 
     at java.lang.Class.classForName(Native Method)
     at java.lang.Class.forName(Class.java:454)
     at i.p.b.w.b.a(SourceFile:516)
 	... 109 more
 Caused by: java.lang.ClassNotFoundException: Didn't find class "feature.bankaccounts.data.model.AccountExpenseResponseJsonAdapter" on path: DexPathList[[zip file "/data/app/in.wealth.debug-wWI0I-EzMKlkerGtVEAXCA==/base.apk"],nativeLibraryDirectories=[/data/app/in.wealth.debug-wWI0I-EzMKlkerGtVEAXCA==/lib/x86, /data/app/in.wealth.debug-wWI0I-EzMKlkerGtVEAXCA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]

Moshi Version: 1.9.2
Moshi Code Gen : 1.9.2

**Data class**

```kotlin
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class AccountExpenseResponse(
    val data: AccountExpenseResponseData?,
    @Json(name = "sync_status")
    var syncStatus: String
) {

    .. other fxns
}

@JsonClass(generateAdapter = true)
data class AccountExpenseResponseData(
    @Json(name = "total_expenses")
    val totalExpenses: Double?,

    @Json(name = "total_account_balance")
    val totalAccountBalance: Double?,

    @Json(name = "last_processed_time")
    val lastProcessedTime: Double?
)
```
**Tried Adding**
```
`sourceSets {
        main.java.srcDirs += [file("$buildDir/generated/source/kaptKotlin/main")]
        debug.java.srcDirs += [file("$buildDir/generated/source/kaptKotlin/devDebug")]
        debug.java.srcDirs += [file("$buildDir/generated/source/kaptKotlin/prodDebug")]
        release.java.srcDirs += [file("$buildDir/generated/source/kaptKotlin/devRelease")]
        release.java.srcDirs += [file("$buildDir/generated/source/kaptKotlin/prodRelease")]
        test.java.srcDirs += [file("$buildDir/generated/source/kaptKotlin/test")]
    }`
```

**Added these proguard rules**

```
-keep class kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoaderImpl

-keepclassmembers class kotlin.Metadata {
    public <methods>;
}

# JSR 305 annotations are for embedding nullability information.
-dontwarn javax.annotation.**

-keepclasseswithmembers class * {
    @com.squareup.moshi.* <methods>;
}

-keep @com.squareup.moshi.JsonQualifier interface *

# Enum field names are used by the integrated EnumJsonAdapter.
# values() is synthesized by the Kotlin compiler and is used by EnumJsonAdapter indirectly
# Annotate enums with @JsonClass(generateAdapter = false) to use them with Moshi.
-keepclassmembers @com.squareup.moshi.JsonClass class * extends java.lang.Enum {
    <fields>;
    **[] values();
}

# The name of @JsonClass types is used to look up the generated adapter.
-keepnames @com.squareup.moshi.JsonClass class *

# Retain generated target class's synthetic defaults constructor and keep DefaultConstructorMarker's
# name. We will look this up reflectively to invoke the type's constructor.
#
# We can't _just_ keep the defaults constructor because Proguard/R8's spec doesn't allow wildcard
# matching preceding parameters.
-keepnames class kotlin.jvm.internal.DefaultConstructorMarker
-keepclassmembers @com.squareup.moshi.JsonClass @kotlin.Metadata class * {
    synthetic <init>(...);
}

# Retain generated JsonAdapters if annotated type is retained.
-if @com.squareup.moshi.JsonClass class *
-keep class <1>JsonAdapter {
    <init>(...);
    <fields>;
}
-if @com.squareup.moshi.JsonClass class **$*
-keep class <1>_<2>JsonAdapter {
    <init>(...);
    <fields>;
}
-if @com.squareup.moshi.JsonClass class **$*$*
-keep class <1>_<2>_<3>JsonAdapter {
    <init>(...);
    <fields>;
}
-if @com.squareup.moshi.JsonClass class **$*$*$*
-keep class <1>_<2>_<3>_<4>JsonAdapter {
    <init>(...);
    <fields>;
}
-if @com.squareup.moshi.JsonClass class **$*$*$*$*
-keep class <1>_<2>_<3>_<4>_<5>JsonAdapter {
    <init>(...);
    <fields>;
}
-if @com.squareup.moshi.JsonClass class **$*$*$*$*$*
-keep class <1>_<2>_<3>_<4>_<5>_<6>JsonAdapter {
    <init>(...);
    <fields>;
}
```

**Comment by ZacSweers** [comment]
Unfortunately can't really help without a reproducing project. The above could be going wrong in a number of different places
