### ISSUE TITLE
AssertionError in JsonUtf8Reader

### ISSUE THREAD

**Issue by gabrielittner** [square/moshi#1097]
Recently we've been seeing this crash:

```
Caused by java.lang.AssertionError
       at com.squareup.moshi.JsonUtf8Reader.<init>(JsonUtf8Reader.java:118)
       at com.squareup.moshi.JsonUtf8Reader.peekJson(JsonUtf8Reader.java:1090)
       at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.fromJson(PolymorphicJsonAdapterFactory.java:237)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
       at com.freeletics.core.coach.trainingsession.model.QuickAdaptOptionJsonAdapter.fromJson(QuickAdaptOptionJsonAdapter.java:24)
       at com.freeletics.core.coach.trainingsession.model.QuickAdaptOptionJsonAdapter.fromJson(QuickAdaptOptionJsonAdapter.java:12)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
       at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
       at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
       at com.freeletics.core.coach.trainingsession.model.QuickAdaptJsonAdapter.fromJson(QuickAdaptJsonAdapter.java:35)
       at com.freeletics.core.coach.trainingsession.model.QuickAdaptJsonAdapter.fromJson(QuickAdaptJsonAdapter.java:18)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
       at com.freeletics.core.coach.trainingsession.model.SessionJsonAdapter.fromJson(SessionJsonAdapter.java:106)
       at com.freeletics.core.coach.trainingsession.model.SessionJsonAdapter.fromJson(SessionJsonAdapter.java:22)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
       at com.freeletics.core.coach.trainingsession.api.model.SessionResponseJsonAdapter.fromJson(SessionResponseJsonAdapter.java:37)
       at com.freeletics.core.coach.trainingsession.api.model.SessionResponseJsonAdapter.fromJson(SessionResponseJsonAdapter.java:17)
       at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:40)
       at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
       at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
       at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
       at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
```

The `PolymorphicJsonAdapter` is created by moshi-sealed, but I don't think that has anything to do with it. So far my only theory is that R8 might break something in Okio, but it's hard to verify that without being able to reproduce it.

**Comment by Grouen** [comment]
I have the same issue

**Comment by gabrielittner** [comment]
This doesn't happen for us anymore since we updated r8 to version 1.6.82.
