### ISSUE TITLE
Trying to enable compose with a project that uses moshi seems to cause an issue with kotlin reflect at runtime

### ISSUE THREAD

**Issue by ColtonIdle** [square/moshi#1221]
Not sure if this is a compose problem or moshi problem or kotlin/reflect problem.

I have a project that uses moshi and it runs fine.

I'm trying to enable compose. So far I updated kotlin to 1.4, agp to 4.2.0-alpha10, gradle to 6.6.1,

When I do the above updates... my app runs fine, it's only when I add

```
buildFeatures {
    compose true
}
composeOptions {
    kotlinCompilerExtensionVersion MyVersions.compose_version //this id defined as val compose_version = "1.0.0-alpha02"
    kotlinCompilerVersion '1.4.0'
}
```

I get an error when my app runs due to moshi/kotlin reflection?

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp.free, PID: 8768
    kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Could not compute caller for function: public constructor MyNetworkResponse(myFields...) defined in com.myapp.free.MyNetworkResponse[DeserializedClassConstructorDescriptor@aa293b] (member = null)
        at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:89)
        at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:36)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:62)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)
        at kotlin.reflect.jvm.internal.KFunctionImpl.getCaller(Unknown Source:7)
        at kotlin.reflect.jvm.ReflectJvmMapping.getJavaMethod(ReflectJvmMapping.kt:63)
        at kotlin.reflect.jvm.KCallablesJvm.setAccessible(KCallablesJvm.kt:82)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:223)
        at com.squareup.moshi.Moshi.nextAdapter(Moshi.java:172)
```

**Comment by ZacSweers** [comment]
Not a Moshi problem, it just defers to kotlin-reflect APIS. You should file a bug on the kotlin issue tracker with a reproducible case (like a sample class that you're trying to reflectively read)

**Comment by ColtonIdle** [comment]
Thanks for the response. Filed on youtrack as well.
