### ISSUE TITLE
Android Studio Canary Alpha12 - ExternalSynthetic0 is defined multiple times

### ISSUE THREAD

**Issue by okarakose** [square/moshi#1237]
```
Kotlin: 1.4.10
Android Gradle Tool: 4.2.0-alpha12
```

I'm using moshi in my project without any problem. But after I upgraded my Android Studio Canary from Alpha11 to Alpha12, there is an error on building process which is following:

```
AGPBI: {"kind":"error","text":"Type com.mydomain.example.data.forecast.remote.response.GetForecastResponse$City-$$ExternalSynthetic0 is defined multiple times: /Users/mydomain/Projects/Example/app/build/intermediates/project_dex_archive/debug/out/com/mydomain/example/data/forecast/remote/response/GetForecastResponse$City.dex, /Users/mydomain/Projects/Example/app/build/intermediates/project_dex_archive/debug/out/com/mydomain/example/data/forecast/remote/response/GetForecastResponse$Forecast.dex","sources":[{"file":"/Users/mydomain/Projects/Example/app/build/intermediates/project_dex_archive/debug/out/com/mydomain/example/data/forecast/remote/response/GetForecastResponse$City.dex"}],"tool":"D8"}
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type com.mydomain.example.data.forecast.remote.response.GetForecastResponse$City-$$ExternalSynthetic0 is defined multiple times: /Users/mydomain/Projects/Example/app/build/intermediates/project_dex_archive/debug/out/com/mydomain/example/data/forecast/remote/response/GetForecastResponse$City.dex, /Users/mydomain/Projects/Example/app/build/intermediates/project_dex_archive/debug/out/com/mydomain/example/data/forecast/remote/response/GetForecastResponse$Forecast.dex
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:128)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:115)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:111)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:805)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:760)
	at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/mydomain/Projects/Example/app/build/intermediates/project_dex_archive/debug/out/com/mydomain/example/data/forecast/remote/response/GetForecastResponse$City.dex
	at Version.fakeStackEntry(Version_2.2.15-dev.java:0)
	at com.android.tools.r8.utils.Y.a(SourceFile:80)
	at com.android.tools.r8.D8.run(D8.java:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:113)
	... 33 more
Caused by: com.android.tools.r8.utils.b: Type com.mydomain.example.data.forecast.remote.response.GetForecastResponse$City-$$ExternalSynthetic0 is defined multiple times: /Users/mydomain/Projects/Example/app/build/intermediates/project_dex_archive/debug/out/com/mydomain/example/data/forecast/remote/response/GetForecastResponse$City.dex, /Users/mydomain/Projects/Example/app/build/intermediates/project_dex_archive/debug/out/com/mydomain/example/data/forecast/remote/response/GetForecastResponse$Forecast.dex
	at com.android.tools.r8.utils.T0.a(SourceFile:22)
	at com.android.tools.r8.utils.T0.a(SourceFile:25)
	at com.android.tools.r8.utils.R0.b(SourceFile:6)
	at com.android.tools.r8.utils.R0.a(SourceFile:23)
	at com.android.tools.r8.utils.R0.a(SourceFile:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
	at com.android.tools.r8.utils.R0.a(SourceFile:6)
	at com.android.tools.r8.graph.R0$c.e(SourceFile:3)
	at com.android.tools.r8.dex.a.a(SourceFile:336)
	at com.android.tools.r8.dex.a.a(SourceFile:265)
	at com.android.tools.r8.D8.a(D8.java:22)
	at com.android.tools.r8.D8.d(D8.java:6)
	at com.android.tools.r8.D8.b(D8.java:1)
	at com.android.tools.r8.utils.Y.a(SourceFile:38)
	... 35 more
```

This is my moshi gradle definition:

```
implementation "com.squareup.moshi:moshi:1.9.3"
kapt "com.squareup.moshi:moshi-kotlin-codegen:1.9.3"
```

And response classes are below:

```
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class GetForecastResponse(
    @Json(name = "cod") val code: String,
    @Json(name = "message") val message: Int,
    @Json(name = "cnt") val count: Int?,
    @Json(name = "list") val list: List<Forecast>?,
    @Json(name = "city") val city: City?,
) {

    @JsonClass(generateAdapter = true)
    data class Forecast(
        @Json(name = "dt") val datetime: Long,
        @Json(name = "main") val main: ForecastMain,
        @Json(name = "weather") val weather: List<ForecastWeather>,
        @Json(name = "clouds") val clouds: ForecastClouds,
        @Json(name = "wind") val wind: ForecastWind,
        @Json(name = "visibility") val visibility: Int,
        @Json(name = "pop") val pop: Double,
        @Json(name = "sys") val sys: ForecastSys,
        @Json(name = "dt_txt") val dateText: String,
    )

    @JsonClass(generateAdapter = true)
    data class ForecastMain(
        @Json(name = "temp") val temperature: Double,
        @Json(name = "feels_like") val feelsLike: Double,
        @Json(name = "temp_min") val minTemperature: Double,
        @Json(name = "temp_max") val maxTemperature: Double,
        @Json(name = "pressure") val pressure: Double,
        @Json(name = "sea_level") val seaLevel: Double,
        @Json(name = "grnd_level") val groundLevel: Double,
        @Json(name = "humidity") val humidity: Double,
        @Json(name = "temp_kf") val kfTemperature: Double,
    )

    @JsonClass(generateAdapter = true)
    data class ForecastWeather(
        @Json(name = "id") val id: Long,
        @Json(name = "main") val main: String,
        @Json(name = "description") val description: String,
        @Json(name = "icon") val icon: String,
    )

    @JsonClass(generateAdapter = true)
    data class ForecastClouds(
        @Json(name = "all") val all: Int,
    )

    @JsonClass(generateAdapter = true)
    data class ForecastWind(
        @Json(name = "speed") val speed: Double,
        @Json(name = "deg") val degree: Double,
    )

    @JsonClass(generateAdapter = true)
    data class ForecastSys(
        @Json(name = "pod") val pod: String,
    )

    @JsonClass(generateAdapter = true)
    data class City(
        @Json(name = "id") val id: Int,
        @Json(name = "name") val name: String,
        @Json(name = "coord") val location: Location,
        @Json(name = "country") val country: String,
        @Json(name = "population") val population: Long,
        @Json(name = "timezone") val timezone: Long,
        @Json(name = "sunrise") val sunrise: Long,
        @Json(name = "sunset") val sunset: Long,
    )

    @JsonClass(generateAdapter = true)
    data class Location(
        @Json(name = "lat") val latitude: Double,
        @Json(name = "lon") val longitude: Double,
    )
}
```

Anyone has idea for this?

**Comment by ZacSweers** [comment]
Not a moshi issue, you should file this on the R8 or Kotlin issue trackers

**Comment by okarakose** [comment]
@ZacSweers Thanks, I'm closing the issue.
