### ISSUE TITLE
Enum parsing fails with generated R8 rules

### ISSUE THREAD

**Issue by WonderCsabo** [square/moshi#1240]
If i only rely on the built-in and generated R8 rules for moshi, parsing enums fail in release builds. For me it seems that R8 strips all enum fields, so we have to explicitly keep them. If i keep them manually, it works as expected.

I have the following dependencies
moshi-codegen: 1.10.0
kotlin: 1.4.10
Android Gradle Plugin: 4.0.1

I got this stacktrace when parsing enums (i kept `com.squareup.moshi.**` for this log only):

```
java.lang.AssertionError: Missing field in e.f.a.k.c.b.a
        at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.<init>(SourceFile:246)
        at com.squareup.moshi.StandardJsonAdapters$1.create(SourceFile:67)
        at com.squareup.moshi.Moshi.adapter(SourceFile:141)
        at com.tsystems.tpay.data.client.models.ContactApiModelJsonAdapter.<init>(SourceFile:30)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.squareup.moshi.internal.Util.generatedAdapter(SourceFile:553)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(SourceFile:193)
        at com.squareup.moshi.Moshi.adapter(SourceFile:141)
        at com.squareup.moshi.Moshi.adapter(SourceFile:101)
        at com.squareup.moshi.Moshi.adapter(SourceFile:71)
        at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(SourceFile:52)
        at com.squareup.moshi.CollectionJsonAdapter$1.create(SourceFile:36)
        at com.squareup.moshi.Moshi.adapter(SourceFile:141)
        at com.squareup.moshi.Moshi.adapter(SourceFile:101)
        at p.z.a.a.a(SourceFile:91)
        at p.u.a(SourceFile:352)
        at p.u.b(SourceFile:335)
        at p.k.a(SourceFile:113)
        at p.k.a(SourceFile:82)
        at p.v.a(SourceFile:37)
        at p.u.a(SourceFile:192)
        at p.u$a.invoke(SourceFile:149)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy14.c(Unknown Source)
        at e.f.a.k.b.f$g.a(SourceFile:87)
        at i.b0.j.a.a.b(SourceFile:33)
        at j.a.v0.run(SourceFile:241)
        at j.a.g3.a.a(SourceFile:594)
        at j.a.g3.a.a(SourceFile:60)
        at j.a.g3.a$b.run(SourceFile:740)
     Caused by: java.lang.NoSuchFieldException: PERSONAL
        at java.lang.Class.getField(Class.java:1604)
        at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.<init>(SourceFile:240)
```

@ZacSweers i hope it is OK that i ping you for this. :)

**Comment by ZacSweers** [comment]
Usage questions should be posted on stackoverflow with the Moshi tag

**Comment by WonderCsabo** [comment]
Well, i spent some time with this, and i considered this is a bug, that is why opened a github issue here.

**Comment by ZacSweers** [comment]
It's not a bug. Like anything else using reflection, there must be a rule. And there is. Ask on stackoverflow and I'll answer there 👍

**Comment by WonderCsabo** [comment]
To clarify the project setup follows the README, and everything is working correctly if i add keep rules to keep all of my classes and properties. However the README says:

> Moshi contains minimally required rules for its own internals to work without need for consumers to embed their own. However if you are using reflective serialization and R8 or ProGuard, you must add keep rules in your proguard configuration file for your reflectively serialized classes.

According to this line, i do not have to add any of the keep rules manually. I see that moshi-codegen generates some rules, it works well for data classes, but i ran into this issue with enums. I suspected another rule should be generated / bundled into the library specifically for enums. Or maybe the readme should be clarified a bit.

I will post to stackoverflow as requested. :)
