### ISSUE TITLE
Release build / RuntimeException: Failed to find the generated JsonAdapter constructor

### ISSUE THREAD

**Issue by johnjohndoe** [square/moshi#1266]
In [my Android application project](https://github.com/EventFahrplan/EventFahrplan) I am depending on [a Kotlin library](https://github.com/johnjohndoe/engelsystem) which itself depends on Moshi 1.9.3 and uses `moshi-kotlin-codegen`.

``` kotlin
@JsonClass(generateAdapter = true)
data class Shift internal constructor( /* ... */ )
```

When I update Moshi in the application project from 1.9.3 to 1.10.0 or 1.11.0 I get the following error for the **release** build:

```
...
Caused by: java.lang.RuntimeException: Failed to find the generated JsonAdapter constructor for 
  class info.metadude.kotlin.library.engelsystem.models.Shift
    at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:591)
    at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:61)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:74)
    at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:54)
    at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:38)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
    at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
    at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:91)
    at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
    at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313)
    at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:113)
    ... 14 more
Caused by: java.lang.NoSuchMethodException: info.metadude.kotlin.library.engelsystem.models.ShiftJsonAdapter.<init> []
    at java.lang.Class.getConstructor0(Class.java:2332)
    at java.lang.Class.getDeclaredConstructor(Class.java:2170)
    at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:572)
    ... 26 more
```

I am aware that the newest Moshi version is transitively applied to the library as well:

```
info.metadude.kotlin.library.engelsystem:engelsystem-base:4.0.1
  com.squareup.moshi:moshi:1.9.3 -> 1.11.0
```

Can this be fixed by adding a ProGuard/R8 rule to keep any classes inheriting from `JsonAdapter` or do I have to update the library to Moshi 1.11.0 before it can be used in the app?

**Comment by ZacSweers** [comment]
Moshi no longer packages blanket proguard rules and newer code gen versions generate rules on the fly. We probably should have called this out in release notes, but you can restore prev behavior by copying the embedded proguard rules from Moshi 1.9.3 into your rules

**Comment by johnjohndoe** [comment]
I found the ProGuard rules from Moshi 1.9.3 [here](https://raw.githubusercontent.com/square/moshi/moshi-parent-1.9.3/moshi/src/main/resources/META-INF/proguard/moshi.pro). - Thank you, this helps a lot. This issue can be closed.
