### ISSUE TITLE
Android: failing to find adapter for a 'GenericArrayTypeImpl' type

### ISSUE THREAD

**Issue by bjdodson** [square/moshi#128]
We have an adapter in place to process `byte[]` as a base64 / base32 string. Everything works fine when a class has a `byte[]` field, but parsing json fails on Android when we have a field of type `Map<String, byte[]>`. The code below works in the standard JVM but fails on Android.

``` java
  class Base32Adapter extends JsonAdapter<byte[]>  {
    @Override
    public byte[] fromJson(JsonReader reader) throws IOException {
      String string = reader.nextString();
      return new BigInteger(string, 32).toByteArray();
    }

    @Override
    public void toJson(JsonWriter writer, byte[] bytes) throws IOException {
      String string = new BigInteger(bytes).toString(32);
      writer.value(string);
    }
  }

  static class FavoriteBytes {
    @Json(name = "Bytes")
    public Map<String, byte[]> keys;
  }

  @Test public void customAdapter() throws Exception {
    String jsonString = "{\"Bytes\":{\"jesse\":\"a\",\"jake\":\"1\"}}";
    Moshi binaryMoshi = new Moshi.Builder().add(byte[].class, new Base32Adapter()).build();
    FavoriteBytes fav = binaryMoshi.adapter(FavoriteBytes.class).fromJson(jsonString);

    assertThat(fav.keys).containsOnlyKeys("jesse", "jake");
    assertThat(fav.keys.get("jesse")).isEqualTo(new byte[] { 0xa });
    assertThat(fav.keys.get("jake")).isEqualTo(new byte[] { 0x1 });
  }
```

On Android, this fails with exception:

```
E/MoshiTest(18268): com.squareup.moshi.JsonDataException: Expected BEGIN_ARRAY but was STRING at path $.Keys.jesse
E/MoshiTest(18268):     at com.squareup.moshi.JsonReader.beginArray(JsonReader.java:346)
E/MoshiTest(18268):     at com.squareup.moshi.ArrayJsonAdapter.fromJson(ArrayJsonAdapter.java:53)
E/MoshiTest(18268):     at com.squareup.moshi.JsonAdapter$1.fromJson(JsonAdapter.java:68)
E/MoshiTest(18268):     at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:68)
E/MoshiTest(18268):     at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:29)
E/MoshiTest(18268):     at com.squareup.moshi.JsonAdapter$1.fromJson(JsonAdapter.java:68)
E/MoshiTest(18268):     at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:183)
E/MoshiTest(18268):     at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:144)
E/MoshiTest(18268):     at com.squareup.moshi.JsonAdapter$1.fromJson(JsonAdapter.java:68)
E/MoshiTest(18268):     at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:33)
E/MoshiTest(18268):     at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:37)
...
```

**Comment by bjdodson** [comment]
Logging the type lookups in the JVM:
```
Lookup for class com.squareup.moshi.MapJsonAdapterTest$FavoriteBytes 
   is class java.lang.Class 
   raw class com.squareup.moshi.MapJsonAdapterTest$FavoriteBytes

Lookup for java.util.Map<java.lang.String, byte[]> 
   is class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl 
   raw interface java.util.Map

Lookup for class java.lang.String 
   is class java.lang.Class 
   raw class java.lang.String

Lookup for class [B 
   is class java.lang.Class 
   raw class [B
```

For Android (Lollipop)
```
I/System.out(13735): Lookup for class mobisocial.omlib.service.OmlibContentProvider$FavoriteBytes 
I/System.out(13735):    is class java.lang.Class 
I/System.out(13735):    raw class mobisocial.omlib.service.OmlibContentProvider$FavoriteBytes

I/System.out(13735): Lookup for java.util.Map<java.lang.String, byte[]> 
I/System.out(13735):    is class libcore.reflect.ParameterizedTypeImpl 
I/System.out(13735):    raw interface java.util.Map

I/System.out(13735): Lookup for class java.lang.String 
I/System.out(13735):    is class java.lang.Class 
I/System.out(13735):    raw class java.lang.String

I/System.out(13735): Lookup for byte[] 
I/System.out(13735):    is class libcore.reflect.GenericArrayTypeImpl 
I/System.out(13735):    raw class [B

I/System.out(13735): Lookup for byte 
I/System.out(13735):    is class java.lang.Class 
I/System.out(13735):    raw byte
```

**Comment by swankjesse** [comment]
Ahh, yeah we likely need to canonicalize the lookup type when we delegate from the Map adapter. It’s annoying that there’s two different, non-equal `java.lang.reflect.Type` values for `byte[]` and all other arrays.

**Comment by bjdodson** [comment]
Those Dalvik guys...
