### ISSUE TITLE
Ques: Skip bad element from a list for polymorphic type

### ISSUE THREAD

**Issue by kdani41** [square/moshi#1288]
I am trying to use the adapter mentioned [here](https://stackoverflow.com/a/54190660/3354265) to skip the bad element from `List<Any?>` but this implementation doesn't seems to work with `PolymorphicJsonAdapterFactory`. 
Do I need to add something special to support polymorphic type?

## Stacktrace

```
2021-01-21 00:58:49.240 19633-19633/com.blah E/AndroidRuntime:     at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:61)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:74)
        at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory.create(PolymorphicJsonAdapterFactory.java:216)
        at com.blah.models.ABC_StyleJsonAdapter.<init>(ABC_StyleJsonAdapter.kt:21)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:577)
        at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:61)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
        at com.blah.models.CJsonAdapter.<init>(CJsonAdapter.kt:30)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:577)
        at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:61)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
        at com.blah.models.KType_CJsonAdapter.<init>(KType_CJsonAdapter.kt:27)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:577)
        at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:61)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:74)
2021-01-21 00:58:49.240 19633-19633/com.blah E/AndroidRuntime:     at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
        at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:89)
        at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:362)
        at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:345)
        at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:124)
```
## Adapter

```kotlin
internal class SkipBadElementsListAdapter(private val elementAdapter: JsonAdapter<Any?>) :
    JsonAdapter<List<Any?>>() {

    object Factory : JsonAdapter.Factory {
        override fun create(
            type: Type,
            annotations: Set<Annotation>,
            moshi: Moshi
        ): JsonAdapter<*>? {
            if (annotations.isNotEmpty() || Types.getRawType(type) != List::class.java) {
                return null
            }
            val elementType = Types.collectionElementType(type, List::class.java)
            val elementAdapter = moshi.adapter<Any?>(elementType)
            return SkipBadElementsListAdapter(elementAdapter)
        }
    }

    override fun fromJson(reader: JsonReader): List<Any?>? {
        val result = mutableListOf<Any?>()
        reader.beginArray()
        while (reader.hasNext()) {
            try {
                val peeked = reader.peekJson()
                result += elementAdapter.fromJson(peeked)
            } catch (ignored: JsonDataException) {
            }
            reader.skipValue()
        }
        reader.endArray()
        return result

    }

    override fun toJson(writer: JsonWriter, value: List<Any?>?) {
        if (value == null) {
            throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
        }
        writer.beginArray()
        for (i in value.indices) {
            elementAdapter.toJson(writer, value[i])
        }
        writer.endArray()
    }
}
```

**Comment by kdani41** [comment]
@ZacSweers Sorry tagging you here. This occurred when I'm using `sealed` codegen from [MoshiSealed](https://github.com/ZacSweers/MoshiX/tree/main/moshi-sealed)  
 Can you please confirm if this is a valid issue?

**Comment by ZacSweers** [comment]
Usage questions should go on stackoverflow and use the `moshi` tag

**Comment by kdani41** [comment]
@ZacSweers  Sorry with my title there. But I am getting an exception in `PolymorphicJsonAdapterFactory`. Would it still be a usage question?
