### ISSUE TITLE
NoSuchMethodError during kapt codegen 

### ISSUE THREAD

**Issue by jdegroot** [square/moshi#1291]
I have the following issue while building my project with Moshi v1.11.0 and the Gradle worker api:

```
Caused by: java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReferenceImpl.<init>(ILjava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V	
    at com.squareup.moshi.kotlin.codegen.api.ProguardConfig$writeTo$2$2.<init>(ProguardRules.kt)	
    at com.squareup.moshi.kotlin.codegen.api.ProguardConfig$writeTo$2$2.<clinit>(ProguardRules.kt)	
    at com.squareup.moshi.kotlin.codegen.api.ProguardConfig.writeTo(ProguardRules.kt:83)	
    at com.squareup.moshi.kotlin.codegen.api.ProguardConfig.writeTo(ProguardRules.kt:51)	
    at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.process(JsonClassCodegenProcessor.kt:137)	
    at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)	
    at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:161)	
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)	
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)	
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)	
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)	
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)	
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)	
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)	
    at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:78)	
    at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:34)	
    at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:45)	
    at org.jetbrains.kotlin.gradle.internal.KaptExecution.run(KaptWithoutKotlincTask.kt:158)	
    at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)	
    at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)	
    at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)	
    at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)	
    at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)	
    at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)	
    at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)	
    at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)	
    at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)	
    at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)	
    at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)	
    at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)	
    at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)	
    at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)	
    at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)	
    at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)	
    at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)	
    at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)	
    at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)	
    at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)	
    at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)	
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)	
    at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)	
    at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
```

The issue does not occur when disabling the worker api for kapt:

```
kapt.use.worker.api=false
```

In that case the project builds without failure. I have not been able to reproduce this issue outside of this one project. Does anyone know what might be wrong here?

**Comment by ZacSweers** [comment]
Sounds like your project is still using an older version of kotlin. Moshi uses 1.4.x

**Comment by jdegroot** [comment]
That's what I thought as well but the project is using Kotlin `1.4.10`. Also I couldn't explain why disabling the worker api fixes the problem.

**Comment by ZacSweers** [comment]
Can you make a reproducible sample project?

**Comment by jdegroot** [comment]
I've not been able to reproduce the issue outside of this one project, but I'll give it another shot. 

I understand it's hard to figure out what the issue is without being able to reproduce it, was just hoping someone saw this before and knew a solution : -)

**Comment by ZacSweers** [comment]
Ok, feel free to revisit if you can make a public repro
