### ISSUE TITLE
Combining DefaultOnDataMismatchAdapter with an adapter from PolymorphicJsonAdapterFactory throws a StackOverflowError

### ISSUE THREAD

**Issue by xxfast** [square/moshi#1300]
Not entirely sure if I'm using this correctly or if this is indeed a defect. But my intention is to combine behaviours of both `DefaultOnDataMismatchAdapter` and `PolymorphicJsonAdapterFactory`

Here's a simple test to reproduce this
```kotlin
class Test{
  @Test fun test() {
    val json = "{\"type\":\"A\",\"propA\":\"1\"}"

    val dataMismatchAdapter = DefaultOnDataMismatchAdapter.create<Parent>(ChildC(false))

    val polymorphicJsonAdapter = PolymorphicJsonAdapterFactory.of(Parent::class.java, "type")
        .withSubtype(ChildA::class.java, "A")
        .withSubtype(ChildB::class.java, "B")
        .withSubtype(ChildC::class.java, "C")

    val moshi = Moshi.Builder()
        .add(dataMismatchAdapter)
        .add(polymorphicJsonAdapter)
        .add(KotlinJsonAdapterFactory())
        .build()

    val adapter: JsonAdapter<Parent> = moshi.adapter(Parent::class.java)
    val instance: Parent = adapter.fromJson(json)!!

    assertThat(adapter.toJson(instance)).isEqualTo(json)
  }

  sealed class Parent {
    data class ChildA(val propA: String): Parent()
    data class ChildB(val propB: Int): Parent()
    data class ChildC(val propC: Boolean): Parent()
  }
}
```

`DefaultOnDataMismatchAdapter` is based off from this [recipe](https://github.com/square/moshi/blob/master/examples/src/main/java/com/squareup/moshi/recipes/DefaultOnDataMismatchAdapter.java). _However_, I did tweak my implementation by adding the ability to handle interfaces
```kotlin
class DefaultOnDataMismatchAdapter<T>(
    private val delegate: JsonAdapter<T>,
    private val defaultValue: T?
) : JsonAdapter<T?>() {

  ... // Same as the recipe 

  companion object {
    inline fun <reified T> create(defaultValue: T?): Factory {
      return object : Factory {
       private val type: Class<T> = T::class.java
        override fun create(requestedType: Type, annotations: Set<Annotation?>,
                            moshi: Moshi): JsonAdapter<*>? {
          val isTheSame: Boolean = T::class.java == requestedType
          // Tweak to see if requested raw type can be assigned to given type
          val isAChild: Boolean = type.isAssignableFrom(requestedType.rawType)
          if (!isTheSame && !isAChild) return null
          val delegate: JsonAdapter<T> = moshi.nextAdapter(this, T::class.java, annotations)
          return DefaultOnDataMismatchAdapter(delegate, defaultValue)
        }
      }
    }
  }
}

```

EDIT: forgot to put the stacktrace, basically this repeated many times
```
	at com.squareup.moshi.Moshi$Lookup.fromJson(Moshi.java:408)
	at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.fromJson(PolymorphicJsonAdapterFactory.java:264)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at au.com.gridstone.pscore.hkpf.search.data.adapters.DefaultOnDataMismatchAdapter.fromJson(DefaultOnDataMismatchAdapter.kt:28)
	at com.squareup.moshi.Moshi$Lookup.fromJson(Moshi.java:408)
	at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.fromJson(PolymorphicJsonAdapterFactory.java:264)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at au.com.gridstone.pscore.hkpf.search.data.adapters.DefaultOnDataMismatchAdapter.fromJson(DefaultOnDataMismatchAdapter.kt:28)
	at com.squareup.moshi.Moshi$Lookup.fromJson(Moshi.java:408)
```

**Comment by ZacSweers** [comment]
Let's keep the issue tracker for Moshi's first party offerings, this is a question for help with your custom implementation and should be asked on stackoverflow
