### ISSUE TITLE
PolymorphicJsonAdapterFactory only supports json string labels

### ISSUE THREAD

**Issue by maciej-kaznowski** [square/moshi#1321]
Hi, I have the following (simplified) json:

```
{
  "data": [
    {
      "was_comment": false
    },
    {
      "was_comment": true
    }
  ]
}
```

I wanted to de serialize these objects depending on the value of `was_comment`:

```
PolymorphicJsonAdapterFactory.of(Message::class.java, "was_comment")
                         .withSubtype(RedditCommentMessage::class.java, "true")
                         .withSubtype(RedditPrivateMessage::class.java, "false")
```

However the `com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory.PolymorphicJsonAdapter` only works for labels which are strings:
https://github.com/square/moshi/blob/797140c5cf0e376387b99fcaa8cc00988d1ffbb5/adapters/src/main/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactory.java#L277

so it throws an exception:

```
com.squareup.moshi.JsonDataException: Expected a string but was BOOLEAN at path $.data.children[0].data.was_comment

	at com.squareup.moshi.JsonUtf8Reader.nextString(JsonUtf8Reader.java:674)
	at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.labelIndex(PolymorphicJsonAdapterFactory.java:285)
	at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.fromJson(PolymorphicJsonAdapterFactory.java:257)
```

So I believe it may be beneficial to add support for the other types:
- boolean
- double, int, long
- null

**Comment by ZacSweers** [comment]
What would the API for that look like?

**Comment by maciej-kaznowski** [comment]
Sorry for the late response.

I think the simplest approach would simply be to add methods for the other types:

Current:
`com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory#withSubtype(java.lang.Class<? extends T>, java.lang.String)`


New methods:
```
com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory#withSubtype(java.lang.Class<? extends T>, boolean)
com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory#withSubtype(java.lang.Class<? extends T>, double)
com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory#withSubtype(java.lang.Class<? extends T>, int)
com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory#withSubtype(java.lang.Class<? extends T>, long)
com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory#withNullSubtype(java.lang.Class<? extends T>)
```

The adapter would need to be modified a little to not assume it's a string.

Then again I wonder whether this is the right approach - suppose our json has an "id" value, taking values such as `t1_1234`, `t2_1234`, `t3_1234` etc, where t1, t2, t3... denote the type of object. Then simply assuming constants values for type of json object wouldn't work since it's determined by a part of the value. In that case it would be good to have an adapter which could peek over the json to determine what type of object it is, before handling over to the appropriate adapter.

**Comment by ZacSweers** [comment]
I think a potentially more useful approach would be a json qualifier passed by the factory when searching for a delegate string adapter, then any type could be represented and simply intercepted

**Comment by overfullstack** [comment]
@maciej-kaznowski Have you found a way to achieve this? If yes, can you please help with a code reference? Thanks!
