### ISSUE TITLE
Kotlin metadata error with Kotlin preview builds

### ISSUE THREAD

**Issue by vRallev** [square/moshi#1324]
Using Kotlin preview builds like `1.5.20-dev-3628` results in following error:
```
Caused by: java.lang.IllegalStateException: Could not parse metadata! This should only happen if you're using Kotlin <1.1.
        at com.squareup.moshi.kotlinpoet.metadata.KotlinPoetMetadata.readKotlinClassMetadata(KotlinPoetMetadata.kt:70)
        at com.squareup.moshi.kotlinpoet.metadata.KotlinPoetMetadata.toImmutableKmClass(KotlinPoetMetadata.kt:50)
        at com.squareup.moshi.kotlin.codegen.MoshiCachedClassInspector.toImmutableKmClass(MoshiCachedClassInspector.kt:22)
        at com.squareup.moshi.kotlin.codegen.MetadataKt.targetType(metadata.kt:109)
        at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.adapterGenerator(JsonClassCodegenProcessor.kt:136)
        at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.process(JsonClassCodegenProcessor.kt:110)
        at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
        at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:175)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
        ... 41 more
```
There's no special sample required, it happens with any Kotlin file. This issue doesn't happen with the latest announced version `1.5.0-M1`.

**Comment by ZacSweers** [comment]
This is probably due to kotlinx-metadata needing a newer version. They have a 0.2.0 planned but not released yet

**Comment by vRallev** [comment]
This became an issue in `1.5.0-M2`.

**Comment by vRallev** [comment]
Seems like `0.2.0` was released a while ago: https://search.maven.org/artifact/org.jetbrains.kotlinx/kotlinx-metadata-jvm/0.2.0/jar

**Comment by ZacSweers** [comment]
Yup I was thinking of 0.2.1 not 0.2.0

**Comment by gajicm93** [comment]
This seems to be happening again with Kotlin 1.5.30?

**Comment by theapache64** [comment]
1.5.31 also affected i gues

**Comment by bmarty** [comment]
This seems to be happening again with Kotlin 1.6.0

**Comment by ZacSweers** [comment]
Known issue, it will be updated in the next release (waiting for KSP to release)

**Comment by niqo01** [comment]
Which KSP issue is this waiting on?

**Comment by AlexZvonik** [comment]
The issue is reproducible with moshi 1.12.0 and kotlin 1.6.0
