### ISSUE TITLE
Bool Adapter Error 

### ISSUE THREAD

**Issue by Yinzeyu** [square/moshi#1341]
implementation("com.squareup.moshi:moshi:1.12.0")
    kapt 'com.squareup.moshi:moshi-kotlin-codegen:1.12.0'
implementation 'com.squareup.moshi:moshi-kotlin:1.12.0'
 val moshi = Builder()
    .add(KotlinJsonAdapterFactory())
    .add(BooleanAdapter())
    .build()
 val json = "{\"type\":true}"
  val example: ExampleClass = moshi.adapter(ExampleClass::class.java).fromJson(json)!!
  System.out.println("${example.type}")

@JsonClass(generateAdapter = true)
data class ExampleClass(
  var type: Boolean=false
)
Exception in thread "main" com.squareup.moshi.JsonDataException: Expected an int but was BOOLEAN at path $.type
	at com.squareup.moshi.JsonUtf8Reader.nextInt(JsonUtf8Reader.java:949)
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:196)
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:193)
	at com.squareup.moshi.AdapterMethodsFactory$5.fromJson(AdapterMethodsFactory.java:295)
	at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:97)
	at com.example.myapplication.ExampleClassJsonAdapter.fromJson(ExampleClassJsonAdapter.kt:45)
	at com.example.myapplication.ExampleClassJsonAdapter.fromJson(ExampleClassJsonAdapter.kt:24)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
	at com.example.myapplication.JsonStringKt.main(JsonString.kt:68)
	at com.example.myapplication.JsonStringKt.main(JsonString.kt)

**Comment by Yinzeyu** [comment]
data class ExampleClass(
  var type: Boolean
)
  val moshi = Builder()
    .add(KotlinJsonAdapterFactory())
    .add(BooleanAdapter())
    .build()
//
  val json = "{\"type\":true}"
  val example: ExampleClass = moshi.adapter(ExampleClass::class.java).fromJson(json)!!
  System.out.println("${example.type}")

Exception in thread "main" com.squareup.moshi.JsonDataException: Expected an int but was BOOLEAN at path $.type
	at com.squareup.moshi.JsonUtf8Reader.nextInt(JsonUtf8Reader.java:949)
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:196)
	at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:193)
	at com.squareup.moshi.AdapterMethodsFactory$5.fromJson(AdapterMethodsFactory.java:295)
	at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:97)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:84)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
	at com.example.myapplication.JsonStringKt.main(JsonString.kt:68)
	at com.example.myapplication.JsonStringKt.main(JsonString.kt)

**Comment by ZacSweers** [comment]
Can you paste the generated adapter?

**Comment by Yinzeyu** [comment]
class BooleanAdapter {
    @ToJson
    fun toJson(value: Boolean): Int {
        return if (value) 1 else 0
    }

    @FromJson
    fun fromJson(value: Int): Boolean {
        return value == 1
    }
}




// Code generated by moshi-kotlin-codegen. Do not edit.
@file:Suppress("DEPRECATION", "unused", "ClassName", "REDUNDANT_PROJECTION",
    "RedundantExplicitType", "LocalVariableName", "RedundantVisibilityModifier",
    "PLATFORM_CLASS_MAPPED_TO_KOTLIN")

package com.example.myapplication

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.`internal`.Util
import java.lang.NullPointerException
import kotlin.Boolean
import kotlin.String
import kotlin.Suppress
import kotlin.Unit
import kotlin.collections.emptySet
import kotlin.text.buildString

public class ExampleClassJsonAdapter(
  moshi: Moshi
) : JsonAdapter<ExampleClass>() {
  private val options: JsonReader.Options = JsonReader.Options.of("type")

  private val booleanAdapter: JsonAdapter<Boolean> = moshi.adapter(Boolean::class.java, emptySet(),
      "type")

  public override fun toString(): String = buildString(34) {
      append("GeneratedJsonAdapter(").append("ExampleClass").append(')') }

  public override fun fromJson(reader: JsonReader): ExampleClass {
    var type: Boolean? = null
    reader.beginObject()
    while (reader.hasNext()) {
      when (reader.selectName(options)) {
        0 -> type = booleanAdapter.fromJson(reader) ?: throw Util.unexpectedNull("type", "type",
            reader)
        -1 -> {
          // Unknown name, skip it.
          reader.skipName()
          reader.skipValue()
        }
      }
    }
    reader.endObject()
    return ExampleClass(
        type = type ?: throw Util.missingProperty("type", "type", reader)
    )
  }

  public override fun toJson(writer: JsonWriter, value_: ExampleClass?): Unit {
    if (value_ == null) {
      throw NullPointerException("value_ was null! Wrap in .nullSafe() to write nullable values.")
    }
    writer.beginObject()
    writer.name("type")
    booleanAdapter.toJson(writer, value_.type)
    writer.endObject()
  }
}

**Comment by Yinzeyu** [comment]
Solution
https://stackoverflow.com/questions/48918990/dealing-with-one-field-that-is-sometimes-boolean-and-sometimes-int
