### ISSUE TITLE
Custom field name is not allowed?

### ISSUE THREAD

**Issue by felipeska** [square/moshi#1346]
I have this code:

``` kotlin
open class Animal<T>(
  @Json(name = "name") val name: String,
  @Json(name = "kind") val kind: String,
  @Json(name = "value") val value: T
)

class Reptile(name: String, kind: String, value: String) : Animal<String>(name, kind, value)
class Bird(name: String, kind: String, value: Int) : Animal<Int>(name, kind, value)

fun main() {

  val moshi = Moshi.Builder()
    .add(
      PolymorphicJsonAdapterFactory.of(Animal::class.java, "kind")
        .withSubtype(Reptile::class.java, "REPTILE")
        .withSubtype(Bird::class.java, "BIRD")
    )
    .addLast(KotlinJsonAdapterFactory()).build()

  val jsonSnake = "{\n" +
      "  \"name\" : \"snake\",\n" +
      "  \"value\" : \"foo\",\n" +
      "  \"kind\" : \"REPTILE\"\n" +
      "}"
  val snake: Animal<*>? = moshi.adapter(Animal::class.java).fromJson(jsonSnake)
  println(snake is Reptile)
  println((snake as Reptile).value)
  println(snake is Bird)

  println()

  val jsonEagle = "{\n" +
      "  \"name\" : \"eagle\",\n" +
      "  \"value\" : 10,\n" +
      "  \"kind\" : \"BIRD\"\n" +
      "}"

  val eagle: Animal<*>? = moshi.adapter(Animal::class.java).fromJson(jsonEagle)
  println(eagle is Reptile)
  println((eagle as Bird).value)
  println(eagle is Reptile)
}
```

The result looks good:

```java
true
foo
false

false
10
false
```
I do a little modification in my code by changing the name in a json field (now  `@Json(name = "value") val value: T`  is changed to  `@Json(name = "other") val value: T)`

```kotlin
open class Animal<T>(
  @Json(name = "name") val name: String,
  @Json(name = "kind") val kind: String,
  // Json name changed
  @Json(name = "other") val value: T
)

fun main() {

  val moshi = Moshi.Builder()
    .add(
      PolymorphicJsonAdapterFactory.of(Animal::class.java, "kind")
        .withSubtype(Reptile::class.java, "REPTILE")
        .withSubtype(Bird::class.java, "BIRD")
    )
    .addLast(KotlinJsonAdapterFactory()).build()

  val jsonSnake = "{\n" +
      "  \"name\" : \"snake\",\n" +
      "  \"other\" : \"foo\",\n" +
      "  \"kind\" : \"REPTILE\"\n" +
      "}"
  val snake: Animal<*>? = moshi.adapter(Animal::class.java).fromJson(jsonSnake)
  println(snake is Reptile)
  println((snake as Reptile).value)
  println(snake is Bird)

  println()

  val jsonEagle = "{\n" +
      "  \"name\" : \"eagle\",\n" +
      "  \"other\" : 10,\n" +
      "  \"kind\" : \"BIRD\"\n" +
      "}"

  val eagle: Animal<*>? = moshi.adapter(Animal::class.java).fromJson(jsonEagle)
  println(eagle is Reptile)
  println((eagle as Bird).value)
  println(eagle is Reptile)
}
```
it is returning me the following exception:

```java
Exception in thread "main" com.squareup.moshi.JsonDataException: Required value 'value' missing at $
	at com.squareup.moshi.internal.Util.missingProperty(Util.java:649)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:103)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.fromJson(PolymorphicJsonAdapterFactory.java:264)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
```
It is mandatory that the field name in the json is the same as the field in the class?

**Comment by ZacSweers** [comment]
Please use stackoverflow for usage questions like our issue template asks. Thanks!
