### ISSUE TITLE
Why Moshi Can't parser Json with generic types?

### ISSUE THREAD

**Issue by pokerfaceCmy** [square/moshi#1363]
I have endpoint definitions that use generic types, like this:

```
@GET("banner/json")
    suspend fun getBanner(): MutableList<Banner>
```

and i have a retrofit Converter , like this(i want handle ServerException in Converter ) :

```
class RetroMoshiResponseBodyConverter<T, ApiResultType : IApiResult<*>> constructor(
    private val moshi: Moshi,
    private val type: Type,
    private val apiClass: Class<ApiResultType>,
) : Converter<ResponseBody, T> {

    @Suppress("UNCHECKED_CAST")
    override fun convert(value: ResponseBody): T? {
        return value.use { v ->
            val response = v.string()
            val adapter: JsonAdapter<ApiResultType> = moshi.adapter(apiClass)
            val bean = adapter.fromJson(response)
            
            if (bean?.isSuccess == false) throw ServerException(bean.httpCode, bean.httpMsg)

            bean?.httpData as T
        }
    }
}
```

```
@JsonClass(generateAdapter = true)
data class DataWrapper<Data>(
    val data: Data,
    val errorCode: Int,
    val errorMsg: String = ""
): IApiResult<Data> {
    override val isSuccess: Boolean
        get() = errorCode == 0

    override val httpData: Data
        get() = data

    override val httpMsg: String
        get() = errorMsg

    override val httpCode: Int
        get() = errorCode

    override val dataField: String
        get() = "data"
}
```

```
@Provides
    @Singleton
    fun provideMoshi(): Moshi {
        return Moshi.Builder()
            .addLast(KotlinJsonAdapterFactory())
            .build()
    }
```

so i get a  problem

```
2021-07-08 16:08:25.337 21394-21394/com.poker.pixiu W/System.err: java.lang.IllegalArgumentException: No JsonAdapter for Data (with no annotations)
2021-07-08 16:08:25.337 21394-21394/com.poker.pixiu W/System.err: for Data data
2021-07-08 16:08:25.337 21394-21394/com.poker.pixiu W/System.err: for class com.poker.pixiu.app.bean.DataWrapper
2021-07-08 16:08:25.337 21394-21394/com.poker.pixiu W/System.err:     at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:388)
2021-07-08 16:08:25.337 21394-21394/com.poker.pixiu W/System.err:     at com.squareup.moshi.Moshi.adapter(Moshi.java:157)
2021-07-08 16:08:25.337 21394-21394/com.poker.pixiu W/System.err:     at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:262)
2021-07-08 16:08:25.337 21394-21394/com.poker.pixiu W/System.err:     at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
2021-07-08 16:08:25.338 21394-21394/com.poker.pixiu W/System.err:     at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
2021-07-08 16:08:25.338 21394-21394/com.poker.pixiu W/System.err:     at com.squareup.moshi.Moshi.adapter(Moshi.java:79)
2021-07-08 16:08:25.338 21394-21394/com.poker.pixiu W/System.err:     at com.poker.common.network.converter.RetroMoshiResponseBodyConverter.convert(RetroMoshiResponseBodyConverter.kt:32)
2021-07-08 16:08:25.338 21394-21394/com.poker.pixiu W/System.err:     at com.poker.common.network.converter.RetroMoshiResponseBodyConverter.convert(RetroMoshiResponseBodyConverter.kt:22)
2021-07-08 16:08:25.338 21394-21394/com.poker.pixiu W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
2021-07-08 16:08:25.338 21394-21394/com.poker.pixiu W/System.err:     at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
2021-07-08 16:08:25.338 21394-21394/com.poker.pixiu W/System.err:     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
2021-07-08 16:08:25.338 21394-21394/com.poker.pixiu W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-07-08 16:08:25.338 21394-21394/com.poker.pixiu W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-07-08 16:08:25.338 21394-21394/com.poker.pixiu W/System.err:     at java.lang.Thread.run(Thread.java:923)
2021-07-08 16:08:25.339 21394-21394/com.poker.pixiu W/System.err: Caused by: java.lang.IllegalArgumentException: No JsonAdapter for Data (with no annotations)
2021-07-08 16:08:25.339 21394-21394/com.poker.pixiu W/System.err:     at com.squareup.moshi.Moshi.adapter(Moshi.java:155)
2021-07-08 16:08:25.339 21394-21394/com.poker.pixiu W/System.err: 	... 12 more
```

**Comment by ZacSweers** [comment]
Usage questions should go on stackoverflow.
