### ISSUE TITLE
How to fix "Nesting too deep at"

### ISSUE THREAD

**Issue by onexuan** [square/moshi#1386]
com.squareup.moshi.JsonDataException: Nesting too deep at $.treeModel.rootNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes[0].parentNode.childNodes: circular reference?
        at com.squareup.moshi.JsonWriter.checkStack(JsonWriter.java:200)
        at com.squareup.moshi.JsonUtf8Writer.open(JsonUtf8Writer.java:125)
        at com.squareup.moshi.JsonUtf8Writer.beginArray(JsonUtf8Writer.java:92)
        at com.squareup.moshi.CollectionJsonAdapter.toJson(CollectionJsonAdapter.java:89)
        at com.squareup.moshi.CollectionJsonAdapter$2.toJson(CollectionJsonAdapter.java:55)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
        at com.squareup.moshi.ClassJsonAdapter$FieldBinding.write(ClassJsonAdapter.java:250)
        at com.squareup.moshi.ClassJsonAdapter.toJson(ClassJsonAdapter.java:218)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
        at com.squareup.moshi.Moshi$Lookup.toJson(Moshi.java:414)
        at com.squareup.moshi.ClassJsonAdapter$FieldBinding.write(ClassJsonAdapter.java:250)
        at com.squareup.moshi.ClassJsonAdapter.toJson(ClassJsonAdapter.java:218)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
        at com.squareup.moshi.Moshi$Lookup.toJson(Moshi.java:414)
        at com.squareup.moshi.CollectionJsonAdapter.toJson(CollectionJsonAdapter.java:91)
        at com.squareup.moshi.CollectionJsonAdapter$2.toJson(CollectionJsonAdapter.java:55)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
        at com.squareup.moshi.ClassJsonAdapter$FieldBinding.write(ClassJsonAdapter.java:250)
        at com.squareup.moshi.ClassJsonAdapter.toJson(ClassJsonAdapter.java:218)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
        at com.squareup.moshi.Moshi$Lookup.toJson(Moshi.java:414)
        at com.squareup.moshi.ClassJsonAdapter$FieldBinding.write(ClassJsonAdapter.java:250)

**Comment by ZacSweers** [comment]
Usage questions belong on stackoverflow
