### ISSUE TITLE
Not able to deserialize a value class

### ISSUE THREAD

**Issue by ampeixoto** [square/moshi#1388]
I am not sure if this is a bug or only a feature not implemented, but I will expose a piece of code to reproduce it.

Code:
```
package my.app

import com.squareup.moshi.FromJson
import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi
import com.squareup.moshi.ToJson
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory

@JvmInline
//@JsonClass(generateAdapter = true)
value class Revision(val value: String)
class RevisionAdapter {
    @ToJson
    fun toJson(x: Revision): String {
        return x.value
    }

    @FromJson
    fun fromJson(x: String): Revision {
        return Revision(x)
    }
}

@JsonClass(generateAdapter = true)
data class MyDto(
    val someField: Int? = null,
    val revision: Revision? = null,
)

fun main() {
    val moshiBuilder = Moshi.Builder()
    val moshi = moshiBuilder
        .add(RevisionAdapter())
//        .addLast(KotlinJsonAdapterFactory())
        .build()
    val adapter = moshi.adapter(MyDto::class.java)

    val objectToSerialize = MyDto(
        someField = 987,
        revision = Revision("something")
    )

    val resultSerialization = adapter.toJson(objectToSerialize)

    println("resultSerialization: $resultSerialization")

    val jsonToDeserialize = """{
                              "someField": 123,
                              "revision": "some-random-string"
                            }"""

    val resultDeserialization = adapter.fromJson(jsonToDeserialize)

    println("resultDeserialization: $resultDeserialization")
}
```

When I try to run the main function, it fails with the following exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot serialize Kotlin type my.app.Revision. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.
for class my.app.Revision revision
for class my.app.MyDto
	at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:388)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:157)
	at my.app.MyDtoJsonAdapter.<init>(MyDtoJsonAdapter.kt:31)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:577)
	at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:61)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:79)
	at my.app.MyDtoKt.main(MyDto.kt:35)
	at my.app.MyDtoKt.main(MyDto.kt)
```

So I tried first by generating the adapter by uncommenting the line `@JsonClass(generateAdapter = true)` for the `Revision`, but now I get the following exception when trying to deserialize (**serialization works fine**):
```
Exception in thread "main" com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was STRING at path $.revision
	at com.squareup.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:172)
	at my.app.RevisionJsonAdapter.fromJson-vNtr6p0(RevisionJsonAdapter.kt:33)
	at my.app.RevisionJsonAdapter.fromJson(RevisionJsonAdapter.kt:20)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at my.app.MyDtoJsonAdapter.fromJson(MyDtoJsonAdapter.kt:53)
	at my.app.MyDtoJsonAdapter.fromJson(MyDtoJsonAdapter.kt:23)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
	at my.app.MyDtoKt.main(MyDto.kt:51)
	at my.app.MyDtoKt.main(MyDto.kt)
```
The same happens if I try using reflection by uncommenting the line `.addLast(KotlinJsonAdapterFactory())` (and adding the proper dependency to `com.squareup.moshi:moshi-kotlin:1.12.0`)

My question is: 
Is that a bug/feature not implemented, or I am doing something wrong and this is possible to do?

**Comment by JakeWharton** [comment]
Tracked by #1170
