### ISSUE TITLE
When given a Class, look for static ToJson/FromJson methods.

### ISSUE THREAD

**Issue by JakeWharton** [square/moshi#140]
Current behavior:

```
Exception in thread "main" java.lang.IllegalArgumentException: Expected at least one @ToJson or @FromJson method on java.lang.Class
    at com.squareup.moshi.AdapterMethodsFactory.get(AdapterMethodsFactory.java:129)
    at com.squareup.moshi.Moshi$Builder.add(Moshi.java:186)
```

**Comment by WingedToaster** [comment]
```
-keepclassmembers class ** {
    @com.squareup.moshi.FromJson *;
    @com.squareup.moshi.ToJson *;
}
```

from https://github.com/square/moshi/issues/93 solved this for me

**Comment by JakeWharton** [comment]
@WingedToaster that is unrelated to this issue
