### ISSUE TITLE
Doesn't work with Kotlin 1.6

### ISSUE THREAD

**Issue by Goooler** [square/moshi#1426]
```
Caused by: java.lang.IllegalStateException: Could not parse metadata! This should only happen if you're using Kotlin <1.1.
	at com.squareup.moshi.kotlinpoet.metadata.KotlinPoetMetadata.readKotlinClassMetadata(KotlinPoetMetadata.kt:89)
	at com.squareup.moshi.kotlinpoet.metadata.KotlinPoetMetadata.toImmutableKmClass(KotlinPoetMetadata.kt:119)
	at com.squareup.moshi.kotlin.codegen.MoshiCachedClassInspector.toImmutableKmClass(MoshiCachedClassInspector.kt:37)
	at com.squareup.moshi.kotlin.codegen.MetadataKt.targetType(metadata.kt:139)
	at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.adapterGenerator(JsonClassCodegenProcessor.kt:148)
	at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.process(JsonClassCodegenProcessor.kt:114)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:188)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
	... 38 more

```

**Comment by ZacSweers** [comment]
Next release will, please don't duplicate issues and check the issue tracker first

**Comment by G00fY2** [comment]
@ZacSweers maybe you could keep the issue open until the new release is out. This allows people to easier notice this current issue and to subscribe to it, since you don't seem to use GitHub releases (the way I normaly get noticed about library updates). Just an idea. :slightly_smiling_face:

**Comment by Hussienfahmy** [comment]
Any Information about the release date ?
