### ISSUE TITLE
[ANR] com.squareup.moshi.*

### ISSUE THREAD

**Issue by raghav2945** [square/moshi#1476]
We ([Audiomack](https://audiomack.com/)) are getting a lot of ANR from your component "com.squareup.moshi.*." I was unable to reproduce this issue locally, so I couldn't able to provide some test examples in accordance with your expectations. I'm going to share a few Firebase stacks in the hopes that they will help you figure out some specific category of ANR that you may have encountered previously.

### Stack-trace

Moshi.java line 43 (com.squareup.moshi.Moshi.<clinit>)
```
main (runnable): tid=1 systid=23690
       at java.util.ArrayList.<init>(ArrayList.java:164)
       at com.squareup.moshi.Moshi.<clinit>(Moshi.java:43)
       at com.squareup.moshi.Moshi$Builder.build(Moshi.java:246)
       at retrofit2.converter.moshi.MoshiConverterFactory.create(MoshiConverterFactory.java:48)
       at com.audiomack.network.retrofitApi.ApiFavorites$Companion.create(ApiFavorites.kt:55)
       at com.audiomack.network.Api$apiFavorites$2.invoke(Api.kt:75)
       at com.audiomack.network.Api$apiFavorites$2.invoke(Api.kt:75)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.audiomack.network.Api.getApiFavorites(Api.kt:75)
       at com.audiomack.data.api.MusicRepository.<init>(MusicRepository.kt:51)
       at com.audiomack.data.support.ZendeskRepository$Companion.init$default(ZendeskRepository.kt:216)
       at com.audiomack.startup.ZendeskInitializer.create(ZendeskInitializer.kt:8)
       at com.audiomack.startup.ZendeskInitializer.create(ZendeskInitializer.kt:7)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:38)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2429)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2399)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8144)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7680)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7500)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2150)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8587)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

ClassJsonAdapter.java line 98 (com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings)
```
main (runnable): tid=1 systid=18107
#00 pc 0x370e15 libart.so 
#01 pc 0x43f937 libart.so 
#02 pc 0x43b303 libart.so 
#03 pc 0x457ed9 libart.so 
#04 pc 0x44053f libart.so 
#05 pc 0x4ccae5 libart.so 
       at java.lang.reflect.Field.getNameInternal(Native method)
       at java.lang.reflect.Field.getName(Field.java:98)
       at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:98)
       at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:82)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:67)
       at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:52)
       at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:36)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
       at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:99)
       at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:82)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
       at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:89)
       at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:362)
       at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:345)
       at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:124)
       at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:85)
       at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
       at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
       at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
       at com.audiomack.network.retrofitApi.WorldPostService.getPosts(WorldPostService.kt)
       at com.audiomack.network.retrofitApi.WorldPostService$DefaultImpls.getPosts$default(WorldPostService.kt:26)
       at com.audiomack.data.world.WorldRepository.getWorldArticles(WorldRepository.kt:52)
       at com.audiomack.ui.discover.DiscoverViewModel.loadMoreWorldPosts(DiscoverViewModel.kt:439)
       at com.audiomack.ui.discover.DiscoverViewModel.updateData(DiscoverViewModel.kt:374)
       at com.audiomack.ui.discover.DiscoverViewModel.reloadItems(DiscoverViewModel.kt:354)
       at com.audiomack.ui.discover.DiscoverViewModel.setFilterData(DiscoverViewModel.kt:368)
       at com.audiomack.ui.discover.DiscoverFragment.onCreate(DiscoverFragment.kt:109)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentController.execPendingActions(FragmentController.java:451)
       at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:436)
       at com.audiomack.activities.BaseActivity.onResume(BaseActivity.kt:34)
       at com.audiomack.ui.home.HomeActivity.onResume(HomeActivity.kt:259)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
       at android.app.Activity.performResume(Activity.java:8135)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4476)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4518)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2105)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7700)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

CollectionJsonAdapter.java line 30 (com.squareup.moshi.CollectionJsonAdapter.<clinit>)

```
main (runnable): tid=1 systid=13263
       at com.squareup.moshi.CollectionJsonAdapter.<clinit>(CollectionJsonAdapter.java:30)
       at com.squareup.moshi.Moshi.<clinit>(Moshi.java:47)
       at com.squareup.moshi.Moshi$Builder.build(Moshi.java:246)
       at retrofit2.converter.moshi.MoshiConverterFactory.create(MoshiConverterFactory.java:48)
       at com.audiomack.network.retrofitApi.ApiFavorites$Companion.create(ApiFavorites.kt:55)
       at com.audiomack.network.Api$apiFavorites$2.invoke(Api.kt:75)
       at com.audiomack.network.Api$apiFavorites$2.invoke(Api.kt:75)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.audiomack.network.Api.getApiFavorites(Api.kt:75)
       at com.audiomack.data.api.MusicRepository.<init>(MusicRepository.kt:51)
       at com.audiomack.data.support.ZendeskRepository$Companion.init$default(ZendeskRepository.kt:216)
       at com.audiomack.startup.ZendeskInitializer.create(ZendeskInitializer.kt:8)
       at com.audiomack.startup.ZendeskInitializer.create(ZendeskInitializer.kt:7)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:38)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2429)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2399)
       at android.app.ActivityThread.installProvider(ActivityThread.java:8144)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7680)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7500)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2150)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8587)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

AdapterMethodsFactory.java line 242 (com.squareup.moshi.AdapterMethodsFactory.fromAdapter)
```
main (runnable): tid=1 systid=11749
       at com.squareup.moshi.AdapterMethodsFactory.fromAdapter(AdapterMethodsFactory.java:242)
       at com.squareup.moshi.AdapterMethodsFactory.get(AdapterMethodsFactory.java:123)
       at com.squareup.moshi.Moshi$Builder.add(Moshi.java:237)
       at com.adswizz.obfuscated.i0.b.<clinit>()
       at com.adswizz.obfuscated.b0.a.<clinit>()
       at com.adswizz.sdk.AdswizzSDK.initialize()
       at com.adswizz.sdk.AdswizzSDK.initialize$default()
       at com.audiomack.data.ads.AdProvidersHelper.enableAudioAds(AdProvidersHelper.kt:470)
       at com.audiomack.data.ads.AdProvidersHelper.turnOn(AdProvidersHelper.kt:464)
       at com.audiomack.data.ads.AdProvidersHelper.toggle(AdProvidersHelper.kt:490)
       at com.audiomack.data.ads.AdProvidersHelper.observePremiumChanges$lambda-84(AdProvidersHelper.kt:1442)
       at com.audiomack.data.ads.AdProvidersHelper.lambda$x6s11ci3SHkBiGQTTm_UdqcKfN4(AdProvidersHelper.kt)
       at com.audiomack.data.ads.-$$Lambda$AdProvidersHelper$x6s11ci3SHkBiGQTTm_UdqcKfN4.accept(lambda)
       at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
       at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged$DistinctUntilChangedObserver.onNext(ObservableDistinctUntilChanged.java:85)
       at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
       at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:569)
       at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:530)
       at io.reactivex.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:239)
       at io.reactivex.Observable.subscribe(Observable.java:12284)
       at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged.subscribeActual(ObservableDistinctUntilChanged.java:35)
       at io.reactivex.Observable.subscribe(Observable.java:12284)
       at io.reactivex.Observable.subscribe(Observable.java:12270)
       at io.reactivex.Observable.subscribe(Observable.java:12198)
       at com.audiomack.data.ads.AdProvidersHelper.observePremiumChanges(AdProvidersHelper.kt:1442)
       at com.audiomack.data.ads.AdProvidersHelper.create(AdProvidersHelper.kt:500)
       at com.audiomack.ui.home.HomeViewModel.onCreate(HomeViewModel.kt:589)
       at com.audiomack.ui.home.HomeActivity.onCreate(HomeActivity.kt:239)
       at android.app.Activity.performCreate(Activity.java:8198)
       at android.app.Activity.performCreate(Activity.java:8182)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3773)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3976)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2315)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8550)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by ZacSweers** [comment]
This isn't really actionable. Feel free to revisit with a minimally reproducible sample.
