### ISSUE TITLE
Using a custom type adapter: Cannot serialize abstract class on API 17

### ISSUE THREAD

**Issue by aphexcx** [square/moshi#150]
This could be related to #148. 

I'm using the moshi converter with retrofit2 to convert my json responses. Some of these fields are missing, so I defined some of the fields as [FunctionalJava Option](http://www.functionaljava.org/examples-java8.html#optionMap) types.

```java
public class Profile {
    private String first_name;
    private String last_name;
    private String real_name;
    private Option<String> phone = Option.none();
    private Option<String> email = Option.none();
    private Option<String> title = Option.none();
    
    ...

    public Profile() {
    }
}
```

Moshi needs to know how to deal with those, of course, so specifiying the following adapter for fj.data.Option types worked great on my API23 device:

```java
public class OptionAdapter {
    @ToJson
    String toJson(@NonNull Option<String> stringOption) {
        return stringOption.orSome("");
    }

    @FromJson
    Option<String> fromJson(@Nullable String string) {
        return Option.fromNull(string);
    }
}

```

But on my API 17 emulator, I'm getting: 

```
Caused by: java.lang.IllegalArgumentException: Cannot serialize abstract class fj.data.Option
                                                                              at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:58)
                                                                              at com.squareup.moshi.Moshi.adapter(Moshi.java:92)
                                                                              at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:80)
                                                                              at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:64)
                                                                              at com.squareup.moshi.Moshi.adapter(Moshi.java:92)
                                                                              at com.squareup.moshi.Moshi.adapter(Moshi.java:57)
                                                                              at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:51)
                                                                              at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:35)
                                                                              at com.squareup.moshi.Moshi.adapter(Moshi.java:92)
                                                                              at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:80)
                                                                              at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:64)
                                                                              at com.squareup.moshi.Moshi.adapter(Moshi.java:92)
                                                                              at com.squareup.moshi.Moshi.adapter(Moshi.java:57)
                                                                              at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:63)
                                                                              at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:325)
                                                                              at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:308)
                                                                              at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:651)
                                                                              	... 20 more
```

I'm at a loss as to why this works on API23 and not on API17. Is this a bug in the library? 

My project's full code can be found at https://github.com/aphexcx/slack-team-viewer and the full exception is below.
```
04-12 16:13:55.895 10673-10673/cx.aphex.slackteamviewer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{cx.aphex.slackteamviewer/cx.aphex.slackteamviewer.activities.MainActivity}: java.lang.IllegalArgumentException: Unable to create converter for class cx.aphex.slackteamviewer.models.UsersList
                                                                              for method SlackApiEndpointInterface.getUsersList
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                                              at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                              at android.os.Looper.loop(Looper.java:137)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:511)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                              at dalvik.system.NativeStart.main(Native Method)
                                                                           Caused by: java.lang.IllegalArgumentException: Unable to create converter for class cx.aphex.slackteamviewer.models.UsersList
                                                                              for method SlackApiEndpointInterface.getUsersList
                                                                              at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:667)
                                                                              at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:653)
                                                                              at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:166)
                                                                              at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
                                                                              at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
                                                                              at $Proxy3.getUsersList(Native Method)
                                                                              at cx.aphex.slackteamviewer.activities.MainActivity.loadUsersListFromApi(MainActivity.java:111)
                                                                              at cx.aphex.slackteamviewer.activities.MainActivity.onCreate(MainActivity.java:60)
                                                                              at android.app.Activity.performCreate(Activity.java:5104)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                                              	... 11 more
                                                                           Caused by: java.lang.IllegalArgumentException: Cannot serialize abstract class fj.data.Option
                                                                              at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:58)
                                                                              at com.squareup.moshi.Moshi.adapter(Moshi.java:92)
                                                                              at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:80)
                                                                              at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:64)
                                                                              at com.squareup.moshi.Moshi.adapter(Moshi.java:92)
                                                                              at com.squareup.moshi.Moshi.adapter(Moshi.java:57)
                                                                              at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:51)
                                                                              at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:35)
                                                                              at com.squareup.moshi.Moshi.adapter(Moshi.java:92)
                                                                              at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:80)
                                                                              at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:64)
                                                                              at com.squareup.moshi.Moshi.adapter(Moshi.java:92)
                                                                              at com.squareup.moshi.Moshi.adapter(Moshi.java:57)
                                                                              at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:63)
                                                                              at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:325)
                                                                              at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:308)
                                                                              at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:651)
                                                                              	... 20 more
```

**Comment by swankjesse** [comment]
Please provide an executable test case. Here’s several examples to get you started:
https://github.com/square/moshi/blob/master/moshi/src/test/java/com/squareup/moshi/MoshiTest.java

**Comment by anki1427** [comment]
you got the solution for it
