### ISSUE TITLE
Cannot combine @Serializable and @JsonClass annotations

### ISSUE THREAD

**Issue by pettermahlen** [square/moshi#1515]
The following code:
```
@kotlinx.serialization.Serializable
@JsonClass(generateAdapter = true)
public class Foo<T>
```
generates an exception during annotation processing (root cause): 
```
Caused by: java.lang.IllegalStateException: No type argument found for 0!
	at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt$toTypeParameterResolver$typeParamResolver$1.invoke(KmTypes.kt:202)
	at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt$toTypeParameterResolver$typeParamResolver$1.invoke(KmTypes.kt)
	at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt$toTypeParameterResolver$resolver$1.get(KmTypes.kt:208)
	at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:84)
	at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:63)
	at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:81)
	at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:63)
	at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:81)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs$toTypeSpec$12.invoke(KotlinPoetMetadataSpecs.kt:356)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs$toTypeSpec$12.invoke(KotlinPoetMetadataSpecs.kt)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at com.squareup.kotlinpoet.TypeSpec$Builder.addSuperinterfaces(TypeSpec.kt:847)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:353)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:475)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:182)
	at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec$default(KotlinPoetMetadataSpecs.kt:180)
	at com.squareup.moshi.kotlin.codegen.MoshiCachedClassInspector.toTypeSpec(MoshiCachedClassInspector.kt:43)
	at com.squareup.moshi.kotlin.codegen.MetadataKt.targetType(metadata.kt:208)
	at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.adapterGenerator(JsonClassCodegenProcessor.kt:148)
	at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.process(JsonClassCodegenProcessor.kt:114)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt:90)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:166)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
	... 63 more
```

Removing the type parameter works fine, as well as removing the `@Serializable` annotation, as well as replacing the annotation with a custom, no-op one. So it seems to be some kind of conflict between the two serializers.

Not sure that this is a real or fixable problem, but I ran into it while porting effort from kotlinx.serialization to Moshi so I figured I should report it at least.

**Comment by ZacSweers** [comment]
Does it happen with KSP code gen?

**Comment by pettermahlen** [comment]
I haven't tried that, and unfortunately, I don't have a lot of spare cycles to test that currently. :(

**Comment by virtenv** [comment]
The same issue, when using the OpenApi Generator with default petstore.yaml and the following config.json
{
  "apiSuffix" : "API",
  "artifactId" : "kotlin-client",
  "artifactVersion" : "1.0.0",
  "collectionType" : "list",
  "collectionType" : "dateLibrary",
  "enumPropertyNaming" : "camelCase",
  "groupId" : "org.openapitools",
  "library" : "multiplatform",
  "modelMutable" : "false",
  "moshiCodeGen" : "false",
  "packageName" : "org.openapitools.client",
  "requestDateConverter" : "toJson",
  "serializationLibrary" : "moshi",
  "sourceFolder" : "src/main/kotlin",
  "supportAndroidApiLevel25AndBelow" : "false",
  "useCoroutines" : "false",
  "useRxJava3" : "false"
}

$./gradlew assemble

ends with:

> Task :compileKotlinJs FAILED
e: out/src/commonMain/kotlin/org/openapitools/client/models/ApiResponse.kt: (35, 15): Unresolved reference: JsonClass
e: ./src/commonMain/kotlin/org/openapitools/client/models/Category.kt: (34, 15): Unresolved reference: JsonClass
e: ./src/commonMain/kotlin/org/openapitools/client/models/Order.kt: (38, 15): Unresolved reference: JsonClass
e: ./src/commonMain/kotlin/org/openapitools/client/models/Pet.kt: (40, 15): Unresolved reference: JsonClass
e: ./src/commonMain/kotlin/org/openapitools/client/models/Tag.kt: (34, 15): Unresolved reference: JsonClass
e: ./src/commonMain/kotlin/org/openapitools/client/models/User.kt: (40, 15): Unresolved reference: JsonClass

while

./src/commonMain/kotlin/org/openapitools/client/models/ApiResponse.kt:@Serializable@JsonClass(generateAdapter = true)
./src/commonMain/kotlin/org/openapitools/client/models/Category.kt:@Serializable@JsonClass(generateAdapter = true)
./src/commonMain/kotlin/org/openapitools/client/models/Order.kt:@Serializable@JsonClass(generateAdapter = true)
./src/commonMain/kotlin/org/openapitools/client/models/Pet.kt:@Serializable@JsonClass(generateAdapter = true)
./src/commonMain/kotlin/org/openapitools/client/models/Tag.kt:@Serializable@JsonClass(generateAdapter = true)
./src/commonMain/kotlin/org/openapitools/client/models/User.kt:@Serializable@JsonClass(generateAdapter = true)

**Comment by ZacSweers** [comment]
@virtenv thats not nearly enough context to help and I'm not sure this is even related to the original post

**Comment by virtenv** [comment]
I'am sure it's relatad to the original post because, when I replace
"serializationLibrary" : "moshi",
by
"serializationLibrary" : "gson",
I can build the project.

**Comment by ZacSweers** [comment]
Again, that's really vague. Please make a minimally reproducible sample project and link it here

**Comment by virtenv** [comment]
Here you are.
https://github.com/virtenv/sample.git
