### ISSUE TITLE
NoSuchElementException thrown in KSP processing

### ISSUE THREAD

**Issue by KORuL** [square/moshi#1516]
[ksp] java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.squareup.moshi.kotlin.codegen.ksp.ShadedUtilKt.createInvocationHandler$lambda-4(shadedUtil.kt:209)
	at com.sun.proxy.$Proxy24.ignore(Unknown Source)
	at com.squareup.moshi.kotlin.codegen.ksp.TargetTypesKt.jsonIgnore(TargetTypes.kt:217)
	at com.squareup.moshi.kotlin.codegen.ksp.TargetTypesKt.declaredProperties(TargetTypes.kt:247)
	at com.squareup.moshi.kotlin.codegen.ksp.TargetTypesKt.targetType(TargetTypes.kt:124)
	at com.squareup.moshi.kotlin.codegen.ksp.JsonClassSymbolProcessor.adapterGenerator(JsonClassSymbolProcessorProvider.kt:118)
	at com.squareup.moshi.kotlin.codegen.ksp.JsonClassSymbolProcessor.process(JsonClassSymbolProcessorProvider.kt:91)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:195)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:193)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:287)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:193)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:120)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:262)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1618)

**Comment by ZacSweers** [comment]
Can you provide a minimally reproducing sample project?

**Comment by KORuL** [comment]
in root gradle
```
buildscript {
   ...

    dependencies {
        ...   
        classpath ("com.android.tools.build:gradle:7.1.0")
    }
    ...
}
```

in module gradle
```
plugins {
    ....
    id("com.google.devtools.ksp") version "1.6.0-1.0.1"
}

dependencies {
...
ksp("com.squareup.moshi:moshi-kotlin-codegen:1.13.0")
}

```

**Comment by ZacSweers** [comment]
That is not enough

**Comment by KORuL** [comment]
`interface Tile`

**Comment by KORuL** [comment]
```
e: [ksp] java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.squareup.moshi.kotlin.codegen.ksp.ShadedUtilKt.createInvocationHandler$lambda-4(shadedUtil.kt:209)
	at com.sun.proxy.$Proxy187.ignore(Unknown Source)
	at com.squareup.moshi.kotlin.codegen.ksp.TargetTypesKt.jsonIgnore(TargetTypes.kt:217)
	at com.squareup.moshi.kotlin.codegen.ksp.TargetTypesKt.declaredProperties(TargetTypes.kt:247)
	at com.squareup.moshi.kotlin.codegen.ksp.TargetTypesKt.targetType(TargetTypes.kt:124)
	at com.squareup.moshi.kotlin.codegen.ksp.JsonClassSymbolProcessor.adapterGenerator(JsonClassSymbolProcessorProvider.kt:118)
	at com.squareup.moshi.kotlin.codegen.ksp.JsonClassSymbolProcessor.process(JsonClassSymbolProcessorProvider.kt:91)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:195)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:193)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:287)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:193)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:120)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:262)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1618)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by KORuL** [comment]
![image](https://user-images.githubusercontent.com/19871487/152355706-1684b475-4590-4d41-b19d-3d425d424446.png)

Where is @Json(ignore = true)

**Comment by ArcherEmiya05** [comment]
> I found error
> 
> in gradle need
> 
> ```
>     ksp("com.squareup.moshi:moshi-kotlin-codegen:1.13.0")
>     implementation("com.squareup.moshi:moshi-kotlin:1.13.0")
> ```
> 
> was only `ksp("com.squareup.moshi:moshi-kotlin-codegen:1.13.0")`
> 
> and gradle gave moshi from retrofit old vers

I don't think this is the answer, are you saying you have both?
```
 ksp("com.squareup.moshi:moshi-kotlin-codegen:1.13.0")
    implementation("com.squareup.moshi:moshi-kotlin:1.13.0")
```

Because that is unnecessary, I am having same issue with the latest AGP and Android Studio Dolphin

**Comment by OmaRaad** [comment]
To me, it looks like when you add the `moshi-kotlin` dependency you're actually using reflection not code-gen.

As mentioned in the [Readme here](https://github.com/square/moshi#:~:text=Note%20that%20the%20reflection%20adapter%20transitively%20depends%20on%20the%20kotlin%2Dreflect%20library%20which%20is%20a%202.5%20MiB%20.jar%20file.), `moshi-kotlin` transitively includes `kotlin-reflect`...


Also, in the code-gen section [here](https://github.com/square/moshi#:~:text=Kotlin%20codegen%20has%20no%20additional%20runtime%20dependency.%20You%E2%80%99ll%20need%20to%20enable%20kapt%20or%20KSP%20and%20then%20add%20the%20following%20to%20your%20build%20to%20enable%20the%20annotation%20processor%3A), it's mentioned that code-gen only needs the processor dependency and no runtime dependency. But it's only working when you add the `moshi-kotlin` which is a runtime dependency

**Comment by vitusortner** [comment]
You can depend on the main artifact `com.squareup.moshi:moshi` instead of the Kotlin reflection one as the runtime dependency.
