### ISSUE TITLE
ksp 1.0.3 breaks build

### ISSUE THREAD

**Issue by giangpham96** [square/moshi#1522]
After I update my ksp from `1.6.10-1.0.2` to `1.6.10-1.0.3`, the build breaks. I am not sure if this is a ksp bug or moshi bug. The log doesn't say much
```
e: [ksp] java.lang.IllegalStateException: Required value was null.

	at shadow.com.squareup.kotlinpoet.ksp.UtilsKt.toClassNameInternal(utils.kt:63)
	at shadow.com.squareup.kotlinpoet.ksp.KsClassDeclarationsKt.toClassName(ksClassDeclarations.kt:24)
	at shadow.com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(ksTypes.kt:66)
	at shadow.com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(ksTypes.kt:57)
> Task :net_entities:kspDevelopmentDebugKotlin
	at com.squareup.moshi.kotlin.codegen.ksp.TargetTypesKt.toPropertySpec(TargetTypes.kt:261)
	at com.squareup.moshi.kotlin.codegen.ksp.TargetTypesKt.declaredProperties(TargetTypes.kt:236)
	at com.squareup.moshi.kotlin.codegen.ksp.TargetTypesKt.targetType(TargetTypes.kt:124)
	at com.squareup.moshi.kotlin.codegen.ksp.JsonClassSymbolProcessor.adapterGenerator(JsonClassSymbolProcessorProvider.kt:118)
	at com.squareup.moshi.kotlin.codegen.ksp.JsonClassSymbolProcessor.process(JsonClassSymbolProcessorProvider.kt:91)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:223)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:221)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:312)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:221)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:120)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:96)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:262)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:253)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:100)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:58)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1618)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:[1128](https://github.com/creditornot/wolt-android/runs/5270935241?check_suite_focus=true#step:8:1128))
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ZacSweers** [comment]
Unless you can provide a reproducible sample, this isn't actionable

**Comment by cj3g10** [comment]
This seems to be a ksp 1.0.3 bug. I encountered the same issue, but when I updated to 1.0.4, this issue is gone.

**Comment by giangpham96** [comment]
I confirm that this is fixed in ksp 1.0.4

**Comment by trevjonez** [comment]
I am getting this today with ksp 1.6.10-1.0.4 and 1.13.

I suspect it has to do with having a generic sealed interface. I'll see if I can get a PR up with a reproduction test shortly.

My case is hardly any more complex than this
```kotlin
sealed interface Foo<T: Any> {
  val value: T
}

@JsonClass(generateAdapter = true)
data class Bar(
  override val value: Double,
) : Foo<Double>

@JsonClass(generateAdapter = true)
data class Baz(
  override val value: Long,
) : Foo<Long>
```

stack for SEO
```
[ksp] java.lang.IllegalStateException: Required value was null.
	at shadow.com.squareup.kotlinpoet.ksp.UtilsKt.toClassNameInternal(utils.kt:63)
	at shadow.com.squareup.kotlinpoet.ksp.KsClassDeclarationsKt.toClassName(ksClassDeclarations.kt:24)
	at shadow.com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(ksTypes.kt:66)
	at shadow.com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(ksTypes.kt:150)
	at shadow.com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(ksTypes.kt:129)
	at shadow.com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(ksTypes.kt:66)
	at shadow.com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(ksTypes.kt:150)
	at com.squareup.moshi.kotlin.codegen.ksp.TargetTypesKt.primaryConstructor(TargetTypes.kt:182)
	at com.squareup.moshi.kotlin.codegen.ksp.TargetTypesKt.targetType(TargetTypes.kt:94)
	at com.squareup.moshi.kotlin.codegen.ksp.JsonClassSymbolProcessor.adapterGenerator(JsonClassSymbolProcessorProvider.kt:118)
	at com.squareup.moshi.kotlin.codegen.ksp.JsonClassSymbolProcessor.process(JsonClassSymbolProcessorProvider.kt:91)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:223)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:221)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:316)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:221)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:120)
```

**Comment by ZacSweers** [comment]
Does that example snippet repro in our repo if you add it to the integration tests?

**Comment by trevjonez** [comment]
Forking now. i'll let you know shortly

**Comment by trevjonez** [comment]
Ok found the issue, it is more so an issue of unclear error messaging when there is compile errors in code that moshi ksp codegen is trying to process. PR shortly so we have a place to discuss in context
