### ISSUE TITLE
Cannot use with package-private records

### ISSUE THREAD

**Issue by JakeWharton** [square/moshi#1528]
Creating the serialization-side of the adapter throws. Also not great that `IllegalAccessError` is wrapped in `AssertionError`, should probably be `IllegalStateException` or `IllegalArgumentException`.

```java
record Stuff(long id) {}
var moshi = new Moshi.Builder().build();
var adapter = moshi.getAdapter(Stuff.class);
```
```
Caused by: java.lang.IllegalAccessException: class is not public: Stuff.id[Ljava.lang.Object;@401e7803/invokeSpecial, from class com.squareup.moshi.RecordJsonAdapter$1 (unnamed module @8874c42)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:955)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:3880)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:3820)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:3965)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:3958)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflect(MethodHandles.java:3348)
	at com.squareup.moshi.RecordJsonAdapter$1.createComponentBinding(RecordJsonAdapter.java:106)
	... 18 more
```
It especially sucks because I'm only deserializing and not serializing.

**Comment by ZacSweers** [comment]
Are we just missing a `isAccessible = true` check or does this require opens/exports jvm args and we should just use a better exception?

**Comment by tomridder** [comment]
![image](https://user-images.githubusercontent.com/13205117/227765775-f38ce553-b900-43c4-88c5-7cb1619c4e46.png)
this exception happens in line 168 when execute `lookup.unreflect()`

**Comment by FeldrinH** [comment]
Is there any hope of this getting fixed? Having to convert records to classes just so I can serialize them with Moshi is fairly annoying.

**Comment by migmacdev** [comment]
Hi, I posted a fix suggestion in this one:
https://github.com/square/moshi/pull/2084
