### ISSUE TITLE
Adaptor not being used

### ISSUE THREAD

**Issue by KrystilizeNevaDies** [square/moshi#1548]
I have here a utility adaptor that I wrote:
https://pastes.dev/nqlGnOTA6z

And here is how I am using it:
```java
    public static void main(String[] args) throws IOException {
        Moshi moshi = new Moshi.Builder()
                .add(ArrayOrSingle.class, ArrayOrSingle.ADAPTOR)
                .build();
        moshi.adapter(Example.class).fromJson("""
                    {
                        "multiString": "Example"
                    }
            """);
    }
```

It fails every time, It seems that the impl is hidden through some runtime class loading, so I don't know exactly what the issue is, but here is the stacktrace:
```
Exception in thread "main" com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was STRING at path $.multiString
	at com.squareup.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:172)
	at com.squareup.moshi.RecordJsonAdapter.fromJson(RecordJsonAdapter.java:142)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.RecordJsonAdapter.fromJson(RecordJsonAdapter.java:150)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
	at net.minestom.vanilla.generation.data.WorldgenDataAnalysis.main(WorldgenDataAnalysis.java:29)
```

It seems that the adaptor that I registered is never being used, probably because the moshi object's adaptors are never considered?
Any help would be appreciated, thanks.

**Comment by KrystilizeNevaDies** [comment]
I should also note that I confirmed the adaptor is not being selected though debugging.

**Comment by KrystilizeNevaDies** [comment]
Sorry, I forgot to include that.

Example is a record:
```
public record Example(ArrayOrSingle<String> multiString) { }
```
