### ISSUE TITLE
Allow keys not implementing Comparable in builtin Map adapter

### ISSUE THREAD

**Issue by Tyilo** [square/moshi#1551]
I have a type that I don't want to implement `Comparable` for, but I would like to use as a key in a map which will be parsed from json.

I think it would be nice if the builtin Map adapter supported this, by using a normal `HashMap` if the key type doesn't implement `Comparable` instead of just failing.

<hr>

Example code:

```java
import java.util.*;
import com.squareup.moshi.Moshi;
import com.squareup.moshi.FromJson;
import com.squareup.moshi.JsonAdapter;

public class TestNoncomparableKey {
  public static void main(String[] args) throws Exception {
    Moshi moshi = new Moshi.Builder()
      .add(new NoncomparableKeyAdapter())
      .build();

    JsonAdapter<NoncomparableKeyMap> adapter = moshi.adapter(NoncomparableKeyMap.class);
    NoncomparableKeyMap map = adapter.fromJson("{\"map\": {\"foo\": \"bar\"}}");

    System.out.println(map.map);
  }

  public static class NoncomparableKey {
    private String str;

    public NoncomparableKey() {}

    public NoncomparableKey(String str) {
      this.str = str;
    }

    @Override
    public boolean equals(Object o) {
      if (!(o instanceof NoncomparableKey)) {
        return false;
      }
      NoncomparableKey o2 = (NoncomparableKey)o;
      return Objects.equals(str, o2.str);
    }

    @Override
    public int hashCode() {
      return Objects.hashCode(str);
    }
  }

  public static class NoncomparableKeyAdapter {
    @FromJson
    NoncomparableKey fromJson(String str) {
      return new NoncomparableKey(str);
    }
  }

  public static class NoncomparableKeyMap {
    public Map<NoncomparableKey, String> map = new HashMap<>();
    
    public NoncomparableKeyMap() {}
  }
}
```

Output:
```
Exception in thread "main" java.lang.ClassCastException: TestNoncomparableKey$NoncomparableKey is not Comparable
	at com.squareup.moshi.LinkedHashTreeMap.find(LinkedHashTreeMap.java:177)
	at com.squareup.moshi.LinkedHashTreeMap.put(LinkedHashTreeMap.java:97)
	at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:74)
	at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:30)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:245)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:205)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
	at TestNoncomparableKey.main(TestNoncomparableKey.java:13)
```

**Comment by ZacSweers** [comment]
JSON doesn't allow non-string keys. You should write your own map adapter if you want to further customize the key type

**Comment by Tyilo** [comment]
> JSON doesn't allow non-string keys.

JSON doesn't support `BlackjackHand`, `Card` or `Suit` types either, but they are still supported by moshi.
If I can convert a key from and to `String`, I don't see the problem in supporting it (as you already do if it implements `Comparable` even if it is not a `String`.

If you don't want to add support, could you then instead:
- Restrict the type of the key in the map adapter to only support `String` keys if that is what you want?
- Alternatively enforce that the type of the key is `K extends Comparable<K>`?

**Comment by JakeWharton** [comment]
Note this restriction comes from defending against an attack on servers where carefully chosen string keys will degrade a normal HashMap into a linked list.

It's inherited from Gson. Here's someone else with the same problem with Gson: https://stackoverflow.com/q/65978273/132047

It would be nice if it was trivial to disable the use of this internal map type as it's generally useless on clients which speak to trusted servers.

**Comment by JakeWharton** [comment]
Can you describe your real-world usage a bit? What's your key type look like? We're also wondering whether you can do this as a post-processing step where you parse into a `String`-keyed map and then do a key conversion in the type constructor or map accessor.
