### ISSUE TITLE
After enable R8 full mode getting ParameterizedType error

### ISSUE THREAD

**Issue by NG-Gaurav** [square/moshi#1556]
Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection, allowed)
16:09:29.013  W  java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
16:09:29.014  W  	at retrofit2.HttpServiceMethod.parseAnnotations(SourceFile:46)
16:09:29.014  W  	at retrofit2.ServiceMethod.parseAnnotations(SourceFile:39)
16:09:29.014  W  	at retrofit2.Retrofit.loadServiceMethod(SourceFile:202)
16:09:29.014  W  	at retrofit2.Retrofit$1.invoke(SourceFile:160)
16:09:29.014  W  	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
16:09:29.014  W  	at $Proxy6.generateAnonymousAuthTokenAsyn(Unknown Source)

**Comment by dahis39** [comment]
Hi @NG-Gaurav, I'm getting this exact error log for my app. I upgraded retrofit, moshi and others to latest but still problem persisted. Have you solved yours and with what methods please?
