### ISSUE TITLE
Nesting problem 

### ISSUE THREAD

**Issue by maximlozhechnikov** [square/moshi#1589]
I've ran into a problem with Json adapter:
Here is my stacktrace:
`null java.lang.IllegalStateException: Nesting problem.
	at com.squareup.moshi.JsonUtf8Writer.name(JsonUtf8Writer.java:169)
	at com.omega.rosavtodor.data.sources.remote.body.AnalyticPanelBodyJsonAdapter.toJson(AnalyticPanelBodyJsonAdapter.kt:111)
	at com.omega.rosavtodor.data.sources.remote.body.AnalyticPanelBodyJsonAdapter.toJson(AnalyticPanelBodyJsonAdapter.kt:25)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
	at com.squareup.moshi.CollectionJsonAdapter.toJson(CollectionJsonAdapter.java:91)
	at com.squareup.moshi.CollectionJsonAdapter$2.toJson(CollectionJsonAdapter.java:55)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
	at com.omega.rosavtodor.data.sources.remote.body.WorkspaceBodyJsonAdapter.toJson(WorkspaceBodyJsonAdapter.kt:88)
	at com.omega.rosavtodor.data.sources.remote.body.WorkspaceBodyJsonAdapter.toJson(WorkspaceBodyJsonAdapter.kt:24)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
	at com.squareup.moshi.CollectionJsonAdapter.toJson(CollectionJsonAdapter.java:91)
	at com.squareup.moshi.CollectionJsonAdapter$2.toJson(CollectionJsonAdapter.java:55)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
	at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:82)`

Here is my serializing class:
`@JsonClass(generateAdapter = true)
data class AnalyticPanelBody(
    @Json(name = "analytics_request")
    override val analyticsRequest: AnalyticsRequestBody,
    @Json(name = "supported_chart_types")
    override val supportedChartTypes: List<ChartType>,
    @Json(name = "selected_chart_type")
    override val selectedChartType: ChartType,
    @Json(name = "unit")
    override val unit: Text,
    @Json(name = "report")
    override val report: AnalyticsReportBody?,
    @Json(name = "indicator_type")
    override val indicatorType: IndicatorType,
    @Json(name = "panel_name")
    override val name: Text
)`

Part of moshi code which causes problem:
` @Override
  public JsonWriter name(String name) throws IOException {
    if (name == null) {
      throw new NullPointerException("name == null");
    }
    if (stackSize == 0) {
      throw new IllegalStateException("JsonWriter is closed.");
    }
    int context = peekScope();
    if ((context != EMPTY_OBJECT && context != NONEMPTY_OBJECT)
        || deferredName != null
        || promoteValueToName) {
      throw new IllegalStateException("Nesting problem.");
    }
    deferredName = name;
    pathNames[stackSize - 1] = name;
    return this;
  }`

Here debugged part of your code (stopped at line which causes error). It shows that probles that deffered name is not null
![image](https://user-images.githubusercontent.com/98010383/202753008-4c74a5f6-efd2-44d7-a053-4939c7b7359f.png)

ChartType is enum with custom adapter registered as nonNull. it's adapter:
`class ChartTypeJsonAdapter: JsonAdapter<ChartType>() {

    private companion object {
        val keysMap = mapOf(
            "pie" to ChartType.PIE,
            "bar" to ChartType.BAR,
            "groupedBar" to ChartType.GROUPED,
            "ruled" to ChartType.RULED,
            "line" to ChartType.LINE,
        )
    }

    override fun fromJson(reader: JsonReader): ChartType? = keysMap[reader.nextString()]

    override fun toJson(writer: JsonWriter, value: ChartType?) {
         keysMap.filterValues { it == value }.keys.firstOrNull()
    }

}`

Add all code as images to better readability:
Custom adapter:
![image](https://user-images.githubusercontent.com/98010383/202754115-6c380d74-a1de-43c4-9351-b269fe2cc240.png)
Code that throws error
![image](https://user-images.githubusercontent.com/98010383/202754167-deee30a2-22a0-4f99-ac6b-efe9aaa27f9b.png)
Serializing class
![image](https://user-images.githubusercontent.com/98010383/202754305-747050ad-24c3-4d3c-ad24-0c80246c53f9.png)
Stacktrace:
![image](https://user-images.githubusercontent.com/98010383/202754452-cd26b8db-3945-4543-b030-bcdacc8834ec.png)

**Comment by maximlozhechnikov** [comment]
sorry? that's my mistake. If ite helps someone, this kind of exception happens if forgot to use writer.value() in your adapter
