### ISSUE TITLE
Oout of Memory crash on JsonAdapter when parsing very large json array

### ISSUE THREAD

**Issue by hannah-smudge** [square/moshi#1592]
Hi! I would like to request if there is a solution for an out of memory issue when parsing a very large json array. 
This is the part where it crashes:
` java.lang.OutOfMemoryError: Failed to allocate a 48 byte allocation with 2431568 free bytes and 2374KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
        at com.squareup.moshi.LinkedHashTreeMap.find(LinkedHashTreeMap.java:179)
        at com.squareup.moshi.LinkedHashTreeMap.put(LinkedHashTreeMap.java:97)
        at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:74)
        at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:30)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.StandardJsonAdapters$ObjectJsonAdapter.fromJson(StandardJsonAdapters.java:346)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.Moshi$Lookup.fromJson(Moshi.java:409)
        at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
        at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.StandardJsonAdapters$ObjectJsonAdapter.fromJson(StandardJsonAdapters.java:343)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.Moshi$Lookup.fromJson(Moshi.java:409)
        at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:73)
        at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:30)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.StandardJsonAdapters$ObjectJsonAdapter.fromJson(StandardJsonAdapters.java:346)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
        at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:73)
        at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:30)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)`
        
Appreciate your help. Thanks! Currently using the lastest moshi version 1.14.0

**Comment by ZacSweers** [comment]
This isn't actionable at all with the above details. Feel free to ask in the discussions section and with more details

**Comment by GuangNian10000** [comment]
How did you solve it?
