### ISSUE TITLE
Reference cycles fail badly

### ISSUE THREAD

**Issue by swankjesse** [square/moshi#189]
```
java.lang.ArrayIndexOutOfBoundsException: 32
	at com.squareup.moshi.BufferedSinkJsonWriter.open(BufferedSinkJsonWriter.java:146)
	at com.squareup.moshi.BufferedSinkJsonWriter.beginObject(BufferedSinkJsonWriter.java:132)
	at com.squareup.moshi.ClassJsonAdapter.toJson(ClassJsonAdapter.java:170)
	at com.squareup.moshi.JsonAdapter$1.toJson(JsonAdapter.java:75)
	at com.squareup.moshi.StandardJsonAdapters$ObjectJsonAdapter.toJson(StandardJsonAdapters.java:322)
	at com.squareup.moshi.JsonAdapter$1.toJson(JsonAdapter.java:75)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.write(ClassJsonAdapter.java:204)
	at com.squareup.moshi.ClassJsonAdapter.toJson(ClassJsonAdapter.java:173)
	at com.squareup.moshi.JsonAdapter$1.toJson(JsonAdapter.java:75)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.write(ClassJsonAdapter.java:204)
	at com.squareup.moshi.ClassJsonAdapter.toJson(ClassJsonAdapter.java:173)
```

**Comment by JakeLoo** [comment]
Why are the pathNames and pathIndices have the fixed size of 32?
