### ISSUE TITLE
JsonDataException at $[0]

### ISSUE THREAD

**Issue by janswist** [square/moshi#194]
I have this strange error cause by String json = jsonContactAdapter.toJson(listContacts);:
`com.squareup.moshi.JsonDataException: java.lang.NullPointerException at $[0]
                                                                 at com.squareup.moshi.AdapterMethodsFactory$1.toJson(AdapterMethodsFactory.java:68)
                                                                 at com.squareup.moshi.CollectionJsonAdapter.toJson(CollectionJsonAdapter.java:84)
                                                                 at com.squareup.moshi.CollectionJsonAdapter$2.toJson(CollectionJsonAdapter.java:52)
                                                                 at com.squareup.moshi.JsonAdapter$1.toJson(JsonAdapter.java:75)
                                                                 at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:44)
                                                                 at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:50)
                                                                 at package.network.DatabaseSyncHelper.sendContacts(DatabaseSyncHelper.java:203)
                                                                 at package.network.DatabaseSyncHelper.lambda$getCallLogs$2(DatabaseSyncHelper.java:167)
                                                                 at package.network.DatabaseSyncHelper.access$lambda$2(DatabaseSyncHelper.java:0)
                                                                 at package.network.DatabaseSyncHelper$$Lambda$5.call(Unknown Source)
                                                                 at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                                                 at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                 at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:227)
                                                                 at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                 at android.os.Handler.handleCallback(Handler.java:733)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:146)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5602)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                 at dalvik.system.NativeStart.main(Native Method)`

`listContacts` are of course initialized as adapter. Even checked if they are null and they are not. So I think there might be something with adapter. As I read from documentation `JsonDataException` stand for "the JSON document is well-formed, but doesn’t match the expected format", but I don't understand what that really means. Any help appreciated!

**Comment by swankjesse** [comment]
It looks like we’re swallowing the useful parts of the stack trace. I’m fixing that here:
https://github.com/square/moshi/pull/195

**Comment by janswist** [comment]
@swankjesse Works like a charm now! Helps a lot - now I can put finger on error. Thanks for so fast reaction!
