### ISSUE TITLE
Enum adapter stop reading name value from @Json in v1.4.0

### ISSUE THREAD

**Issue by cesarnorena** [square/moshi#263]
I update from v1.3.1 to v1.4.0 and the enum adapter stop reading the name in json annotation. Now I get null for ExampleEntity.value

> @Json(name="value")

I have the next Json and the entity to store it:

```
{"value":1}

data class ExampleEntity(
    val value: ExampleEnum?
)
```

My Enum class is like this:

```
enum class ExampleEnum {
    @Json(name = "1") FIRST,
}
```

**Comment by cesarnorena** [comment]
I suppose that this is happening after remove the next lines in v1.4.0 from "fromJson"

```
T constant = nameConstantMap.get(name);
if (constant != null) return constant;
```

**Comment by cesarnorena** [comment]
```
Exception in thread "main" com.squareup.moshi.JsonDataException: Expected one of [0, 1] but was 0 at path $.value
	at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.fromJson(StandardJsonAdapters.java:244)
	at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.fromJson(StandardJsonAdapters.java:213)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127)
	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:204)
	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:166)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:127)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:34)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:38)
```

**Comment by NightlyNexus** [comment]
I do not think this worked in 1.3.1, either. It would have been a bug if it did.

I tried running
```java
@Test public void annotatedEnum() throws Exception {
  Moshi moshi = new Moshi.Builder().build();
  JsonAdapter<Roshambo> adapter = moshi.adapter(Roshambo.class).lenient();
  assertThat(adapter.fromJson("1")).isEqualTo(Roshambo.SCISSORS);
  assertThat(adapter.toJson(Roshambo.SCISSORS)).isEqualTo("1");
}
enum Roshambo {
  @Json(name = "1") SCISSORS
}
```
on https://github.com/square/moshi/tree/6d623663cbde4bc14c882ab876aacf6975ee2245, and it failed properly.

Enums need to be string values, not numbers.

**Comment by cesarnorena** [comment]
Ok, I ran the same test with 1.3.1 and the second assert does not work, just the first. How it can be done properly? Can It be with a JsonQualifier for those Enums with an int value?

```
enum class Roshambo(val value: Int) {
    SCISSORS(1),
    ROCK(2),
    PAPER(3);

    companion object {
        private val map = Roshambo.values().associateBy(Roshambo::value);
        fun fromInt(type: Int) = map[type]
    }
}
```

**Comment by JakeWharton** [comment]
In Java:

class RoshamboAdapter {
  @ToJson public int toJson(Roshambo roshambo) {
    return roshambo.value;
  }
  @FromJson public Roshambo fromJson(int value) {
    return Roshambo.fromInt(value);
  }
}

**Comment by NightlyNexus** [comment]
Oh, as an aside, I'm reading these commits now; that's funny that worked before. interesting!

Yep, use an adapter if you need it.

**Comment by cesarnorena** [comment]
@JakeWharton Thats make me do an adapter for each Enum with an Int value. It will be nice something for handle Int values like an Enum, thats make the code more readable that just a Int.

**Comment by JakeWharton** [comment]
You can write a JsonAdapter.Factory that matches enums based on an
interface or something when you want this behavior.

**Comment by cesarnorena** [comment]
I implemented a new FACTORY adapter for that, but the test does not pass because JsonWrite.value(String) returns the value with double quote.

```
import co.tappsi.driver.domain.models.IntegerEnumAdapter
import com.squareup.moshi.Json
import com.squareup.moshi.Moshi
import org.junit.Test

class MoshiAdapterTest {

    @Test
    @Throws(Exception::class)
    fun annotatedEnum() {
        val moshi = Moshi.Builder()
                .add(IntegerEnumAdapter.FACTORY)
                .build()
        val adapter = moshi.adapter(Roshambo::class.java).lenient()
        assert(adapter.fromJson("1") == Roshambo.SCISSORS)
        val json = adapter.toJson(Roshambo.SCISSORS)
        assert(json == "1")
    }

    enum class Roshambo {
        @Json(name = "1") SCISSORS
    }
}

```
```
import com.squareup.moshi.*
import java.io.IOException
import java.util.*

internal class IntegerEnumAdapter<T : Enum<*>> private constructor(enumType: Class<T>) : JsonAdapter<T>() {

    companion object {

        val FACTORY: JsonAdapter.Factory = Factory { type, annotations, moshi ->
            val rawType = Types.getRawType(type)
            if (rawType.isEnum) {
                return@Factory IntegerEnumAdapter(rawType as Class<Enum<*>>)
            }
            null
        }
    }

    private val nameStrings: Array<String?>
    private val nameConstantMap: MutableMap<String, T>

    init {
        try {
            val constants = enumType.enumConstants
            nameStrings = arrayOfNulls<String>(constants.size)
            nameConstantMap = LinkedHashMap()
            for (i in constants.indices) {
                val constant = constants[i]
                val annotation = enumType.getField(constant.name).getAnnotation(Json::class.java)
                val name = annotation?.name ?: constant.name
                nameConstantMap.put(name, constant)
                nameStrings[i] = name
            }
        } catch (e: NoSuchFieldException) {
            throw AssertionError("Missing field in ${enumType.name}")
        }
    }

    @Throws(IOException::class)
    override fun fromJson(reader: JsonReader): T {
        val name = reader.nextString()
        val constant = nameConstantMap[name]
        if (constant != null) return constant
        throw JsonDataException("Expected one of ${Arrays.asList(*nameStrings)} " +
                "but was $name at path ${reader.path}")
    }

    @Throws(IOException::class)
    override fun toJson(writer: JsonWriter, value: T) {
        val newValue = nameConstantMap.filter { value == it.value }.map { it.key }.firstOrNull()
        if (newValue!=null) writer.value(newValue) else writer.nullValue()
    }
}
```

**Comment by NightlyNexus** [comment]
maybe just use a BiMap or something to hack this together?
Quick take on it in Java:
```java
final class IntegerEnumJsonAdapter<T extends Enum<?>> extends JsonAdapter<T> {
  static final Factory FACTORY = new Factory() {
    @Override public com.squareup.moshi.JsonAdapter<?> create(Type type,
        Set<? extends Annotation> annotations, Moshi moshi) {
      Class<?> rawType = Types.getRawType(type);
      if (!rawType.isEnum()) {
        return null;
      }
      // noinspection unchecked
      Class<? extends Enum<?>> enumType = (Class<? extends Enum<?>>) rawType;
      Enum<?>[] constants = enumType.getEnumConstants();
      Map<Integer, Enum<?>> nameToConstant = new LinkedHashMap<>(constants.length);
      Map<Enum<?>, Integer> constantToName = new LinkedHashMap<>(constants.length);
      for (Enum<?> constant : constants) {
        String constantName = constant.name();
        Json annotation;
        try {
          annotation = enumType.getField(constantName).getAnnotation(Json.class);
        } catch (NoSuchFieldException e) {
          throw new AssertionError("Missing field in " + enumType.getName(), e);
        }
        String name = annotation != null ? annotation.name() : constantName;
        try {
          int intName = Integer.parseInt(name);
          nameToConstant.put(intName, constant);
          constantToName.put(constant, intName);
        } catch (NumberFormatException e) {
          return moshi.nextAdapter(this, type, annotations);
        }
      }
      return new IntegerEnumJsonAdapter<>(nameToConstant, constantToName).nullSafe();
    }
  };

  private final Map<Integer, T> nameToConstant;
  private final Map<T, Integer> constantToName;

  IntegerEnumJsonAdapter(Map<Integer, T> nameToConstant, Map<T, Integer> constantToName) {
    this.nameToConstant = nameToConstant;
    this.constantToName = constantToName;
  }

  @Override public T fromJson(JsonReader reader) throws IOException {
    int intName = reader.nextInt();
    T value = nameToConstant.get(intName);
    if (value == null) {
      throw new JsonDataException("Expected one of "
          + nameToConstant.keySet().toString() + " but was " + intName + " at path "
          + reader.getPath());
    }
    return value;
  }

  @Override public void toJson(JsonWriter writer, T value) throws IOException {
    writer.value(constantToName.get(value));
  }
}
```

**Comment by swankjesse** [comment]
No action to take on this.

**Comment by Rody66** [comment]
Here is another working implementation in Kotlin:
```kotlin
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonDataException
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import java.io.IOException

class EnumValueJsonAdapter<T : IValueEnum>
private constructor(private val enumType: Class<T>, private val fallbackValue: T?,
                    private val useFallbackValue: Boolean) : JsonAdapter<T>() 
{
    private val enumValues: HashMap<Int, T>
    private val constants: Array<T> = enumType.enumConstants

    /**
     * Create a new adapter for this enum with a fallback value to use when the JSON value does not
     * match any of the enum's constants. Note that this value will not be used when the JSON value is
     * null, absent, or not a string. Also, the string values are case-sensitive, and this fallback
     * value will be used even on case mismatches.
     */
    fun withUnknownFallback(fallbackValue: T?): EnumValueJsonAdapter<T> {
        return EnumValueJsonAdapter(enumType, fallbackValue, true)
    }

    init {
        enumValues = HashMap(constants.size)
        constants.forEach {
            enumValues[it.value] = it
        }
    }

    @Throws(IOException::class)
    override fun fromJson(reader: JsonReader): T? {
        val value = reader.nextInt()
        if (enumValues.containsKey(value))
            return enumValues[value]

        val path = reader.path
        if (!useFallbackValue) {
            throw JsonDataException("Unknown value of enum ${enumType.name} ($value) at path $path")
        }
        return fallbackValue
    }

    @Throws(IOException::class)
    override fun toJson(writer: JsonWriter, value: T?) {
        if (value == null) {
            throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
        }
        writer.value(value.value)
    }

    override fun toString(): String {
        return "EnumJsonAdapter(" + enumType.name + ")"
    }

    companion object {
        fun <T : IValueEnum> create(enumType: Class<T>, unknownFallback: T? = null): EnumValueJsonAdapter<T> {
            val useFallbackValue = (unknownFallback != null)
            return EnumValueJsonAdapter(enumType, unknownFallback, useFallbackValue)
        }
    }
}
```
To use it, add `IValueEnum` interface to your project:
```kotlin
interface IValueEnum {
    val value: Int
}
```
And implement it:
```kotlin
enum class SomeEnum(override val value: Int) : IValueEnum {
    None(0),
    First(1)
}
```
Then add this line to the moshi builder:
` val moshi: Moshi = Moshi.Builder().add(SomeEnum::class.java, EnumValueJsonAdapter.create(SomeEnum::class.java))`
Also we can simplify using extension:
```kotlin
fun <T : IValueEnum> Moshi.Builder.addValueEnum(kClass: KClass<T>, unknownFallback: T? = null): Moshi.Builder
    = this.add(kClass.java, EnumValueJsonAdapter.create(kClass.java, unknownFallback).nullSafe())
```
And just use it like this:
`val moshi: Moshi = Moshi.Builder().addValueEnum(SomeEnum::class)`

**Comment by Rody66** [comment]
@swankjesse is there some way to not specify all enums in adapter builder? Can we somehow create a universal adapter with filter `where T: Enum<T>, IValueEnum`, which will provide serialization and deserializaion for all types, matching this filter?

**Comment by CRaFT4ik** [comment]
This is my Kotlin solution without additional interface and actions to specify each enum in adapter builder.
It's working for each enum class exactly as original adapter, but allow you to specify integer values (example: `@Json(name = "128")`).
```Kotlin
/** Фабрика для обработки enum классов. См. [EnumIntSafeJsonAdapter]. */
object EnumJsonAdapterFactory : JsonAdapter.Factory
{
    override fun create(type: Type, annotations: Set<Annotation>, moshi: Moshi): JsonAdapter<*>? {
        if (annotations.isNotEmpty()) {
            return null // Annotations? This factory doesn't apply.
        }

        if(type !is Class<*> || !type.isEnum) {
            return null // Not enum type? This factory doesn't apply.
        }

        return EnumIntSafeJsonAdapter(type as Class<Enum<*>>).nullSafe()
    }
}

/** Допускает числовые значения типа @Json(name = "128") для enum классов. */
internal class EnumIntSafeJsonAdapter<T : Enum<T>>(private val enumType: Class<T>) : JsonAdapter<T>()
{
    private val nameStrings: Array<String?>
    private val constants: Array<T>
    private var options: JsonReader.Options

    @Throws(IOException::class)
    override fun fromJson(reader: JsonReader): T {
        val name = reader.nextString()
        val index = options.strings().indexOf(name)
        if (index != -1) return constants[index]

        // We can consume the string safely, we are terminating anyway.
        val path = reader.path
        throw JsonDataException("Expected one of " + listOf(*nameStrings) + " but was " + name + " at path " + path)
    }

    @Throws(IOException::class)
    override fun toJson(writer: JsonWriter, value: T?) {
        writer.value(nameStrings[value!!.ordinal])
    }

    override fun toString(): String = "JsonAdapter(" + enumType.name + ")"

    init {
        try {
            constants = enumType.enumConstants!!
            nameStrings = arrayOfNulls(constants.size)
            for (i in constants.indices) {
                val constant = constants[i]
                val annotation = enumType.getField(constant.name).getAnnotation(Json::class.java)
                val name = annotation?.name ?: constant.name
                nameStrings[i] = name
            }
            options = JsonReader.Options.of(*nameStrings)
        } catch (e: NoSuchFieldException) {
            throw AssertionError("Missing field in " + enumType.name, e)
        }
    }
}
```

Usage: `val moshi: Moshi = Moshi.Builder().add(EnumJsonAdapterFactory)`

Please correct me if something suddenly.

**Comment by mrzbn** [comment]
why for many intuitive things like this issue, everyone has to write a JsonAdapter?
