### ISSUE TITLE
Kotlin val vs var

### ISSUE THREAD

**Issue by jmfayard** [square/moshi#267]
I have a strange issue when using moshi 1.4 with kotlin 1.1

The following snippet works as expected

```
data class Wrapper(
  val map: Map<String, Any>
)

fun main(args: Array<String>) {
    val moshi = Moshi.Builder().build()
    val pat = Wrapper(map = mapOf("ok" to true))
    println(moshi.adapter(Wrapper::class.java).toJson(pat))
   // {"map":{"ok":true}}
}
```

Now if I change my mind and make map a mutable variable with  `var map: Map<String, Any>`, I get this

```
Exception in thread "main" java.lang.IllegalArgumentException: Expected a Class, ParameterizedType, or GenericArrayType, but <null> is of type null
	at com.squareup.moshi.Types.getRawType(Types.java:165)
	at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:82)
	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:74)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:99)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:57)
	at com.squareup.moshi.MapJsonAdapter.<init>(MapJsonAdapter.java:46)
	at com.squareup.moshi.MapJsonAdapter$1.create(MapJsonAdapter.java:37)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:99)
	at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:90)
	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:74)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:99)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:61)
```

The same happens for lists

```kotlin
data class Wrapper(
    val list : List<Any> /* OK */
    var list : List<Any>, /* ERROR <null> is of type null */

    var map: Map<String, Any> /* ERROR <null> is of type null */
    val map: Map<String, Any> /* OK */
    var map: Map<Any, Boolean> /* OK */
    val map: Map<String, Any> /* OK */
    var map: Map<String, Boolean> /* OK */
)
```

**Comment by Egorand** [comment]
The issue is also reproducible with the following Java class:

```java
class Wrapper {
  Map<String, ? extends Object> map;
}
```

This is what `var` gets compiled into. `val` yields the following

```java
class Wrapper {
  Map<String, Object> map;
}
```

which Moshi has no problems serializing.

**Comment by trevjonez** [comment]
Have you tried using  `@JvmSuppressWildcards`?

`val map: Map<String, @JvmSuppressWildcards Any>`

**Comment by Egorand** [comment]
@trevjonez that works! Both

```kotlin
var map: Map<String, @JvmSuppressWildcards Any>
```

and

```kotlin
@JvmSuppressWildcards var map: Map<String, Any>
```

**Comment by jahunt1** [comment]
Thank you @trevjonez! This answer has helped me twice now.

**Comment by NightlyNexus** [comment]
I think this is the same as #338, but it's worth seeing how that affects Kotlin. thanks!

**Comment by swankjesse** [comment]
Recommending either Moshi 1.5’s native Kotlin support, or Kotshi for this.
