### ISSUE TITLE
Error where map key doesn’t encode as a string is incoherent

### ISSUE THREAD

**Issue by swankjesse** [square/moshi#277]
When a map key doesn’t have a natural string encoding we crash with a difficult exception. [For example](https://bitbucket.org/robeden/moshi-test), when writing a `Map<Matcher,String> identifiers` we crash like so:

```
Exception in thread "main" java.lang.IllegalStateException: Nesting problem.
        at com.squareup.moshi.JsonUtf8Writer.beforeValue(JsonUtf8Writer.java:367)
        at com.squareup.moshi.JsonUtf8Writer.open(JsonUtf8Writer.java:102)
        at com.squareup.moshi.JsonUtf8Writer.beginObject(JsonUtf8Writer.java:89)
        at com.squareup.moshi.ClassJsonAdapter.toJson(ClassJsonAdapter.java:177)
        at com.squareup.moshi.JsonAdapter$2.toJson(JsonAdapter.java:134)
        at com.squareup.moshi.MapJsonAdapter.toJson(MapJsonAdapter.java:56)
```

Instead we should say “Matcher cannot be used as a map key in JSON.”

The fix for the above example is a JSON adapter, like so:

```
class MatcherJsonAdapter {
  @ToJson String matcherToJson(Matcher m) {
    return m.type + ":" + m.match;
  }

  @FromJson Matcher matcherFromJson(String s) {
    String[] parts = s.split(":", 1);
    return new Matcher(MatchType.valueOf(parts[0]), parts[1]);
  }
}
```

**Comment by NightlyNexus** [comment]
maybe even easier to demonstrate: just use a boolean key.

Yeah, looks tricky.
The MapJsonAdapter could wrap the JsonWriter that's fed into key adapter to know when the writer is called without a name or a value(string) or a value(number). That doesn't sound like a good special case for a JsonWriter type.
The MapJsonAdapter could catch the exception. That obviously feels bad; it'd be nice to get the state up into the adapter itself.
