### ISSUE TITLE
Cannot read special characters:\n\r in string

### ISSUE THREAD

**Issue by sitexa** [square/moshi#291]
Moshi raise exception when encounter special chars : \n\r , is it an issue?

> 
> val response = call.execute()
> val jsonString = response.body().toString()
> val moshi = Moshi.Builder().add(JodaTimeAdapter()).build()
> val sweetAdapter = moshi.adapter<Sweet>(Sweet::class.java).lenient()
> val sweet = sweetAdapter.fromJson(jsonString)
> 

the response log:

>`INFO: {"id":9,"userId":"xnpeng","text":"Note that\u0027s the method \"annotated\" with \n\n@FromJson does not need to $take a \nString as an argument.","date":1492000948000}`

the jsonString print in console:

> {id=9.0, userId=xnpeng, text=Note that's the method "annotated" with 
>
>@FromJson does not need to $take a 
>String as an argument., date=1.492000948E12}

Please note that the log INFO  is different from println() in console. The log INFO is correct json object, while the jsonString is not correct, but it is the original thing. Then when run fromJson(jsonString) it raise Exception. That means I cannot get right json object by `response.body().toString()` .  How to read the right json?

> 
> Exception in thread "main" com.squareup.moshi.JsonEncodingException: Unterminated object at path $.text
> 	at com.squareup.moshi.JsonReader.syntaxError(JsonReader.java:212)
> 	at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:240)
> 

Is this an issue?

**Comment by sitexa** [comment]
I find the point:
`val jsonString = response.body().toString()`
change to 
`val jsonString = (response.body() as ResponseBody).string()`
The problem is solved.

Kotlin says there is "smart cast", but here , I must explicitly do type cast, otherwise, there is no .string() method, instead a (Any/Object).toString() method. That is the point.
