### ISSUE TITLE
Recipe for base64 byte arrays

### ISSUE THREAD

**Issue by swankjesse** [square/moshi#31]

**Comment by adriancole** [comment]
I could use this. currently 

`ByteString.decodeBase64(reader.nextString()).toByteArray()`

and

`new Buffer().write(value.value).readByteString().base64Url()`

**Comment by bjdodson** [comment]
We are using this on Android:

```java
    Moshi moshi = new Moshi.Builder()
            .add(new JsonAdapter.Factory() {
                @Override
                public JsonAdapter<?> create(Type type, Set<? extends Annotation> annotations, Moshi moshi) {
                    Class<?> raw = Types.getRawType(type);
                    if (raw == byte[].class) {
                        return new Base64Adapter().nullSafe();
                    }

                    return null;
                }
            })
            .build();

    class Base64Adapter extends JsonAdapter<byte[]>  {
        @Override
        public byte[] fromJson(JsonReader reader) throws IOException {
            String string = reader.nextString();
            return Base64.decode(string, Base64.NO_WRAP);
        }

        @Override
        public void toJson(JsonWriter writer, byte[] bytes) throws IOException {
            String string = Base64.encodeToString(bytes, Base64.NO_WRAP);
            writer.value(string);
        }
    }
```

The factory seems like boilerplate that may be unneeded for similar adapters. Perhaps a new builder.add() that fetches the raw type:

```java
   Moshi moshi = new Moshi.Builder()
       .add(byte[].class, new Base64Adapter(), true)
       .build()
```

**Comment by swankjesse** [comment]
There is an overload that bypasses the factory. But even better is to use annotations:

```
  Moshi moshi = new Moshi.Builder()
      .add(new Base64Adapter())
      .build();

  class Base64Adapter {
    @FromJson byte[] fromJson(String string) {
      return Base64.decode(string, Base64.NO_WRAP);
    }

    @ToJson public String toJson(byte[] bytes) {
      return Base64.encodeToString(bytes, Base64.NO_WRAP);
    }
  }
```

**Comment by bjdodson** [comment]
Clean! But this still fails for me when the byte[] is used as the value of a Map, for example. Conversion using `Types.getRawType(type)` in the Factory was my fix.

```
class ClusterIdentities {
    ...

    @Json(name = "ClusterKeys")
    public Map<String, byte[]> clusterKeys;
}
```


```
E/AndroidRuntime(14763): com.squareup.moshi.JsonDataException: Expected BEGIN_ARRAY but was STRING at path $.ClusterKeys.ONE
E/AndroidRuntime(14763): 	at com.squareup.moshi.JsonReader.beginArray(JsonReader.java:346)
E/AndroidRuntime(14763): 	at com.squareup.moshi.ArrayJsonAdapter.fromJson(ArrayJsonAdapter.java:53)
E/AndroidRuntime(14763): 	at com.squareup.moshi.JsonAdapter$1.fromJson(JsonAdapter.java:68)
E/AndroidRuntime(14763): 	at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:68)
E/AndroidRuntime(14763): 	at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:29)
E/AndroidRuntime(14763): 	at com.squareup.moshi.JsonAdapter$1.fromJson(JsonAdapter.java:68)
E/AndroidRuntime(14763): 	at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:183)
E/AndroidRuntime(14763): 	at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:144)
E/AndroidRuntime(14763): 	at com.squareup.moshi.JsonAdapter$1.fromJson(JsonAdapter.java:68)
E/AndroidRuntime(14763): 	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:33)
E/AndroidRuntime(14763): 	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:37)
E/AndroidRuntime(14763): 	at mobisocial.serialization.SerializationUtils.fromJson(SerializationUtils.java:48)
E/AndroidRuntime(14763): 	at mobisocial.longdan.ClusterIdentities.getConfiguration(ClusterIdentities.java:85)
E/AndroidRuntime(14763): 	at mobisocial.omlib.client.LongdanClient.configureIdpConnection(LongdanClient.java:327)
E/AndroidRuntime(14763): 	at mobisocial.omlib.client.LongdanClient.<init>(LongdanClient.java:152)
E/AndroidRuntime(14763): 	at mobisocial.omlib.service.LongdanClientHelper.resetInstance(LongdanClientHelper.java:46)
E/AndroidRuntime(14763): 	at mobisocial.omlib.service.LongdanClientHelper.getInstance(LongdanClientHelper.java:34)
E/AndroidRuntime(14763): 	at mobisocial.omlib.service.OmlibService.getLdClient(OmlibService.java:279)
E/AndroidRuntime(14763): 	at mobisocial.omlib.service.OmlibService$3.run(OmlibService.java:165)
E/AndroidRuntime(14763): 	at java.lang.Thread.run(Thread.java:818)

```
