### ISSUE TITLE
IllegalStateException on creating JsonAdapter for a data class with @Transient enum class item 

### ISSUE THREAD

**Issue by rajatbeck** [square/moshi#387]
For the following `data class`, `JsonAdapter` is not created. 

```@Parcelize
@SuppressLint("ParcelCreator")
data class Clazz(
        @Json(name = "id") val id: Long,
        @Transient val type: Type
) : Parcelable {    
    enum class Type { New, Old }
}
```
The following code gives `IllegalStateException`

```
val adapter = moshi.adapter<Clazz>(Clazz::class.java)
val string = adapter.toJson(Clazz(11, Clazz.Type.New))
```

```
java.lang.IllegalArgumentException: No property for required constructor parameter #1 type of fun <init>(kotlin.Long, com.my.app.data.models.Clazz.Type): com.my.app.data.models.Clazz
              at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:196)
              at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
              at com.squareup.moshi.Moshi.adapter(Moshi.java:62)
              at com.my.app.MyFragment.placeOrder(MyFragment.kt:125)
              at com.my.app.MyFragment$onViewCreated$2.onClick(MyFragment.kt:217)
              at android.view.View.performClick(View.java:5637)
              at android.view.View$PerformClick.run(View.java:22429)
              at android.os.Handler.handleCallback(Handler.java:751)
              at android.os.Handler.dispatchMessage(Handler.java:95)
              at android.os.Looper.loop(Looper.java:154)
              at android.app.ActivityThread.main(ActivityThread.java:6119)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by swankjesse** [comment]
Because `Type` is transient, you need to provide a default value for Moshi to use when constructing a `Clazz`.

**Comment by NightlyNexus** [comment]
☝️ Yep, transient means that Moshi won't ever deserialize that field, so a default value is required.

The next version of Moshi will hopefully give [a clearer error message here](https://github.com/square/moshi/blob/b7a91e05576c293053fc042c53e45707c3f5f053/kotlin/src/main/java/com/squareup/moshi/KotlinJsonAdapter.kt#L172).

**Comment by swankjesse** [comment]
No action to take on this.
