### ISSUE TITLE
ProGuard configuration for Kotlin 1.2

### ISSUE THREAD

**Issue by aaronhe42** [square/moshi#402]
We upgraded to Kotlin 1.2 but got warnings at compile time and crashes at runtime. This is a ProGuard config change makes the app working again.

```
-dontwarn kotlin.reflect.jvm.internal.**
-keep class kotlin.reflect.jvm.internal.** { *; }
```

Hesitant to submit a PR just yet because I didn't spend too much time to see if this is the minimum config to get it working with kotlin 1.2. The crashes were reported very late night so I just quickly made a hotfix.

Posted here in case someone else has this issue. Or someone is more familiar with the changes can shed some light on this. I might find some time tomorrow digging deeper into this.

The warnings were:

```
Warning: kotlin.reflect.jvm.internal.KClassImpl: can't find referenced class kotlin.reflect.jvm.internal.KClassImpl$kotlin.reflect.jvm.internal.KClassImpl$Data
Warning: kotlin.reflect.jvm.internal.KClassImpl: can't find referenced class kotlin.reflect.jvm.internal.KClassImpl$kotlin.reflect.jvm.internal.KClassImpl$Data
Warning: kotlin.reflect.jvm.internal.KClassImpl$data$1: can't find referenced class kotlin.reflect.jvm.internal.KClassImpl$kotlin.reflect.jvm.internal.KClassImpl$Data
Warning: kotlin.reflect.jvm.internal.KClassImpl$data$1: can't find referenced class kotlin.reflect.jvm.internal.KClassImpl$kotlin.reflect.jvm.internal.KClassImpl$Data
Warning: kotlin.reflect.jvm.internal.impl.protobuf.SmallSortedMap: can't find referenced class kotlin.reflect.jvm.internal.impl.protobuf.SmallSortedMap$kotlin.reflect.jvm.internal.impl.protobuf.SmallSortedMap$Entry
Warning: kotlin.reflect.jvm.internal.impl.protobuf.SmallSortedMap: can't find referenced class kotlin.reflect.jvm.internal.impl.protobuf.SmallSortedMap$kotlin.reflect.jvm.internal.impl.protobuf.SmallSortedMap$EntrySet
Warning: kotlin.reflect.jvm.internal.impl.protobuf.SmallSortedMap$Entry: can't find referenced class kotlin.reflect.jvm.internal.impl.protobuf.SmallSortedMap$kotlin.reflect.jvm.internal.impl.protobuf.SmallSortedMap$Entry
Warning: kotlin.reflect.jvm.internal.impl.protobuf.SmallSortedMap$Entry: can't find referenced class kotlin.reflect.jvm.internal.impl.protobuf.SmallSortedMap$kotlin.reflect.jvm.internal.impl.protobuf.SmallSortedMap$Entry
```

And the stacktrace for the crashes:

```
Fatal Exception: java.lang.NoClassDefFoundError: kotlin.reflect.jvm.internal.impl.builtins.b
       at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(KotlinBuiltIns.java:150)
       at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.(JvmBuiltIns.kt)
       at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.(JvmBuiltIns.kt)
       at kotlin.reflect.jvm.internal.impl.load.kotlin.reflect.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:54)
       at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:35)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:32)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(KDeclarationContainerImpl.kt)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:46)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:43)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
       at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt)
       at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:172)
       at kotlin.reflect.jvm.internal.KClassImpl.getConstructorDescriptors(KClassImpl.kt:186)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:90)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:43)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
       at kotlin.reflect.jvm.internal.KClassImpl$Data.getConstructors(KClassImpl.kt)
       at kotlin.reflect.jvm.internal.KClassImpl.getConstructors(KClassImpl.kt:222)
       at kotlin.reflect.full.KClasses.getPrimaryConstructor(KClasses.kt:40)
       at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:160)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
       at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:91)
       at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
       at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313)
       at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:736)
       at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:169)
       at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
       at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
```

and,

```
Caused by java.util.NoSuchElementException: Collection is empty.
       at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:166)
       at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion.(BuiltInsLoader.kt)
       at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader.(Unknown Source)
       at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(KotlinBuiltIns.java:150)
       at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.(JvmBuiltIns.kt)
       at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.(JvmBuiltIns.kt)
       at kotlin.reflect.jvm.internal.impl.load.kotlin.reflect.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:54)
       at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:35)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:32)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
       at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(Unknown Source:7)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:46)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:43)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
       at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(Unknown Source:7)
       at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:172)
       at kotlin.reflect.jvm.internal.KClassImpl.getConstructorDescriptors(KClassImpl.kt:186)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:90)
       at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:43)
       at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
       at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
       at kotlin.reflect.jvm.internal.KClassImpl$Data.getConstructors(Unknown Source:7)
       at kotlin.reflect.jvm.internal.KClassImpl.getConstructors(KClassImpl.kt:222)
       at kotlin.reflect.full.KClasses.getPrimaryConstructor(KClasses.kt:40)
       at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:160)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:58)
       at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:52)
       at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:36)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:58)
       at com.tinder.api.model.common.AutoValue_ApiMatch$MoshiJsonAdapter.(AutoValue_ApiMatch.java)
       at com.tinder.api.model.common.ApiMatch.jsonAdapter(ApiMatch.java:19)
       at com.tinder.api.moshi.AutoValueMoshi_TinderMoshiAdapterFactory.create(AutoValueMoshi_TinderMoshiAdapterFactory.java:220)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:58)
       at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:52)
       at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:36)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:58)
       at com.tinder.api.model.updates.AutoValue_Updates$MoshiJsonAdapter.(AutoValue_Updates.java)
       at com.tinder.api.model.updates.Updates.jsonAdapter(Updates.java:20)
       at com.tinder.api.moshi.AutoValueMoshi_TinderMoshiAdapterFactory.create(AutoValueMoshi_TinderMoshiAdapterFactory.java:170)
       at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
       at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:91)
       at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
       at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:313)
       at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:736)
       at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:169)
       at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
       at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
       at java.lang.reflect.Proxy.invoke(Proxy.java:913)
```

**Comment by aaronhe42** [comment]
Finally got some time looking a little deeper into this.

The ProGuard warning actually wasn't coming from the usage of kotlin reflect in moshi kotlin, but rather kotlin reflect 1.2. We explicitly added kotlin reflect 1.2 because of the `Runtime JAR files in the classpath should have the same version` warning. Though, the kotlin reflect is only used in moshi kotlin, so we can just ignore the warning?

Now the `NoClassDefFoundError` crashes may just be API changes in 1.2. And the following `NoSuchElementException` could just be the cascading effect of? Played around with different ProGuard configurations and it looks like `-keep public class kotlin.reflect.jvm.internal.impl.builtins.* { public *; }` is the minimum config to get the app working.

So maybe a PR on ProGuard configuration with kotlin reflect 1.2?

**Comment by recoverrelax** [comment]
exactly same problem here. I just ignore the warning because if i explicitly add 1.2, it breaks my release build with those warnings.

**Comment by hzsweers** [comment]
FWIW - I got a similar trace from running the lint driver in android tools from the CLI. Posted to lint-dev, maybe Tor can shed more light - https://groups.google.com/forum/#!topic/lint-dev/70j4pQ8uMuA

**Comment by premnirmal** [comment]
Same crash here. Does anybody have any idea why explicitly adding `kotlin-reflect` as a dependency causes this crash?

**Comment by kafumi** [comment]
It looks an issue of `kotlin-reflect` 1.2.30. I believe it doesn't matter who depends on the library. In `kotlin-reflect`, the implementation class of `kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader` is not directly referenced in code and will be loaded by Java's `ServiceLoader` using service provider configuration files in META-INF. The class can be trimmed by ProGuard because of no explicit reference and `ServiceLoader` will fail to load it at runtime.

`kotlin-reflect` project has ProGuard configurations to keep it *for their build*. I think copying them is another option of workaround.

https://github.com/JetBrains/kotlin/blob/1.2.30/core/reflection.jvm/reflection.pro#L16-L17

```
-keep class * implements kotlin.reflect.jvm.internal.impl.resolve.ExternalOverridabilityCondition { public protected *; }
-keep class * implements kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader { public protected *; }
```

`ExternalOverridabilityCondition` looks not used by moshi but it might be better to define configuration for it as well because the interface also depends on `ServiceLoader`.

**Comment by williamwue** [comment]
Same issue, have any update info about it?

**Comment by pddkhanh** [comment]
Same issue here. Watching on this.

**Comment by aaronhe42** [comment]
i don't have an update on this proguard issue per se. but we are in the process of migrating reflection based moshi kotlin to the codegen. haven't had any horror proguard stories keep me awake at night.

**Comment by JakeWharton** [comment]
The minimum config is
```
-keep class kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoaderImpl
```
which will keep only the no-arg constructor of the service defined in `META-INF/services/kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader`. Anything more is keeping too much.

**Comment by emakar** [comment]
I might missed something, but there is no `kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoaderImpl`
full name is `kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl`

and still, this results in various errors of missing `FieldOverridabilityCondition`, etc

**Comment by AllenWen** [comment]
> I might missed something, but there is no `kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoaderImpl`
> full name is `kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl`
> 
> and still, this results in various errors of missing `FieldOverridabilityCondition`, etc

same error

**Comment by androidovshchik** [comment]
`-ignorewarnings`?

**Comment by Diolor** [comment]
@androidovshchik no because your code will crash in the runtime :)

As of latest kotlin-stdlib (right now **1.3.41** but still uses kotlin-reflect **1.2.71**) _I think_ the minimum configuration should change to the following:

```
-keep class kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl
-keep class kotlin.reflect.jvm.internal.impl.load.java.FieldOverridabilityCondition
-keep class kotlin.reflect.jvm.internal.impl.load.java.ErasedOverridabilityCondition
-keep class kotlin.reflect.jvm.internal.impl.load.java.JavaIncompatibilityRulesOverridabilityCondition
```

I still don't understand why the first rule (with the explicit path) works but not this one:
`-keep class kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader` 
which is in the META-INF/services 🤔 

And as in #880 this:

```
-keep class kotlin.Metadata { *; }
```

**Comment by ZacSweers** [comment]
After talking with Jetbrains on the kotlin-lang slack, I've opened a PR to add embedded proguard rules to kotlin-reflect here: https://github.com/JetBrains/kotlin/pull/2893

Please feel free to chime in with any suggestions!
