### ISSUE TITLE
Problem when using List<interface>  in data class

### ISSUE THREAD

**Issue by sidzi** [square/moshi#432]
`java.lang.IllegalArgumentException: No JsonAdapter for interface .home.model.PageItem annotated []
	at com.squareup.moshi.Moshi.adapter(Moshi.java:116)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:58)
	at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:52)
	at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:36)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
	at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:184)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
	at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:184)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:58)
`
When using abstract classes : 

`java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at kotlin.reflect.jvm.internal.FunctionCaller$Constructor.call(FunctionCaller.kt:66)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:107)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod(KCallableImpl.kt:147)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:111)
	at com.squareup.moshi.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:88)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:72)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:72)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.JsonAdapter$3.fromJson(JsonAdapter.java:152)
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:35)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:39)
`

Can we only use data classes and not interfaces ? Is there a workaround ?
It works when I use an implementation of the interface

**Comment by NightlyNexus** [comment]
Value types are preferable, yes.

Also, how would you expect an interface or abstract class to get deserialized? There are no clear bindings for such types.
If you need to use them, consider using custom JsonAdapters: https://github.com/square/retrofit/blob/fe7280aac7d7e4553c84523e65f66fb9f33a0356/retrofit-converters/moshi/src/test/java/retrofit2/converter/moshi/MoshiConverterFactoryTest.java#L76-L96
