### ISSUE TITLE
Having proguard issues

### ISSUE THREAD

**Issue by schwiz** [square/moshi#478]
I am using multiple type adapters and the example KotlinFactory however when proguard is enabled I am running into different issues. 
I have the following rules:
```
-dontwarn okio.**
-dontwarn javax.annotation.**
-dontwarn org.jetbrains.annotations.**
-keepclasseswithmembers class * {
    @com.squareup.moshi.* <methods>;
}
-keepattributes *Annotation*
-keepattributes EnclosingMethod
-keep @com.squareup.moshi.JsonQualifier interface *
-keep class kotlin.Metadata { *; }
```

However, with these rules when trying to deserialize data classes we get an exception:

```
Caused by: java.util.NoSuchElementException: Collection is empty.
at kotlin.a.r.b(_Collections.kt:166)
at kotlin.reflect.jvm.internal.impl.a.b$a.<clinit>(BuiltInsLoader.kt:38)
at kotlin.reflect.jvm.internal.impl.a.b.<clinit>(BuiltInsLoader.kt) 
at kotlin.reflect.jvm.internal.impl.a.i.c(KotlinBuiltIns.java:148) 
at kotlin.reflect.jvm.internal.impl.e.b.<init>(JvmBuiltIns.kt:56) 
at kotlin.reflect.jvm.internal.impl.e.b.<init>(JvmBuiltIns.kt:31) 
at kotlin.reflect.jvm.internal.a.j$a.a(RuntimeModuleData.kt:54) 
at kotlin.reflect.jvm.internal.ab.a(moduleByClassLoader.kt:58) 
at kotlin.reflect.jvm.internal.l$b$a.a(KDeclarationContainerImpl.kt:35) 
at kotlin.reflect.jvm.internal.l$b$a.invoke(KDeclarationContainerImpl.kt:32) 
at kotlin.reflect.jvm.internal.ac$a.a(ReflectProperties.java:93) 
at kotlin.reflect.jvm.internal.ac$c.a(ReflectProperties.java:32) 
at kotlin.reflect.jvm.internal.l$b.l(KDeclarationContainerImpl.kt) 
at kotlin.reflect.jvm.internal.j$a$i.a(KClassImpl.kt:46) 
at kotlin.reflect.jvm.internal.j$a$i.invoke(KClassImpl.kt:43) 
at kotlin.reflect.jvm.internal.ac$a.a(ReflectProperties.java:93) 
at kotlin.reflect.jvm.internal.ac$c.a(ReflectProperties.java:32) 
at kotlin.reflect.jvm.internal.j$a.a(KClassImpl.kt) 
at kotlin.reflect.jvm.internal.j.g(KClassImpl.kt:172) 
at kotlin.reflect.jvm.internal.j.d(KClassImpl.kt:250) 
```

Adding -keep class kotlin.reflect.jvm.internal.** to proguard fixes that problem but then it can not find the adapters for custom types such as this:
add(LocalTime::class.java, LocalTimeConverter().nullSafe()

It is looking for the full name org.threeteen.bp.LocalDate rather than the renamed org.threeteen.bp.a 

Any idea what my issue is here? Let me know if any more info could be helpful.

**Comment by SeboRax** [comment]
I'm facing the same problem and couldn't find a solution

**Comment by swankjesse** [comment]
Ick. Not sure where to start on this. The problem goes away when you disable ProGuard?

**Comment by schwiz** [comment]
@swankjesse yes it works fine with proguard disabled. I had just just hard code a couple cases into my proguard rules and its working fine now.
-keep class kotlin.reflect.**
-keep class org.threeten.bp.**
-keep class kotlin.Boolean
-keep class java.math.BigDecimal

**Comment by whalemare** [comment]
Got the same issue with proguard.
When ProGuard disables it`s works fine
