### ISSUE TITLE
FYI: Consider adding Moshi support to quicktype

### ISSUE THREAD

**Issue by dvdsgl** [square/moshi#528]
quicktype just added Kotlin support enabled by Klaxon: http://blog.quicktype.io/kotlin/

It would be great to support Moshi as well. Just bringing this opportunity to your attention, as it could help test Moshi and demonstrate how to use Moshi with JVM languages.

**Comment by swankjesse** [comment]
@dvdsgl neat. Wanna volunteer?

**Comment by swankjesse** [comment]
Enums are pretty straightforward. Easiest way is a `@FromJson/@ToJson` method pair. You could probably use a `when` statement. ([custom adapter example](https://github.com/square/moshi/blob/master/examples/src/main/java/com/squareup/moshi/recipes/CardAdapter.java))

Unions can be done in a couple ways. You can get an `Object` and use `instanceof`, or you can get a `JsonReader` and use `peek()`. ([example](https://github.com/square/moshi/blob/master/examples/src/main/java/com/squareup/moshi/recipes/MultipleFormats.java#L56))

Map is similar as long as the key is a String, or convertible to a string.

**Comment by swankjesse** [comment]
Oh, and for Arrays you use [Types.arrayOf()](https://square.github.io/moshi/1.x/moshi/com/squareup/moshi/Types.html#arrayOf-java.lang.reflect.Type-).

**Comment by dvdsgl** [comment]
I'm trying to make this sample work:

```kotlin
import com.squareup.moshi.*
import com.squareup.moshi.kotlin.KotlinJsonAdapterFactory

private val moshi = Moshi.Builder()
    .add(KotlinJsonAdapterFactory())
    .add(object {
        @ToJson fun toJson(x: Tuple): Any = when (x) {
			is Tuple.IntegerValue -> x.value
			is Tuple.StringValue  -> x.value
		}
        @FromJson fun fromJson(s: Any): Tuple = when (s) {
			is Int, is Long -> Tuple.IntegerValue(s)
			is String       -> Tuple.StringValue(s)
		}
    })
    .build()

data class TopLevel(val tuples: List<List<Tuple>>)

sealed class Tuple {
    class IntegerValue(val value: Long)  : Tuple()
    class StringValue(val value: String) : Tuple()
}

fun main(args: Array<String>) {
    val json = """
        {
          "tuples": [
              [0, "zero"],
              [1, "one"],
              [2, "two"]
          ]
      }
      """
    val adapter = moshi.adapter(TopLevel::class.java)
    val top = adapter.fromJson(json)
    println(adapter.toJson(top))
}
```

But I get

```
Exception in thread "main" com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was NUMBER at path $.tuples[0][0]
        at com.squareup.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:140)
        at com.squareup.moshi.kotlin.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:65)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
        at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
        at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.squareup.moshi.kotlin.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:81)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:41)
        at quicktype.MainKt.main(main.kt:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:61)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:109)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:119)
```

Can you help me understand how to make this case work? Then I can generalize it.

**Comment by dvdsgl** [comment]
Here's the implementation so far: https://app2.quicktype.io?share=aajwCbqOYCuOQtmI2EVV

**Comment by swankjesse** [comment]
Looks great!

I’d be tempted to organize the Moshi + companion objects a bit differently here; having the adapter as a companion field is problematic. It’s the kind of thing that can break class loading due to circular dependencies.

For top-level lists use `Types.newParameterizedType(List::class.java, Long::class.java)` and pass that to Moshi. Similarly for maps.

**Comment by dvdsgl** [comment]
Thanks!

How do you recommend handling the adaptors?

**Comment by dvdsgl** [comment]
Top-level maps and array now work, except when the values are primitives:

```
Caused by: java.lang.IllegalArgumentException: Unexpected primitive long. Use the boxed type.
        at com.squareup.moshi.internal.Util.checkNotPrimitive(Util.java:278)
        at com.squareup.moshi.internal.Util$ParameterizedTypeImpl.<init>(Util.java:307)
        at com.squareup.moshi.Types.newParameterizedType(Types.java:81)
        at quicktype.TopLevel.<clinit>(TopLevel.kt:18)
        ... 8 more
```

`Types.newParameterizedType(List::class.java, Long::class.java)` throws. Any idea how to resolve this?

**Comment by swankjesse** [comment]
Maybe this:

```
private val moshi = ...
private val topLevelMapAdapter = moshi.adapter<Map<String, Long>>(Types.newParameterizedType(Map::class.java, String::class.java, Long::class.java))
private val topLevelObjectAdapter = moshi.adapter(TopLevelObject::class.java)
```
With no explicit toJson/fromJson methods.

**Comment by JakeWharton** [comment]
Long::class.javaObjectType?

**Comment by dvdsgl** [comment]
Our test suite requires that for every top-level type `T`, there are function `fromJson :: String -> T` and `toJson :: T -> String`. These functions must have the same name regardless of whether `T` is primitive, object, map, array, or union. For now, defining them as members of the types is the best option I can understand for Kotlin, but I can add an option to remove them if you thank that's important to Kotlin users.

**Comment by dvdsgl** [comment]
@JakeWharton Brilliant, that fixed it.

**Comment by swankjesse** [comment]
Any further action on this? Thakns @dvdsgl !

**Comment by dvdsgl** [comment]
We got close but don't plan to finish the work! Sorry for dropping it but we've seen little Kotlin usage with quicktype and have moved on to other work for now. [The branch](https://github.com/quicktype/quicktype/pull/856) lives on in case anyone would like to finish it, it just needs union support.
