### ISSUE TITLE
Moshi converter for nested HashMap

### ISSUE THREAD

**Issue by shashank090789** [square/moshi#544]
I want to create converter for 

`HashMap<String, List<HashMap<String, Any>>>`

I have used following for this:

```kotlin
class MoshiJsonListAdapersFactory : JsonAdapter.Factory {
  override fun create(type: Type, annotations: Set<out Annotation>, moshi: Moshi): JsonAdapter<*>? {
    return when (type) {
      Types.newParameterizedType(Map::class.java, String::class.java, List::class.java) ->
        moshi.adapter<HashMap<String, List<HashMap<String, Any>>>>(type)
      Types.newParameterizedType(Map::class.java, String::class.java, Any::class.java) ->
        moshi.adapter<HashMap<String, String>>(type)
      else -> null
    }
  }
}
```

 but getting StackOverFlow error . Stacktrace is as follows:

`05-16 06:39:08.092 3051-3089/com.petroit.material E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
    Process: com.petroit.material, PID: 3051
    io.reactivex.exceptions.UndeliverableException: java.lang.StackOverflowError
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:64)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.StackOverflowError
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
        at com.squareup.moshi.Moshi$DeferredAdapter.fromJson(Moshi.java:234)
    	at com.squareup.moshi.Mos`

**Comment by swankjesse** [comment]
Try replacing the call to `moshi.adapter` with `moshi.nextAdapter`. The first method will create recursive adapters; the second one explicitly forces delegation.
