### ISSUE TITLE
Reflective adapter doesn't allow nullable generics.

### ISSUE THREAD

**Issue by NightlyNexus** [square/moshi#550]
```kotlin
data class Box<out T>(val data: T)

@Test fun nullableGenericTypes() {
  val moshi = Moshi.Builder().add(KotlinJsonAdapterFactory()).build()
  val stringBoxAdapter = moshi.adapter<Box<String?>>(
      Types.newParameterizedTypeWithOwner(KotlinJsonAdapterTest::class.java, Box::class.java,
          String::class.java)).serializeNulls()
  assertThat(stringBoxAdapter.fromJson("""{"data":null}""")).isEqualTo(Box<String?>(null))
  assertThat(stringBoxAdapter.toJson(Box<String?>(null))).isEqualTo("""{"data":null}""")
}
```

This fails, even thought the generic is bounded to `Any?`, a nullable type.
The workaround is to have `data class Box<out T>(val data: T?)`.

We need a Kotlin type resolver, anyway.

**Comment by reeshuai** [comment]
I also met the same problem.
     Caused by: java.lang.IllegalArgumentException: Expected a Class, ParameterizedType, or GenericArrayType, but <null> is of type null
                                                                        at com.squareup.moshi.Types.getRawType(Types.java:167)
                                                                        at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:83)
                                                                        at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:75)
                                                                        at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
                                                                        at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:184)
                                                                        at com.squareup.moshi.Moshi.adapter(Moshi.java:100)
                                                                        at com.squareup.moshi.Moshi.adapter(Moshi.java:62)

**Comment by NightlyNexus** [comment]
@reeshuai On Moshi 1.6.0?

**Comment by swankjesse** [comment]
Folding into this issue: https://github.com/square/moshi/issues/634
