### ISSUE TITLE
Codegen compilation error for uppercase property name

### ISSUE THREAD

**Issue by NightlyNexus** [square/moshi#574]
```kotlin
@JsonClass(generateAdapter = true)
class Foo {
  var BAR
    get() = 0
    set(BAR) {
    }
}
```
```
[ERROR] [kapt] An exception occurred: kotlin.KotlinNullPointerException
[ERROR] at com.squareup.moshi.kotlin.codegen.TargetProperty.getElement(TargetProperty.kt:54)
[ERROR] at com.squareup.moshi.kotlin.codegen.TargetProperty.jsonQualifiers(TargetProperty.kt:99)
[ERROR] at com.squareup.moshi.kotlin.codegen.TargetProperty.delegateKey(TargetProperty.kt:95)
[ERROR] at com.squareup.moshi.kotlin.codegen.PropertyGenerator.<init>(PropertyGenerator.kt:24)
[ERROR] at com.squareup.moshi.kotlin.codegen.TargetProperty.generator(TargetProperty.kt:92)
[ERROR] at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.adapterGenerator(JsonClassCodegenProcessor.kt:101)
[ERROR] at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.process(JsonClassCodegenProcessor.kt:88)
```

The TargetProperty field, setter, and getter are all null from my brief look. Changing "BAR" to "bar" works.

**Comment by NightlyNexus** [comment]
The problem is the `decapitalizeAsciiOnly` strategy.
