### ISSUE TITLE
Kotlin's Map<String,*>: Failed to construct the generated JsonAdapter

### ISSUE THREAD

**Issue by jansorg** [square/moshi#595]
Thanks for Moshi, I like it a lot with Kotlin!

I tried to use a type with a property of `Map<String, *>` or `Map<String, Comparable<*>>`. I this case Moshi fails with an exception about the adapter.

Using `Map<String, Object>` is working fine.

I had assumed that `Map<String,*>` is basically equivalent to `Map<String, Object>`, I'm not Kotlin expert, though.
How is this handled with Moshi in the best way?

Sample code:
```kotlin
import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi

@JsonClass(generateAdapter = true)
data class Dynamic1(val data: Map<String, Object>)

@JsonClass(generateAdapter = true)
data class Dynamic2(val data: Map<String, *>)

fun main(args: Array<String>) {
    val moshi = Moshi.Builder().build()

    println("Map<String,Object>:")
    println(moshi.adapter(Dynamic1::class.java).toJson(Dynamic1(mapOf("int" to 123, "float" to 123.0) as Map<String, Object>)))

    println("Map<String,*>:")
    println(moshi.adapter(Dynamic2::class.java).toJson(Dynamic2(mapOf("int" to 123, "float" to 123.0))))
}
```

Messages:
```
Map<String,Object>:
{"data":{"int":123,"float":123.0}}

Map<String,*>:
Exception in thread "main" java.lang.RuntimeException: Failed to construct the generated JsonAdapter for class eu.jadev.errorlog.server.store.Dynamic2
	at com.squareup.moshi.StandardJsonAdapters.generatedAdapter(StandardJsonAdapters.java:258)
	at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:62)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:130)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:68)
	at eu.jadev.errorlog.server.store.MoshiTestKt.main(MoshiTest.kt:22)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.squareup.moshi.StandardJsonAdapters.generatedAdapter(StandardJsonAdapters.java:246)
	... 4 more
Caused by: java.lang.IllegalArgumentException: No JsonAdapter for ? (with no annotations)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:147)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:64)
	at com.squareup.moshi.MapJsonAdapter.<init>(MapJsonAdapter.java:47)
	at com.squareup.moshi.MapJsonAdapter$1.create(MapJsonAdapter.java:38)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:130)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:64)
	at eu.jadev.errorlog.server.store.Dynamic2JsonAdapter.<init>(Dynamic2JsonAdapter.kt:19)
	... 9 more


```

**Comment by NightlyNexus** [comment]
`Map<String, Object>` or `Map<String, Any>` is correct.

(`*` is the same as `? extends Object`.) Is there a reason to use wildcards?

**Comment by jansorg** [comment]
@NightlyNexus Thanks! 
I've got confused after trying to use Comparable<*> as value type, I should've thought of `<Any>`, of course.

**Comment by leocorder** [comment]
@jansorg Is there any way to keep the keys in the result JSON when value in the map is null? I've tried with Map<String, Any?>, but the keys are removed from the JSON when the value is null.

**Comment by NightlyNexus** [comment]
JsonAdapter.serializeNulls
