### ISSUE TITLE
Is Kotlin's Unit supported?

### ISSUE THREAD

**Issue by sevar83** [square/moshi#598]
Hi, I use kotlin-codegen 1.6.0

`@PUT("company/login/email")
    fun loginEmail(@Body credential: UserCredentials): Single<Unit>`

And I got:

```
 Caused by: java.lang.IllegalArgumentException: **Platform class kotlin.Unit (with no annotations) requires explicit JsonAdapter to be registered**
07-16 19:12:36.809 7699-7699/com.citizenwatch.android W/System.err:     at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:60)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:130)
07-16 19:12:36.810 7699-7699/com.citizenwatch.android W/System.err:     at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:91)
07-16 19:12:36.811 7699-7699/com.citizenwatch.android W/System.err:     at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:330)
```

**Comment by JakeWharton** [comment]
It is, since it doesn't really represent anything that makes sense _inside_ of JSON.

For Retrofit, you probably want something [like this][1] instead.

 [1]: https://github.com/square/retrofit/issues/2329#issuecomment-301316873
