### ISSUE TITLE
Not respecting nullability when serializing using generated adapter

### ISSUE THREAD

**Issue by konmik** [square/moshi#634]
@JsonClass(generateAdapter = true)
    class Child()

    class Parent(val child: Child?)

    moshi.adapter(Parent::class.java).toJson(Parent(null))

Caused by: java.lang.NullPointerException: value was null! Wrap in .nullSafe() to write nullable values.
        at com.booking.pulse.features.donotdisturb.ChildJsonAdapter.toJson(ChildJsonAdapter.kt:42)
        at com.booking.pulse.features.donotdisturb.ChildJsonAdapter.toJson(ChildJsonAdapter.kt:13)
        at com.squareup.moshi.ClassJsonAdapter$FieldBinding.write(ClassJsonAdapter.java:203)
        at com.squareup.moshi.ClassJsonAdapter.toJson(ClassJsonAdapter.java:172)
        at com.squareup.moshi.JsonAdapter$2.toJson(JsonAdapter.java:144)
        at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:52)
        at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:58)

**Comment by NightlyNexus** [comment]
The adapter for Parent don't know about its property's nullability unless you install the reflective Kotlin adapter or generate a Kotlin adapter for Parent.

**Comment by konmik** [comment]
I understand this.

The issue is that parent's  runtime adapter makes assumption on child's adapter nullability. We should probably add an annotation to solve the issue, add default behavior or something like that.

**Comment by konmik** [comment]
Solution 1: `@JsonClass(generateAdapter = true, nullable = true)`

Solution 2: `@field:Json(name = "time_until", nullable = true)`

Solution 3: when generic serializer finds a generated adapter for a field it marks field as nullable by default.

**Comment by remcomokveld** [comment]
I am also running into this when trying to parse a `List<Parent?>`

I think creating all generatedAdapters with `nullSafe` would be okay for this right? if the child may not be null kotin will throw the NPE when the parent class' constructor is being called.

There is one problem with this approach, and that is that `List<Parent>` is no longer guaranteed to only contain non nulls, but I would think that that needs to be handled in special CollectionJsonAdapter for kotlin collections.

**Comment by remcomokveld** [comment]
The problem I am running into now is that I have a list which can contain null items.

With Kotlin's nullability features this should be possible to express by having 
```
@JsonClass(generateAdapter = true)
data class Item(val itemId: String)
```

Now let's say you have a graphql API, which gives this response

**Comment by swankjesse** [comment]
Actions to take here:

 * [ ] If we have a type like `List<String?>` we should permit null elements.
 * [ ] If we have a type like `List<String>` we should forbid null elements.

**Comment by schatzdesigns** [comment]
Any progress on this?

**Comment by ZacSweers** [comment]
No one is currently working on this

**Comment by dkonurov** [comment]
@ZacSweers @swankjesse may be it's bad idea but I add annotations for nullable and nonnull values in collectionAdapter and support it and add support nonnull or nullable values for kotlin json adapter and codegen in kotlin. IэMay be this is bad idea pls tell me :-)  May be need support annotation for array and map?

**Comment by jkaan** [comment]
Hey guys :). I could try to make a PR for this. Basically it should just be supported, right? No additional annotations or anything, I assume?

**Comment by swankjesse** [comment]
You're welcome to try but I believe it's difficult to do without major changes to Moshi’s internal type model.

**Comment by jkaan** [comment]
Okay, that's good to know. I guess this is not a good issue then to start working on to get acquainted with Moshi :).

**Comment by dkonurov** [comment]
@swankjesse what do you think about add Nullable Type and NonNull Type in Moshi, because Java doesn't know any more about Null safety. as @ZacSweers said we can wrap Kotlin Type but Java doesn't know nothing about KType and cannot resolve this. I think we can resolve in Java and add Wrap Type like OptionalType or NullableType in Kotlin.

**Comment by ZacSweers** [comment]
> said we can wrap Kotlin Type but Java doesn't know nothing about KType and cannot resolve this

I meant if a kotlin rewrite happens, KType would become the internal type mechanism. Java behavior would remain unchanged because Java has no notion of nullability in its types. We could possible parse Nullable type parameter annotations but they would need to be runtime retained for reflection.

I think it could work to expose new collection/map adapter APIs in Types that custom JsonAdapter.Factory or generated adapter implementations could use if they can understand nullability about a target type. That approach works probably today without any overly invasive changes to moshi’s core type machinery.

**Comment by dkonurov** [comment]
Hm... If I correct understood idea we can save Nullable from Kotlin but:

1. Need Support Nullable or NonNull annotation for Java

**Comment by dkonurov** [comment]
I think many times about this issue, but KType must be used inside method Util.reslove, because some internal type can be annotated  nullable like field inside class, and generic type can be annotated nullable like generic type by class.  Than we must create new Type, but It will be similar to this pull request: https://github.com/square/moshi/pull/1139 :-(

**Comment by ZacSweers** [comment]
We're coverting to kotlin and that may lend us more information

**Comment by dkonurov** [comment]
Yeah I saw it. I create some branch with new Type. Could you review me? https://github.com/square/moshi/pull/1322 But now doesn't work AdapterMethodsFactory in Kotlin. I will fix it. This branch has problem with name of type, I think :-)

**Comment by dkonurov** [comment]
What do you think about add KotlinType like wrap usual type and save nullable infromation? ([https://github.com/square/moshi/pull/1322/files] like this)  but if it add this type should we detect difference between adapters:
`class NoNullAdapter {
  
  fun fromJson(json: String): Int {
    //....
  } 
}

class NullableAdapter {

  fun fromJson(json: String): Int? {
    //....
  }
}
`
I think it's break changes :-(

**Comment by PierluigiFimiano** [comment]
Hi, I have found this solution:

`
inline fun <reified T> getType(): Type = T::class.java

val type = Types.newParameterizedType(List::class.java, getType<Int?>())
val adapter: JsonAdapter<List<Int?>> = mocha.adapter(type)

val json = "[1, 2, null, 5]"
val list = adapter.fromJson(json)

`

Let me know if there are some problems, for me it is working.
