### ISSUE TITLE
KotlinReflectionInternalError in GeneratedAdaptersTest

### ISSUE THREAD

**Issue by swankjesse** [square/moshi#662]
This test has been flaking. Something is broken when we try to use Kotlin reflection in this test.
```
com.squareup.moshi.kotlin.codgen.GeneratedAdaptersTestTests run: 49, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 0.667 sec <<< FAILURE!qualifiedAdaptersAreShared(com.squareup.moshi.kotlin.codgen.GeneratedAdaptersTest)  Time elapsed: 0.213 sec  <<< ERROR!kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Unresolved class: class com.squareup.moshi.JsonAdapter$2
	at kotlin.reflect.jvm.internal.KClassImpl.reportUnresolvedClass(KClassImpl.kt:301)
	at kotlin.reflect.jvm.internal.KClassImpl.access$reportUnresolvedClass(KClassImpl.kt:42)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:52)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:43)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt)
	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:172)
	at kotlin.reflect.jvm.internal.KClassImpl.getMemberScope$kotlin_reflection(KClassImpl.kt:178)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:152)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:43)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDeclaredNonStaticMembers(KClassImpl.kt)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:161)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:43)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getAllNonStaticMembers(KClassImpl.kt)
	at kotlin.reflect.full.KClasses.getMemberProperties(KClasses.kt:149)
	at com.squareup.moshi.kotlin.codgen.GeneratedAdaptersTest.qualifiedAdaptersAreShared(GeneratedAdaptersTest.kt:872)
```

**Comment by swankjesse** [comment]
... it’s caused by a newly introduced call to `.nullSafe()` that causes it to return a non-Kotlin class.
