### ISSUE TITLE
Kotlin  proguard ExceptionInInitializerError

### ISSUE THREAD

**Issue by debughao** [square/moshi#669]
Rejecting re-init on previously-failed class java.lang.Class<kotlin.reflect.jvm.internal.impl.builtins.d>: java.lang.ExceptionInInitializerError: 
        at void kotlin.reflect.jvm.internal.impl.builtins.d.<clinit>() (BuiltInsLoader.kt:-1)
        at void kotlin.reflect.jvm.internal.impl.builtins.l.va() (KotlinBuiltIns.java:150)
        at void kotlin.reflect.jvm.internal.impl.d.b.<init>(kotlin.reflect.jvm.internal.impl.h.i, boolean) (JvmBuiltIns.kt:56)
        at void kotlin.reflect.jvm.internal.impl.d.b.<init>(kotlin.reflect.jvm.internal.impl.h.i, boolean, int, kotlin.e.b.g) (JvmBuiltIns.kt:31)
        at kotlin.reflect.jvm.internal.a.j kotlin.reflect.jvm.internal.a.j$a.b(java.lang.ClassLoader) (RuntimeModuleData.kt:54)
        at kotlin.reflect.jvm.internal.a.j kotlin.reflect.jvm.internal.ad.V(java.lang.Class) (moduleByClassLoader.kt:58)
        at kotlin.reflect.jvm.internal.a.j kotlin.reflect.jvm.internal.m$b$a.invoke() (KDeclarationContainerImpl.kt:35)
        at java.lang.Object kotlin.reflect.jvm.internal.m$b$a.invoke() (KDeclarationContainerImpl.kt:32)
        at java.lang.Object kotlin.reflect.jvm.internal.ae$a.invoke() (ReflectProperties.java:93)
        at java.lang.Object kotlin.reflect.jvm.internal.ae$c.j(java.lang.Object, java.lang.Object) (ReflectProperties.java:32)

**Comment by debughao** [comment]
@JakeWharton

**Comment by JakeWharton** [comment]
Please provide a full sample that demonstrates the problem as there's no information provided to discern any kind of cause.

**Comment by debughao** [comment]
Has been resolved by adding: -keep class kotlin.reflect.**

**Comment by JakeWharton** [comment]
That is not a solution. It's the same effect as disabling ProGuard.

**Comment by linzhengloser** [comment]
Hello, I am using Moshi and Retrofit to run an error after confusion, the error message is as follows:

```
 java.lang.ExceptionInInitializerError
        at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader.<clinit>(SourceFile)
        at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(SourceFile:150)
        at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.<init>(SourceFile:56)
        at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.<init>(SourceFile:31)
                                                                 <init>
        at kotlin.reflect.jvm.internal.components.RuntimeModuleData$Companion.create(SourceFile:54)
        at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(SourceFile:58)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(SourceFile:35)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(SourceFile:32)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(SourceFile:93)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(SourceFile:32)
                                                             invoke
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(SourceFile)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(SourceFile:46)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(SourceFile:43)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(SourceFile:93)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(SourceFile:32)
                                                             invoke
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(SourceFile)
                                                       calculateLocalClassName
                                                       access$calculateLocalClassName
        at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(SourceFile:172)
        at kotlin.reflect.jvm.internal.KClassImpl.isAbstract(SourceFile:250)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(SourceFile:184)
        at com.squareup.moshi.Moshi.adapter(SourceFile:130)
        at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(SourceFile:91)
        at retrofit2.Retrofit.nextResponseBodyConverter(SourceFile:330)
        at retrofit2.Retrofit.responseBodyConverter(SourceFile:313)
        at retrofit2.ServiceMethod$Builder.createResponseConverter(SourceFile:739)
        at retrofit2.ServiceMethod$Builder.build(SourceFile:172)
        at retrofit2.Retrofit.loadServiceMethod(SourceFile:170)
        at retrofit2.Retrofit$1.invoke(SourceFile:147)
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
        at $Proxy0.a(Unknown Source)
        at com.heyooo.heymail.presenter.SignInPresenter.signInRequest(SourceFile:28)
        at com.heyooo.heymail.ui.fragment.SignInFragment$onViewCreated$5.onClick(SourceFile:123)
        at android.view.View.performClick(View.java:5275)
        at android.view.View$PerformClick.run(View.java:21559)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
```

Moshi's obfuscated configuration has been added

![image](https://user-images.githubusercontent.com/12724989/46185070-09b95e80-c30b-11e8-9da0-05d3710c3c22.png)


help me！！！

**Comment by linzhengloser** [comment]
Update the error message after Kotlin-Moshi 1.7.0

```
    java.lang.IllegalArgumentException: Unable to create converter for class com.heyooo.heymail.model.Token
        for method d.a
        at retrofit2.ServiceMethod$Builder.methodError(SourceFile:755)
        at retrofit2.ServiceMethod$Builder.createResponseConverter(SourceFile:741)
        at retrofit2.ServiceMethod$Builder.build(SourceFile:172)
        at retrofit2.Retrofit.loadServiceMethod(SourceFile:170)
        at retrofit2.Retrofit$1.invoke(SourceFile:147)
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
        at $Proxy0.a(Unknown Source)
        at com.heyooo.heymail.presenter.SignInPresenter.signInRequest(SourceFile:28)
        at com.heyooo.heymail.ui.fragment.SignInFragment$onViewCreated$5.onClick(SourceFile:123)
        at android.view.View.performClick(View.java:5275)
        at android.view.View$PerformClick.run(View.java:21559)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5856)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
     Caused by: java.lang.IllegalStateException: No BuiltInsLoader implementation was found. Please ensure that the META-INF/services/ is not stripped from your application and that the Java virtual machine is not running under a security manager
        at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion$Instance$2.invoke(SourceFile:39)
        at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion$Instance$2.invoke(SourceFile:36)
        at kotlin.SafePublicationLazyImpl.getValue(SourceFile:107)
        at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion.getInstance(SourceFile)
        at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(SourceFile:172)
        at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.<init>(SourceFile:43)
        at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.<init>(SourceFile:18)
                                                                     <init>
        at kotlin.reflect.jvm.internal.components.RuntimeModuleData$Companion.create(SourceFile:58)
        at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(SourceFile:58)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(SourceFile:37)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(SourceFile:34)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(SourceFile:92)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(SourceFile:31)
                                                             invoke
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(SourceFile)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(SourceFile:47)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(SourceFile:44)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(SourceFile:92)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(SourceFile:31)
                                                             invoke
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(SourceFile)
                                                       calculateLocalClassName
                                                       access$calculateLocalClassName
                                                       access$getInheritedNonStaticMembers$p
        at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(SourceFile:171)
        at kotlin.reflect.jvm.internal.KClassImpl.isAbstract(SourceFile:252)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(SourceFile:184)
        at com.squareup.moshi.Moshi.adapter(SourceFile:142)
        at com.squareup.moshi.Moshi.adapter(SourceFile:94)
        at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(SourceFile:91)
        at retrofit2.Retrofit.nextResponseBodyConverter(SourceFile:330)
        at retrofit2.Retrofit.responseBodyConverter(SourceFile:313)
        at retrofit2.ServiceMethod$Builder.createResponseConverter(SourceFile:739)
        at e.o$a.a(SourceFile:172)?
        at e.n.a(SourceFile:170)?
        at e.n$1.invoke(SourceFile:147)?
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)?
        at $Proxy0.a(Unknown Source)?
        at com.heyooo.heymail.d.a.a(SourceFile:28)?
        at com.heyooo.heymail.ui.b.a$f.onClick(SourceFile:123)?
        at android.view.View.performClick(View.java:5275)?
        at android.view.View$PerformClick.run(View.java:21559)?
        at android.os.Handler.handleCallback(Handler.java:815)?
        at android.os.Handler.dispatchMessage(Handler.java:104)?
        at android.os.Looper.loop(Looper.java:207)?
        at android.app.ActivityThread.main(ActivityThread.java:5856)?
        at java.lang.reflect.Method.invoke(Native Method)?
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)?
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)?

```

**Comment by linzhengloser** [comment]
Is it this one?

![image](https://user-images.githubusercontent.com/12724989/46186525-b1d22600-c311-11e8-9864-93fff6ddc90b.png)

**Comment by JakeWharton** [comment]
No there should be a META-INF/services/ folder with a file named the same
as that long class. There should also be a class present inside the dex
file with the same name as the contents of that META-INF file.

**Comment by linzhengloser** [comment]
![image](https://user-images.githubusercontent.com/12724989/46186644-3de44d80-c312-11e8-9775-810d616b4f75.png)

![image](https://user-images.githubusercontent.com/12724989/46186649-450b5b80-c312-11e8-934e-656bdb3604da.png)

this one？

**Comment by JakeWharton** [comment]
Yes. The second one. Now if you click on the classes.dex can you navigate
to that kotlin.reflect.jvm.... class or is it missing?

**Comment by linzhengloser** [comment]
![image](https://user-images.githubusercontent.com/12724989/46186855-5ef96e00-c313-11e8-9ac5-7f76cb5770c5.png)

Didn't find it, which one is my package below?

**Comment by JakeWharton** [comment]
Based on that it looks like it's being obfuscated. Are you sure you have the `-keep` rule for it and it's being used by ProGuard?

**Comment by linzhengloser** [comment]
Right, I used Moshi 1.5.0 Kotlin-Moshi with 1.7.0.
Is it related to this?

this is my Proguard.pro

```
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

-dontwarn javax.annotation.**
-dontwarn org.codehaus.mojo.animal_sniffer.*
-dontwarn okhttp3.internal.platform.ConscryptPlatform
-dontwarn kotlin.Unit
-dontwarn retrofit2.-KotlinExtensions
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
-dontwarn java.awt.**
-dontwarn java.beans.Beans
-dontwarn javax.security.**
-dontwarn javax.naming.**
-dontwarn java.awt.**,javax.activation.**,java.beans.**
-dontwarn org.codehaus.mojo.animal_sniffer.*
-ignorewarnings

-keepattributes *Annotation*
-keepattributes Signature, InnerClasses

-keepclassmembers class fqcn.of.javascript.interface.for.webview {
   public *;
}

-keepclassmembers class * extends andrBuiltInsLoaderImploid.webkit.webViewClient {
    public void *(android.webkit.WebView, java.lang.String, android.graphics.Bitmap);
    public boolean *(android.webkit.WebView, java.lang.String);
}

-keepclassmembers,allowshrinking,allowobfuscation interface * {
    @retrofit2.http.* <methods>;
}

-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

-keepclassmembers class * {
    @org.greenrobot.eventbus.Subscribe <methods>;
}

-keep enum org.greenrobot.eventbus.ThreadMode { *; }

-keepclasseswithmembers class * {
    @com.squareup.moshi.* <methods>;
}

-keep @com.squareup.moshi.JsonQualifier interface *

-keepclassmembernames @com.squareup.moshi.JsonClass class * extends java.lang.Enum {
    <fields>;
}

-keepnames @com.squareup.moshi.JsonClass class *

-if @com.squareup.moshi.JsonClass class *
-keep class <1>JsonAdapter {
    <init>(...);
    <fields>;
}

-keep class kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoaderImpl

-keepclassmembers class kotlin.Metadata {
    public <methods>;
}

-keep class javax.** {*;}
-keep class com.sun.** {*;}
-keep class myjava.** {*;}
-keep class org.apache.harmony.** {*;}
-keep public class Mail {*;}

-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}

# 友盟相关
-dontwarn com.taobao.**
-dontwarn anet.channel.**
-dontwarn anetwork.channel.**
-dontwarn org.android.**
-dontwarn org.apache.thrift.**
-dontwarn com.xiaomi.**
-dontwarn com.huawei.**
-dontwarn com.meizu.**

-keep class com.taobao.** {*;}
-keep class org.android.** {*;}
-keep class anet.channel.** {*;}
-keep class com.umeng.** {*;}
-keep class com.xiaomi.** {*;}
-keep class com.huawei.** {*;}
-keep class com.meizu.** {*;}
-keep class org.apache.thrift.** {*;}

-keep class com.alibaba.sdk.android.**{*;}
-keep class com.ut.**{*;}
-keep class com.ta.**{*;}

-keep public class **.R$*{
   public static final int *;
}

#（可选）避免Log打印输出
-assumenosideeffects class android.util.Log {
   public static *** v(...);
   public static *** d(...);
   public static *** i(...);
   public static *** w(...);
}

```

**Comment by linzhengloser** [comment]
i update  -keep class kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoaderImpl
to -keep class kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins.BuiltInsLoaderImpl

![image](https://user-images.githubusercontent.com/12724989/46187375-e1832d00-c315-11e8-8c12-2338b8110dd9.png)

But still report an error

**Comment by linzhengloser** [comment]
i use proguard rule ``` -keep public class kotlin.reflect.jvm.internal.impl.** { public *; } ```

Although the operation does not report an error, the objects parsed using Moshi are default values.

![image](https://user-images.githubusercontent.com/12724989/46201810-a863b080-c347-11e8-89a5-2b7e98afdceb.png)

**Comment by linzhengloser** [comment]
Exception information：

```
09-28 19:10:38.432 22504-22504/? E/b: kotlin.reflect.jvm.internal.KotlinReflectionInternalError: This callable does not support a default call: public constructor Token(uid: kotlin.String, @com.c.a.e accessToken: kotlin.String, @com.c.a.e refreshToken: kotlin.String, expire: kotlin.Long, saveDate: kotlin.Long = ...) defined in com.heyooo.heymail.model.Token[DeserializedClassConstructorDescriptor@627037e]
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod(SourceFile:153)
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(SourceFile:110)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(SourceFile:103)
        at com.squareup.moshi.JsonAdapter$2.fromJson(SourceFile:137)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(SourceFile:45)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(SourceFile:27)
        at retrofit2.ServiceMethod.toResponse(SourceFile:122)
        at retrofit2.OkHttpCall.parseResponse(SourceFile:217)
        at retrofit2.OkHttpCall.execute(SourceFile:180)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(SourceFile:42)
        at io.reactivex.Observable.subscribe(SourceFile:12005)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(SourceFile:34)
        at io.reactivex.Observable.subscribe(SourceFile:12005)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(SourceFile:96)
        at io.reactivex.Scheduler$DisposeTask.run(SourceFile:571)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

```

**Comment by swankjesse** [comment]
Unclear what action to take here.
