### ISSUE TITLE
IllegalStateException: Type adapter isn't ready

### ISSUE THREAD

**Issue by Tolriq** [square/moshi#679]
Got some very very very rare exception (see below).

Any idea of the cause and possible workaround ?
```
Fatal Exception: java.lang.IllegalStateException: Type adapter isn't ready
       at com.squareup.moshi.Moshi$DeferredAdapter.toJson(Moshi.java:272)
       at com.squareup.moshi.MapJsonAdapter.toJson(MapJsonAdapter.java:1057)
       at com.squareup.moshi.JsonAdapter$2.toJson(JsonAdapter.java:144)
       at com.squareup.moshi.StandardJsonAdapters$ObjectJsonAdapter.toJson(StandardJsonAdapters.java:367)
       at com.squareup.moshi.JsonAdapter$2.toJson(JsonAdapter.java:144)
       at com.squareup.moshi.ClassJsonAdapter.com.squareup.moshi.ClassJsonAdapter$FieldBinding.write(ClassJsonAdapter.java:1203)
       at com.squareup.moshi.JsonAdapter$2.toJson(JsonAdapter.java:144)
       at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:52)
       at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:58)
       at com.mediacenters.kodi.api.KodiApi$JsonRpcCall.getBody(KodiApi.kt:71)
       at com.mediacenters.kodi.api.KodiApiConnection$asynchronousCall$1$$special$$inlined$forEach$lambda$1.invoke(KodiApiConnection.kt:1069)
       at kotlin.text.StringsKt__StringBuilderKt.appendElement(StringBuilder.kt:58)
       at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:2195)
       at com.mediacenters.kodi.api.KodiApiConnection$asynchronousCall$1.kotlin.collections.CollectionsKt___CollectionsKt.joinTo$default$1296cf06(KodiApiConnection.kt:5189)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by NightlyNexus** [comment]
Post the code that caused the exception?

**Comment by Tolriq** [comment]
Ultra basic stuff.

```
return moshi.adapter(JsonRPC::class.java).toJson(jsonRPC)
```

jsonRPC is a basic kotlin class 
```
class JsonRPC {
    var id = (Math.random() * 1000).toInt().toLong()
    val jsonrpc = "2.0"
    var method: String? = null
    var params: Any? = null
}
```

Moshi init
```
protected val moshi: Moshi by lazy { Moshi.Builder().add(JsonErrorHandlingFactory()).build() }
```

See https://github.com/square/moshi/issues/295#issuecomment-299636385 for what the factory provides (was updated to Kotlin and more cases but exact same concept).

5 phone brands and Android 8 and 5, but with just 10 crash this is not representative and I'm not sure this is tied to OS / Hardware.

This is called hundreds of thousands time per day and I go 10 crash on the last 90 days in Crashlytics. So very very rare, but since I'm now at 99,99% crash free session I'm trying to see if I can get the 100% with rounding :)

**Comment by swankjesse** [comment]
My guess is we're not thread safe with deferred adapters. Can fix!
