### ISSUE TITLE
R8 triggers VerifyError on KitKat devices

### ISSUE THREAD

**Issue by bulatgaleev** [square/moshi#803]
AGP **3.3.0**
Kotlin **1.3.20**
Moshi **1.8.0**
minSdk **19**

On KitKat devices I'm getting this runtime error on first retrofit call.

```
W/dalvikvm: DexOpt: method is in an interface
I/dalvikvm: Could not find method java.util.Map.getOrDefault, referenced from method com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter$IndexedParameterMap.getOrDefault
W/dalvikvm: VFY: unable to resolve virtual method 50960: Ljava/util/Map;.getOrDefault (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
W/dalvikvm: VFY:  rejecting opcode 0x6f at 0x0000
W/dalvikvm: VFY:  rejected Lcom/squareup/moshi/kotlin/reflect/KotlinJsonAdapter$IndexedParameterMap;.getOrDefault (Lkotlin/reflect/KParameter;Ljava/lang/Object;)Ljava/lang/Object;
W/dalvikvm: Verifier rejected class Lcom/squareup/moshi/kotlin/reflect/KotlinJsonAdapter$IndexedParameterMap;
```

Even is i disable R8 and force latest proguard version to be used and **android.proguard.enableRulesExtraction=false** i get this compile error:

```
Failed to notify project evaluation listener.
  proguard.ConfigurationParser.parseClassSpecificationArguments()Lproguard/ClassSpecification;
```

Did i miss something?

**Comment by bulatgaleev** [comment]
As a workaround i've used **LinkedHashMap** instead of **IndexedParameterMap** (for KitKat)

**Comment by JakeWharton** [comment]
Seems like a Kotlin bug. I don't know why its generating those bridge methods for `getOrDefault` in the classsfile.

**Comment by bulatgaleev** [comment]
@JakeWharton raised [ticket](https://youtrack.jetbrains.com/issue/KT-29668). You can close this issue here.

**Comment by Drjacky** [comment]
Same problem here:

```
io.reactivex.exceptions.UndeliverableException: java.lang.VerifyError: com/squareup/moshi/c/a/a$b
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.VerifyError: com/squareup/moshi/c/a/a$b
        at com.squareup.moshi.c.a.a.a(KotlinJsonAdapter.kt:103)
        at com.squareup.moshi.p.a(JsonAdapter.java:137)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12030)
        at retrofit2.adapter.rxjava2.ResultObservable.subscribeActual(ResultObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12030)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
```

**Comment by almozavr** [comment]
> As a workaround i've used **LinkedHashMap** instead of **IndexedParameterMap** (for KitKat)

I encounter the same issue (suddenly) – could you help what do you mean by "using instead"? I thought this class is used somewhere internally 🤔

**Comment by Drjacky** [comment]
@bulatgaleev Would you please answer to the above question? 🙏

**Comment by InnoLuke** [comment]
Any update on this bug?

**Comment by ZacSweers** [comment]
Hey folks, as mentioned above this appears to be a Kotlin issue. Please pursue this in the linked ticket above

**Comment by vladimirov001** [comment]
There is simple fix, please approve pull request:

https://github.com/square/moshi/pull/1168
