### ISSUE TITLE
Unused @ToJson required to be present

### ISSUE THREAD

**Issue by aahlenst** [square/moshi#817]
As far as I understand, it is unnecessary to supply a `@ToJson` annotation if I'm only mapping from JSON to Java/Kotlin. But somehow, the following test breaks if I omit a `@ToJson` method in the adapter definition:

```
class SomeEntityMoshiAdapterTest {

    private val moshi = Moshi.Builder()
        .add(OtherEntityMoshiAdapter())
        .add(SomeEntityMoshiAdapter())
        .build()

    private val adapter = moshi.adapter(SomeEntity::class.java)

    @Test
    fun testFromJson() {
        val json = """
            {
              "otherEntity": {
                "name": "foo"
              }
            }
        """.trimIndent()

        val entity = adapter.fromJson(json)

        assertNotNull(entity)
    }
}
```

The definition of `SomeEntity`:

```
@Entity
class SomeEntity {
    @Id
    var id: Long = 0

    var otherEntity: ToOne<OtherEntity> = ToOne(this, SomeEntity_.otherEntity)

}
```

The definition of the adapter:

```
class SomeEntityMoshiAdapter {

    private val otherEntityAdapter = OtherEntityMoshiAdapter()

    @FromJson
    fun fromJson(json: SomeEntityJson): SomeEntity {
        val entity = SomeEntity()
        entity.otherEntity.target = otherEntityAdapter.fromJson(json.otherEntity)
        return entity
    }
}
```

As soon as I add a `@ToJson` method, everything's fine:

```
@ToJson
fun toJson(entity: SomeEntity): SomeEntityJson {
    throw NotImplementedError("Required to make test pass")
}
```

The full exception:

```
java.lang.IllegalArgumentException: No @ToJson adapter for class com.example.entity.SomeEntity (with no annotations)

	at com.squareup.moshi.AdapterMethodsFactory.create(AdapterMethodsFactory.java:56)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:71)
	at com.example.moshi.SomeEntityMoshiAdapterTest.<init>(SomeEntityMoshiAdapterTest.kt:15)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:453)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:62)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeTestClassConstructor(ClassTestDescriptor.java:345)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:290)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:281)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateAndPostProcessTestInstance(ClassTestDescriptor.java:269)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstancesProvider$2(ClassTestDescriptor.java:259)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstancesProvider$3(ClassTestDescriptor.java:263)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstancesProvider$4(ClassTestDescriptor.java:262)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:98)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:97)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:75)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: No JsonAdapter for io.objectbox.EntityInfo<SOURCE> (with no annotations)
for io.objectbox.EntityInfo<SOURCE> sourceInfo
for class io.objectbox.relation.RelationInfo relationInfo
for io.objectbox.relation.ToOne<com.example.entity.OtherEntity> otherEntity
for class com.example.entity.SomeEntity
	at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:348)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:149)
	at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:99)
	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:82)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
	at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:99)
	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:82)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
	at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:99)
	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:82)
	at com.squareup.moshi.Moshi.nextAdapter(Moshi.java:168)
	at com.squareup.moshi.AdapterMethodsFactory.create(AdapterMethodsFactory.java:52)
	... 58 more
Caused by: java.lang.IllegalArgumentException: No JsonAdapter for io.objectbox.EntityInfo<SOURCE> (with no annotations)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:147)
	... 68 more
```

As you can see from the stacktrace, the problem are missing adapters for some code generated by [ObjectBox](https://objectbox.io) that should not be necessary in my opinion. Unfortunately, I wasn't able to reproduce the problem without ObjectBox, but there's a minimal sample project that you can play around with: https://github.com/aahlenst/moshi-objectbox-tojson.

**Comment by swankjesse** [comment]
We require it because we insist that your JSON adapters can do both encoding and decoding. I like it ’cause it makes it easier to write tests.

**Comment by aahlenst** [comment]
Sorry if this turns into a usage question. Now I'm confused. If JSON adapters should be able to do both (which I'm totally fine with), why does Moshi not complain in this case here? Where's the difference?

```
class MissingToJsonTest {

    class OuterClass {
        var inner: InnerClass? = null
    }

    class InnerClass {
        var name: String? = null
    }

    data class OuterClassJson(
        val inner: InnerClassJson
    )

    data class InnerClassJson(
        val name: String
    )

    class OuterClassMoshiAdapter {
        @FromJson
        fun fromJson(json: OuterClassJson): OuterClass {
            val inner = InnerClass()
            inner.name = json.inner.name

            val outer = OuterClass()
            outer.inner = inner
            return outer
        }
    }

    private val moshi = Moshi.Builder()
        .add(OuterClassMoshiAdapter())
        .build()

    private val adapter = moshi.adapter(OuterClass::class.java)

    @Test
    fun noToJson() {
        val json = """
            {
              "inner": {
                "name": "foo"
              }
            }
        """.trimIndent()

        val outer = adapter.fromJson(json)

        assertNotNull(outer)
        assertEquals("foo", outer?.inner?.name)
    }
}
```

**Comment by NightlyNexus** [comment]
if there's another adapter available for the type (usually the default Java reflection adapter), Moshi will delegate to it.
if there's not (because of JsonQualifiers, a platform type contained somewhere in the type, etc.), a working `@ToJson` is required.

**Comment by aahlenst** [comment]
This makes sense. Thanks a lot.
