### ISSUE TITLE
java.lang.NoSuchMethodError crash when creating  KotlinJsonAdapter

### ISSUE THREAD

**Issue by catsynth** [square/moshi#826]
I am getting a crash while creating/adding a KotlinJasonAdapter.  

```
  Process: com.catsynthappwerx.highways, PID: 14039
    java.lang.NoSuchMethodError: No static method isPlatformType(Ljava/lang/Class;)Z in class Lcom/squareup/moshi/ClassJsonAdapter; or its super classes (declaration of 'com.squareup.moshi.ClassJsonAdapter' appears in /data/app/com.catsynthappwerx.highways-tG5fEZ6ndjF4CbxP9I7KxQ==/split_lib_dependencies_apk.apk:classes3.dex)
        at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:158)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:67)
        at com.squareup.moshi.MapJsonAdapter.<init>(MapJsonAdapter.java:47)
        at com.squareup.moshi.MapJsonAdapter$1.create(MapJsonAdapter.java:38)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:67)
```

My current configuration for moshi and other Square libraries.

```
    implementation 'com.squareup.okhttp3:okhttp:3.13.1'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.squareup.moshi:moshi:1.8.0'
    implementation 'com.squareup.moshi:moshi-kotlin:1.5.0'
    implementation 'com.squareup.moshi:moshi-adapters:1.5.0'
    implementation 'com.squareup.retrofit2:converter-moshi:2.5.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.5.0'
```

Please advise.
Thanks
-Amanda

**Comment by NightlyNexus** [comment]
Please use version 1.8.0 for moshi-kotlin and moshi-adapters.

**Comment by catsynth** [comment]
Yes, that worked.  Thanks!
(I'm wondering why Android Studio did mention an update for those the way it dod for the main moshi module?)
