### ISSUE TITLE
JsonQualifier didn't work with HexColor string

### ISSUE THREAD

**Issue by leagmain** [square/moshi#828]
I got exception when I use JsonQualifier to parse my Hex color.

`W/System.err: com.squareup.moshi.JsonDataException: Expected an int but was #FFFFFFFF at path $.data[1].elements[1].foreground
W/System.err:     at com.squareup.moshi.JsonUtf8Reader.nextInt(JsonUtf8Reader.java:921)
W/System.err:     at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:173)
W/System.err:     at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:171)
W/System.err:     at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
W/System.err:     at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:194)
W/System.err:     at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:156)
W/System.err:     at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
W/System.err:     at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
W/System.err:     at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
W/System.err:     at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
W/System.err:     at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:194)
W/System.err:     at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:156)
W/System.err:     at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
W/System.err:     at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
W/System.err:     at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
W/System.err:     at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
W/System.err:     at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:194)
W/System.err:     at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:156)
W/System.err:     at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
W/System.err:     at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
W/System.err:     at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
W/System.err:     at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223)
W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
W/System.err:     at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:92)`

Data class:
```
data class Element {
    @ColorQualifier var color: Int?=null
}
```

ColorQualifier
```
@Retention(AnnotationRetention.RUNTIME)
@JsonQualifier
annotation class ColorQualifier
```

And adapter
```
object ColorTypeAdapter {
    @ToJson
    fun toJson(@ColorQualifier argb: Int): String {
        return String.format("#%02X%02X%02X%02X", argb.red, argb.green, argb.blue, argb.alpha)
    }

    @FromJson
    @ColorQualifier
    fun fromJson(rgba: String): Int {
        @ColorInt
        val rgbaColor = Color.parseColor(rgba)
        return Color.argb(rgbaColor.blue, rgbaColor.alpha, rgbaColor.red, rgbaColor.green)
    }
}
```

*how to handle this exception?*

**Comment by leagmain** [comment]
sorry for the noisy, I figured out how to solve this issue.

```
object ColorTypeAdapter {
    @ToJson
    fun toJson(@ColorQualifier argb: Int): String {
        return String.format("#%02X%02X%02X%02X", argb.red, argb.green, argb.blue, argb.alpha)
    }

    @FromJson
    @Throws(Exception::class)
    @ColorQualifier
    fun fromJson(jsonReader: JsonReader): Int {
        val dd = jsonReader.peek()
        when (dd) {
            JsonReader.Token.STRING -> {
                @ColorInt
                val rgbaColor = Color.parseColor(jsonReader.nextString())
                return Color.argb(rgbaColor.blue, rgbaColor.alpha, rgbaColor.red, rgbaColor.green)
            }
            else -> {
                jsonReader.skipValue()
                return Color.BLACK
            }
        }
    }
}
```
