### ISSUE TITLE
Can't convert to Kotlin ULong

### ISSUE THREAD

**Issue by andrewtoth** [square/moshi#832]
Moshi conflates `ULong` with `Long`. However, trying to convert using a JsonQualifier and custom adapter:
```
class ULongAdapter {
    @FromJson @ToULong
    fun fromJson(ulong: String): ULong = ulong.toULong()

    @ToJson
    fun toJson(@ToULong ulong: ULong): String = ulong.toString()
}
```
gets an exception `java.lang.IllegalArgumentException: object is not an instance of declaring class`.

**Comment by NightlyNexus** [comment]
Can you post the stacktrace and the code to reproduce?

**Comment by andrewtoth** [comment]
```
data class LongClass(@ToULong val ulong: ULong)

val moshi = Moshi.Builder().add(ULongAdapter()).add(KotlinJsonAdapterFactory()).build()
val adapter = moshi.adapter(LongClass::class.java)
val json = adapter.toJson(LongClass(1UL))
```
```
argument type mismatch
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.squareup.moshi.AdapterMethodsFactory$AdapterMethod.invoke(AdapterMethodsFactory.java:335)
	at com.squareup.moshi.AdapterMethodsFactory$3.toJson(AdapterMethodsFactory.java:188)
	at com.squareup.moshi.AdapterMethodsFactory$1.toJson(AdapterMethodsFactory.java:73)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.toJson(KotlinJsonAdapter.kt:124)
	at com.squareup.moshi.JsonAdapter$2.toJson(JsonAdapter.java:144)
	at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:52)
	at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:58)
```

**Comment by ZacSweers** [comment]
Moshi doesn’t support inline classes yet since its an experimental feature.

**Comment by andrewtoth** [comment]
@ZacSweers Is ULong implemented as an inline class?

**Comment by JakeWharton** [comment]
Ues

**Comment by JakeWharton** [comment]
Also yes

**Comment by andrewtoth** [comment]
Ok will circle back when inline classes are no longer experimental.

**Comment by jpmeijers** [comment]
I'm hitting the same issue. I tried registering an explicit adapter for ULong and UByte, but even with them added to the builder I get this error. Is there no workaround for this?

```
2021-01-02 11:18:05.173 31135-32461/<REDACTED> E/AndroidRuntime: FATAL EXCEPTION: Thread-1151
    Process: <REDACTED>, PID: 31135
    java.lang.IllegalArgumentException: Platform class kotlin.ULong requires explicit JsonAdapter to be registered
    for class kotlin.ULong Bandwidth
    for class <REDACTED>
        at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:352)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:153)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:256)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:141)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:101)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:75)
        ...
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
     Caused by: java.lang.IllegalArgumentException: Platform class kotlin.ULong requires explicit JsonAdapter to be registered
        at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:72)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:141)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:256) 
        at com.squareup.moshi.Moshi.adapter(Moshi.java:141) 
        at com.squareup.moshi.Moshi.adapter(Moshi.java:101) 
        at com.squareup.moshi.Moshi.adapter(Moshi.java:75) 
        ...
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) 
```

**Comment by ZacSweers** [comment]
As mentioned above, Moshi doesn't support inline classes yet
