### ISSUE TITLE
Runtime crash: No static method isPlatformType(Ljava/lang/Class;)Z

### ISSUE THREAD

**Issue by ber4444** [square/moshi#851]
```
2019-05-15 10:48:20.477 15014-15014/com.blah.activities.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.blah.activities.debug, PID: 15014
    java.lang.NoSuchMethodError: No static method isPlatformType(Ljava/lang/Class;)Z in class Lcom/squareup/moshi/ClassJsonAdapter; or its super classes (declaration of 'com.squareup.moshi.ClassJsonAdapter' appears in /data/app/com.blah.activities.debug-HM9OLcX9tOT6_MLNmGoxFQ==/base.apk!classes28.dex)
        at com.squareup.moshi.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:158)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:71)
```
It's within our in-house library which uses:
```
        "moshi_kotlin" : "1.5.0",
        "retrofit_moshi_converter" : "2.4.0",
    implementation "com.squareup.moshi:moshi-kotlin:${versions.moshi_kotlin}"
    implementation "com.squareup.retrofit2:converter-moshi:${versions.retrofit_moshi_converter}"
```
Our app uses:
```
            moshi:'1.8.0',
    kapt "com.squareup.moshi:moshi-kotlin-codegen:${deps.moshi}"
    implementation "com.squareup.moshi:moshi:${deps.moshi}"
```
We have these proguard rules:
```
-dontwarn javax.annotation.**
-keepclasseswithmembers class * {
    @com.squareup.moshi.* <methods>;
}
-keep @com.squareup.moshi.JsonQualifier interface *
-keepclassmembers @com.squareup.moshi.JsonClass class * extends java.lang.Enum {
    <fields>;
}
-keepnames @com.squareup.moshi.JsonClass class *
-if @com.squareup.moshi.JsonClass class *
-keep class <1>JsonAdapter {
    <init>(...);
    <fields>;
}
-if @com.squareup.moshi.JsonClass class **$*
-keep class <1>_<2>JsonAdapter {
    <init>(...);
    <fields>;
}
-if @com.squareup.moshi.JsonClass class **$*$*
-keep class <1>_<2>_<3>JsonAdapter {
    <init>(...);
    <fields>;
}
-if @com.squareup.moshi.JsonClass class **$*$*$*
-keep class <1>_<2>_<3>_<4>JsonAdapter {
    <init>(...);
    <fields>;
}
-if @com.squareup.moshi.JsonClass class **$*$*$*$*
-keep class <1>_<2>_<3>_<4>_<5>JsonAdapter {
    <init>(...);
    <fields>;
}
-if @com.squareup.moshi.JsonClass class **$*$*$*$*$*
-keep class <1>_<2>_<3>_<4>_<5>_<6>JsonAdapter {
    <init>(...);
    <fields>;
}
```

**Comment by ZacSweers** [comment]
Can you make a reproducible project? It seems like a dex packaging issue where it can't find some of Moshi's classes

**Comment by ber4444** [comment]
I'm using 
```
        classpath 'com.android.tools:r8:1.4.93'
        classpath 'com.android.tools.build:gradle:3.4.0'
```
with multidex. Will try to find time for making a sample project later.

**Comment by ber4444** [comment]
It's actually not related to R8. We have the same crash in our debug build. CI fails with this when running our Espresso tests as well.

**Comment by ZacSweers** [comment]
As mentioned above - it sounds like a packaging issue

**Comment by ber4444** [comment]
Ok, figured it why. In 1.5.0, there was `com.squareup.moshi.ClassJsonAdapter#isPlatformType`
in 1.8.0, it was changed to `Util.isPlatformType()`.

**Comment by ZacSweers** [comment]
Ahhh yep, that will do it too. Definitely make sure your dependency versions are in sync
