### ISSUE TITLE
Kotlin - Can't deserialize field with 'synchronized' val name

### ISSUE THREAD

**Issue by juliancadi** [square/moshi#857]
## Issue description

`val` can't have _**synchronized**_ as variable identifier because deserialization will fail at runtime for that specific field:

```
com.squareup.moshi.JsonDataException: Required property 'synchronized' missing at $.Channel.Items[0]
        at co.arkbox.msg.model.ItemJsonAdapter.fromJson(ItemJsonAdapter.kt:94)
        at co.arkbox.msg.model.ItemJsonAdapter.fromJson(ItemJsonAdapter.kt:16)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
        at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at co.arkbox.msg.model.ChannelJsonAdapter.fromJson(ChannelJsonAdapter.kt:70)
        at co.arkbox.msg.model.ChannelJsonAdapter.fromJson(ChannelJsonAdapter.kt:16)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at co.arkbox.msg.model.MessageJsonAdapter.fromJson(MessageJsonAdapter.kt:40)
        at co.arkbox.msg.model.MessageJsonAdapter.fromJson(MessageJsonAdapter.kt:13)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Kotlin**

```
@JsonClass(generateAdapter = true)
data class Message(
    @field:Json(name = "Title") val title: String,
    @field:Json(name = "Channel") val channel: Channel
)

@JsonClass(generateAdapter = true)
data class Channel(
    @field:Json(name = "ChannelId") val channelId: Int,
    @field:Json(name = "Items") val itemList: List<Item>
)

@JsonClass(generateAdapter = true)
data class Item(
    @field:Json(name = "Id") val id: Int,
    @field:Json(name = "Description") val description: String,
    @field:Json(name = "Order") val order: Int,
    // Failure: This won't work >>
    @field:Json(name = "Synchronized") val synchronized: Boolean
)

```

**Json**

```
{
  "Title": "Container 1",
  "Channel": {
    "ChannelId": 192,
    "Items": [
      {
        "ItemId": 5960,
        "Description": "Item 5960",
        "Order": 1,
        "Synchronized": false
      }
    ]
  }
}
```

Once the variable _**synchronized**_ has been renamed to something else, the deserialization works correctly

```
   ...
    // OK: This works correctly >>
    @field:Json(name = "Synchronized") val newNonConflictingName: Boolean
   ...
```

On the other hand, if the variable _**synchronized**_ is `Nullable` (in this case `Boolean?`) the deserialization won't fail, nevertheless _**synchronized**_ would be set to `null` even though there is an existent value `true/false` in the Json property

```
   ...
    // false/true deserialized as null >>
    @field:Json(name = "Synchronized") val synchronized: Boolean?
   ...
```

## Integration method

**Gradle 5.1.1**

```
implementation "com.squareup.moshi:moshi:1.8.0"
kapt "com.squareup.moshi:moshi-kotlin-codegen:1.8.0"
```

## Moshi version

1.8.0

## Kotlin version

1.3.31

## System Information

Android Studio 3.4
Build #AI-183.5429.30.34.5452501, built on April 10, 2019
JRE: 1.8.0_152-release-1343-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5

**Comment by NightlyNexus** [comment]
can you post the generated adapter here, if you have it handy?

**Comment by cortinico** [comment]
Hey @juliancadi,
I did some investigation here and apparently the `@field:Json(name = "Synchronized")` gets ignored given that no field is generated for the `synchronized` property by the Kotlin Compiler.

Changing the target of your annotation to the getter would fix your problem: `@get:Json(name = "Synchronized")`. 
I'm also not sure this should be considered a bug of moshi 🤔

@NightlyNexus FYI here the type adapter (generated with `moshi-kotlin-codegen:1.8.0`):
```kotlin
// Code generated by moshi-kotlin-codegen. Do not edit.
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonDataException
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import java.lang.NullPointerException
import kotlin.Boolean
import kotlin.Int
import kotlin.String

class ItemJsonAdapter(moshi: Moshi) : JsonAdapter<Item>() {
    private val options: JsonReader.Options =
            JsonReader.Options.of("Id", "Description", "Order", "synchronized")

    private val intAdapter: JsonAdapter<Int> =
            moshi.adapter<Int>(Int::class.java, kotlin.collections.emptySet(), "id")

    private val stringAdapter: JsonAdapter<String> =
            moshi.adapter<String>(String::class.java, kotlin.collections.emptySet(), "description")

    private val booleanAdapter: JsonAdapter<Boolean> =
            moshi.adapter<Boolean>(Boolean::class.java, kotlin.collections.emptySet(), "synchronized")

    override fun toString(): String = "GeneratedJsonAdapter(Item)"

    override fun fromJson(reader: JsonReader): Item {
        var id: Int? = null
        var description: String? = null
        var order: Int? = null
        var synchronized: Boolean? = null
        reader.beginObject()
        while (reader.hasNext()) {
            when (reader.selectName(options)) {
                0 -> id = intAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'id' was null at ${reader.path}")
                1 -> description = stringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'description' was null at ${reader.path}")
                2 -> order = intAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'order' was null at ${reader.path}")
                3 -> synchronized = booleanAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'synchronized' was null at ${reader.path}")
                -1 -> {
                    // Unknown name, skip it.
                    reader.skipName()
                    reader.skipValue()
                }
            }
        }
        reader.endObject()
        var result = Item(
                id = id ?: throw JsonDataException("Required property 'id' missing at ${reader.path}"),
                description = description ?: throw JsonDataException("Required property 'description' missing at ${reader.path}"),
                order = order ?: throw JsonDataException("Required property 'order' missing at ${reader.path}"),
                synchronized = synchronized ?: throw JsonDataException("Required property 'synchronized' missing at ${reader.path}"))
        return result
    }

    override fun toJson(writer: JsonWriter, value: Item?) {
        if (value == null) {
            throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
        }
        writer.beginObject()
        writer.name("Id")
        intAdapter.toJson(writer, value.id)
        writer.name("Description")
        stringAdapter.toJson(writer, value.description)
        writer.name("Order")
        intAdapter.toJson(writer, value.order)
        writer.name("synchronized")
        booleanAdapter.toJson(writer, value.synchronized)
        writer.endObject()
    }
}
```

**Comment by ZacSweers** [comment]
Does this work if you don't use `field:` site targeting? Code gen doesn't require that, and in fact I'm not sure if it necessarily abides by that if it is specified

**Comment by ZacSweers** [comment]
Closing for now. Feel free to revisit if you can answer the above!
