### ISSUE TITLE
Add adapter for Void

### ISSUE THREAD

**Issue by onacit** [square/moshi#866]
I have a case for handling `Void`.
```java
class Parent<IdType> {
    private IdType id;
}
class Child extends Parent<Void> {
}
```
And I have to add my custom `JsonAapter` for that.
```java
static class MoshiVoidAdapter extends JsonAdapter<Void> {

    @Override
    public Void fromJson(final JsonReader reader) throws IOException {
        return reader.nextNull();
    }

    @Override
    public void toJson(final JsonWriter writer, final Void value) throws IOException {
        writer.nullValue();
    }
}
```
It'll be helpful if a predefined adapter provided.

FYI. no luck with `com.squareup.moshi:moshi-adapters`.

**Comment by swankjesse** [comment]
Your adapter looks correct!

**Comment by swankjesse** [comment]
I’m sorry, I didn’t intend to say “send us a pull request”. I think the adapter above is fine, and I think anyone else who encounters a Void should write an adapter.

Moshi’s goal isn’t to provide all the adapters in the box, instead it’s to make writing adapters really easy.

**Comment by onacit** [comment]
@swankjesse Thank you the comment.

Can I raise another issue for following problem?

```
java.lang.IllegalArgumentException: 
Platform class java.lang.Void (with no annotations) requires explicit JsonAdapter to be registered
for class java.lang.Void id
for class ....HandleMessageNotification
        at ....HandleMessageNotificationTest.handleMessage_02_notification(HandleMessageNotificationTest.java:62)
Caused by: java.lang.IllegalArgumentException: Platform class java.lang.Void (with no annotations) requires explicit JsonAdapter to be registered
        at ....HandleMessageNotificationTest.handleMessage_02_notification(HandleMessageNotificationTest.java:62)
```

It will be much more helpful if Moshi, internally, treats `Void` more handy and automatically.

**Comment by onacit** [comment]
For anyone reached here.

```java
    static class VoidAdapter extends JsonAdapter<Void> {

        @Override
        public Void fromJson(final JsonReader reader) throws IOException {
            reader.skipValue();
            return null;
        }

        @Override
        public void toJson(final JsonWriter writer, final Void value) throws IOException {
            writer.nullValue();
        }
    }
```
