### ISSUE TITLE
Android Q compatibility policy violation 

### ISSUE THREAD

**Issue by BejanAlina** [square/moshi#872]
Device running android 9
Moshi version moshi-kotlin:1.8.0

Android P reports non sdk api uasge warnings when using the library:

The warnings are marked as light greylist and they are just warnings for now, but might be restricted in later versions as it is currently for the dark greylist warnings which are not going to work on android Q as announced.

See also https://developer.android.com/preview/restrictions-non-sdk-interfaces.html for a more detailed explanation.

StackTrace
```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe;
        at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
        at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.squareup.moshi.ClassFactory.get(ClassFactory.java:63)
        at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:79)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
        at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:99)
        at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:82)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:67)
```

Thanks for support!

**Comment by ZacSweers** [comment]
Took a crack at this in #913
