### ISSUE TITLE
KotlinJsonAdapter - Wrong property path with missing non-nullable property

### ISSUE THREAD

**Issue by Pasukaru** [square/moshi#882]
As a follow up of #510, there is still an issue with stating the wrong path when a non-nullable property is missing.

Example:
```kotlin
data class Foo(
    val bar: String
)
```

Providing the json: `{}`

Results in 
```
com.squareup.moshi.JsonDataException: Required value 'bar' missing at $
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:96)
```

Whereas 
```json 
{"bar":null}
```

Results in
```
com.squareup.moshi.JsonDataException: Non-null value 'bar' was null at $.bar
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:86)
```

My context:
I'm parsing the error message (with a crude regex `Regex("""^.*\$\.([\w.]+).*$""")` to get the path to the offending property. This inconsistency breaks the parsing.

**Comment by swankjesse** [comment]
Don’t parse error messages with regexes.

**Comment by Pasukaru** [comment]
> Don’t parse error messages with regexes.

I'd love to avoid parsing it manually at all.
Is there an API to retrieve the offending property from the JsonDataException?
I'm looking for something similar that jackson offers with a small extension: `JsonMappingException.path.map { it.fieldName }.joinToString(".")`

**Comment by JakeWharton** [comment]
Supplying the offending JSON path as a string in its own property seems like it makes sense. I'm not sure we want to provide a rich model for the path, though.

**Comment by ZacSweers** [comment]
What would the API for JsonDataException look like for this? Multiple constructor overloads? Setter for the path? Also - would we retrofit all the existing internal usages to start using these new APIs?

**Comment by JakeWharton** [comment]
Constructor overload probably. Yes everything internal would use it.
