### ISSUE TITLE
Parse a jsonarray with custom adapter

### ISSUE THREAD

**Issue by DanteAndroid** [square/moshi#894]
Any mistakes in my code?
```
    private class ImageAdapter {
        private val moshi = Moshi.Builder().build()

        @ToJson
        fun toJson(image: Image): String? {
            return moshi.adapter(Image::class.java).toJson(image)
        }

        @FromJson
        fun fromJson(data: String): Image? {
            println("fromJson") // not called
            return moshi.adapter(Image::class.java).fromJson(data).apply{// some other work} 
        }
    }

      val type = newParameterizedType(List::class.java, Image::class.java)
        val images = Moshi.Builder()
            .add(ImageAdapter()) // ImageAdapter is a custom class with @fromJson & @toJson
            .add(KotlinJsonAdapterFactory())
            .build()
            .adapter<List<Image>>(type).fromJson(array) //array is a JsonArray string
```

```
  com.squareup.moshi.JsonDataException: Expected a string but was BEGIN_OBJECT at path $[0]
        at com.squareup.moshi.JsonUtf8Reader.nextString(JsonUtf8Reader.java:644)
        at com.squareup.moshi.StandardJsonAdapters$10.fromJson(StandardJsonAdapters.java:215)
        at com.squareup.moshi.StandardJsonAdapters$10.fromJson(StandardJsonAdapters.java:213)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.squareup.moshi.AdapterMethodsFactory$5.fromJson(AdapterMethodsFactory.java:256)
        at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:90)
        at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
        at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:53)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:137)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:41)
        at com.example.threedimens.net.DataParser.parseGank(DataParser.kt:70)
        at com.example.threedimens.net.DataParser.parseList(DataParser.kt:32)
        at com.example.threedimens.net.DataParser.getImages(DataParser.kt:23)
        at com.example.threedimens.data.ImageRepository$fetchImages$2.invokeSuspend(ImageRepository.kt:24)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by DanteAndroid** [comment]
It may seem that ImageAdapter is useless, but I need to do some work in `fromJson`

**Comment by DanteAndroid** [comment]
@ZacSweers Hi, `ImageAdapter` is in the code

**Comment by ZacSweers** [comment]
Sorry, misread :).

The exception seems to indicate that your image string is actually a json object. Can you look at the raw json and confirm?

**Comment by DanteAndroid** [comment]
Of course it's a JSON object, and it's a JSON array which I wrote in the comment. Because I want to parse json array to a List<Image>

**Comment by ZacSweers** [comment]
> it's a JSON object, and it's a JSON array

Both of these cannot be true at the same time, so I'm not sure I understand what you're saying. Please paste example raw JSON this is intended to read.

**Comment by DanteAndroid** [comment]
@ZacSweers Thanks for quick response. My mistake. 
The data is response of http://gank.io/api/data/%E7%A6%8F%E5%88%A9/10/1
The array is `val array = JSONObject(data).getString("results")`

**Comment by ZacSweers** [comment]
> The array is val array = JSONObject(data).getString("results")

I'd be curious what this is returning, and what string is coming through your `fromJson`. To simplify this back-and-forth, can you just paste a complete snippet of code that (without any modifications needed) can be pasted into another IDE and run to reproduce this

**Comment by DanteAndroid** [comment]
```
package com.example.moshimoshi

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import com.squareup.moshi.FromJson
import com.squareup.moshi.Moshi
import com.squareup.moshi.ToJson
import com.squareup.moshi.Types.newParameterizedType
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory



class MainActivity : AppCompatActivity() {

    private val result = "[{\"_id\":\"5ccdbc219d212239df927a93\",\"createdAt\":\"2019-05-04T16:21:53.523Z\",\"desc\":\"2019-05-05\",\"publishedAt\":\"2019-05-04T16:21:59.733Z\",\"source\":\"web\",\"type\":\"福利\",\"url\":\"http://ww1.sinaimg.cn/large/0065oQSqly1g2pquqlp0nj30n00yiq8u.jpg\",\"used\":true,\"who\":\"lijinshanmx\"},{\"_id\":\"5cc43919fc3326376038d233\",\"createdAt\":\"2019-04-27T19:12:25.536Z\",\"desc\":\"2019-04-27\",\"publishedAt\":\"2019-04-27T19:12:51.865Z\",\"source\":\"web\",\"type\":\"福利\",\"url\":\"https://ww1.sinaimg.cn/large/0065oQSqly1g2hekfwnd7j30sg0x4djy.jpg\",\"used\":true,\"who\":\"lijinshanmx\"},{\"_id\":\"5c6a4ae99d212226776d3256\",\"createdAt\":\"2019-02-18T06:04:25.571Z\",\"desc\":\"2019-02-18\",\"publishedAt\":\"2019-04-10T00:00:00.0Z\",\"source\":\"web\",\"type\":\"福利\",\"url\":\"https://ws1.sinaimg.cn/large/0065oQSqly1g0ajj4h6ndj30sg11xdmj.jpg\",\"used\":true,\"who\":\"lijinshanmx\"}]"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        parse(result)

        var i = 0
        while (true) {
            i++ // this will cause anr
        }

    }

    private fun parse(data: String) {
        val type = newParameterizedType(List::class.java, Image::class.java)
        val images = Moshi.Builder()
            .add(ImageAdapter())
            .add(KotlinJsonAdapterFactory())
            .build()
            .adapter<List<Image>>(type).fromJson(data)

        println("parse result $images")
    }

    private class ImageAdapter {
        private val moshi = Moshi.Builder().build()

        @ToJson
        fun toJson(image: Image): String? {
            return moshi.adapter(Image::class.java).toJson(image)
        }

        @FromJson
        fun fromJson(data: String): Image? {
            println("fromJson")
            return moshi.adapter(Image::class.java).fromJson(data)
        }
    }
}
data class Image(val id: Int = 0, val url: String = "", var type: String = "")


```

**Comment by ZacSweers** [comment]
I think I have a better solution for you - This is actually easy. If you want simple forwarding, moshi's `JsonAdapter.Factory` API supports that directly.

```kotlin
class DelegatingImageAdapter(private val delegate: JsonAdapter<Image>) : JsonAdapter<Image>() {

  override fun fromJson(reader: JsonReader): Image? {
    return delegate.fromJson(reader).also { image ->
      // TODO Do your things with image!
    }
  }

  override fun toJson(writer: JsonWriter, value: Image?) {
    return delegate.toJson(writer, value)
  }
  
  object Factory : JsonAdapter.Factory {
    override fun create(type: Type, annotations: MutableSet<out Annotation>,
        moshi: Moshi): JsonAdapter<*>? {
      if (annotations.isNotEmpty()) return null
      if (Types.getRawType(type) == Image::class.java) {
        val delegate = moshi.nextAdapter<Image>(this, type, annotations)
        return DelegatingImageAdapter(delegate)
      }
      return null
    }
  }
}
```

Couple other notes
- your `id` field will not match the json `_id` field without a `@Json(name = "_id")` on it.
- ids in that json appear to be strings, not ints

The following code works for me. Note that it's important to add your delegating adapter first before the `KotlinJsonAdapterFactory`.

```Kotlin
@Test fun imageTest() {
  val result = "[{\"_id\":\"5ccdbc219d212239df927a93\",\"createdAt\":\"2019-05-04T16:21:53.523Z\",\"desc\":\"2019-05-05\",\"publishedAt\":\"2019-05-04T16:21:59.733Z\",\"source\":\"web\",\"type\":\"福利\",\"url\":\"http://ww1.sinaimg.cn/large/0065oQSqly1g2pquqlp0nj30n00yiq8u.jpg\",\"used\":true,\"who\":\"lijinshanmx\"},{\"_id\":\"5cc43919fc3326376038d233\",\"createdAt\":\"2019-04-27T19:12:25.536Z\",\"desc\":\"2019-04-27\",\"publishedAt\":\"2019-04-27T19:12:51.865Z\",\"source\":\"web\",\"type\":\"福利\",\"url\":\"https://ww1.sinaimg.cn/large/0065oQSqly1g2hekfwnd7j30sg0x4djy.jpg\",\"used\":true,\"who\":\"lijinshanmx\"},{\"_id\":\"5c6a4ae99d212226776d3256\",\"createdAt\":\"2019-02-18T06:04:25.571Z\",\"desc\":\"2019-02-18\",\"publishedAt\":\"2019-04-10T00:00:00.0Z\",\"source\":\"web\",\"type\":\"福利\",\"url\":\"https://ws1.sinaimg.cn/large/0065oQSqly1g0ajj4h6ndj30sg11xdmj.jpg\",\"used\":true,\"who\":\"lijinshanmx\"}]"
  val moshi = Moshi.Builder()
      .add(DelegatingImageAdapter.Factory)
      .add(KotlinJsonAdapterFactory())
      .build()

  val listAdapter = moshi.adapter<List<Image>>(Types.newParameterizedType(List::class.java, Image::class.java))
  val parsed = listAdapter.fromJson(result)
  println(parsed)
}

data class Image(@Json(name = "_id") val id: String = "0", val url: String = "", var type: String = "")

class DelegatingImageAdapter(private val delegate: JsonAdapter<Image>) : JsonAdapter<Image>() {

  override fun fromJson(reader: JsonReader): Image? {
    return delegate.fromJson(reader).also { image ->
      println("Intercepted image with id: ${image?.id}")
    }
  }

  override fun toJson(writer: JsonWriter, value: Image?) {
    return delegate.toJson(writer, value)
  }

  object Factory : JsonAdapter.Factory {
    override fun create(type: Type, annotations: MutableSet<out Annotation>,
        moshi: Moshi): JsonAdapter<*>? {
      if (annotations.isNotEmpty()) return null
      if (Types.getRawType(type) == Image::class.java) {
        val delegate = moshi.nextAdapter<Image>(this, type, annotations)
        return DelegatingImageAdapter(delegate)
      }
      return null
    }
  }
}
```

And that prints the following out to console

```
Intercepted image with id: 5ccdbc219d212239df927a93
Intercepted image with id: 5cc43919fc3326376038d233
Intercepted image with id: 5c6a4ae99d212226776d3256
[Image(id=5ccdbc219d212239df927a93, url=http://ww1.sinaimg.cn/large/0065oQSqly1g2pquqlp0nj30n00yiq8u.jpg, type=福利), Image(id=5cc43919fc3326376038d233, url=https://ww1.sinaimg.cn/large/0065oQSqly1g2hekfwnd7j30sg0x4djy.jpg, type=福利), Image(id=5c6a4ae99d212226776d3256, url=https://ws1.sinaimg.cn/large/0065oQSqly1g0ajj4h6ndj30sg11xdmj.jpg, type=福利)]
```

Let me know if I've missed something

**Comment by DanteAndroid** [comment]
@ZacSweers Thanks, I'll give it a shot. I wonder why couldn't I use a custom adapter? What's wrong with my code?

**Comment by swankjesse** [comment]
Unclear what action to take on this.
