### ISSUE TITLE
1.9.0 - UnsupportedOperationException when deserialising java class with non-empty constructor

### ISSUE THREAD

**Issue by emartynov** [square/moshi#949]
We have (had) some legacy java DTO code:
```java
public class ProblemDTO {
    private String message;

    ProblemDTO(String message) {
        this.message = message;
    }
}
```

The Moshi crashes on API 29 when trying to deserialise it:
```
 Caused by: java.lang.UnsupportedOperationException: ObjectStreamClass.getConstructorId(Class<?>) is not supported on SDK 28
        at java.io.ObjectStreamClass.getConstructorId(ObjectStreamClass.java:2421)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.squareup.moshi.ClassFactory.get(ClassFactory.java:110)
        at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:96)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:72)
```

An example project is here - https://github.com/emartynov/MoshiTest

The fix for the issue was the conversion of java DTO to Kotlin.

**Comment by emartynov** [comment]
Another workaround - have an empty constructor in your java class.

**Comment by ZacSweers** [comment]
That's the proper workaround for 28+, we can't use that reflective approach on API 28+. I'll open a PR to not try it at all

**Comment by ming13** [comment]
@ZacSweers, just to clarify — is the Kotlin reflection fine with these restrictions? I believe Gson leads to similar warnings and maybe it is a good time to migrate to Moshi for us.

**Comment by ZacSweers** [comment]
Kotlin still requires a constructor but it won't try using ClassFactory. Unsure what Kotlin-reflect does if there's no constructor though.

**Comment by ZacSweers** [comment]
Going to close this for now, please let us know if this does occur without strict mode enabled
