### ISSUE TITLE
kotlin codege: IllegalStateException: No type argument found for 0!

### ISSUE THREAD

**Issue by Wasabi375** [square/moshi#955]
```kotlin
@JsonClass(generateAdapter = true)
class TextAssetMetaData: AssetMetaData<TextAsset>()

class TextAsset: Asset<TextAsset>()

abstract class Asset<A: Asset<A>>
abstract class AssetMetaData<A: Asset<A>>
```
This crashes with 
```
[Kapt and Gradle exception]
Caused by: java.lang.IllegalStateException: No type argument found for 0!
        at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs$toTypeParamsResolver$typeParamResolver$1.invoke(KotlinPoetMetadataSpecs.kt:198)
        at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs$toTypeParamsResolver$typeParamResolver$1.invoke(KotlinPoetMetadataSpecs.kt)
        at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:84)
        at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName$default(KmTypes.kt:79)
        at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:62)
        at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:81)
        at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName$default(KmTypes.kt:79)
        at com.squareup.moshi.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeVariableName(KmTypes.kt:156)
        at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeParamsResolver(KotlinPoetMetadataSpecs.kt:201)
        at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeParamsResolver$default(KotlinPoetMetadataSpecs.kt:192)
        at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:211)
        at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:173)
        at com.squareup.moshi.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:144)
        at com.squareup.moshi.kotlin.codegen.MetadataKt.declaredProperties$default(metadata.kt:206)
        at com.squareup.moshi.kotlin.codegen.MetadataKt.targetType(metadata.kt:184)
        at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.adapterGenerator(JsonClassCodegenProcessor.kt:133)
        at com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor.process(JsonClassCodegenProcessor.kt:107)
...
```
I am pretty sure this is a bug in kotlinpoet, but I'm not really sure how to repoduce it at their end. My testing shows that the bug is in connection with the circular generic definition on `AssetMetaData<A: Asset<A>>`. 

Tested with current SNAPSHOT.

**Comment by ZacSweers** [comment]
Can you reproduce with Kotlinpoet-metadata directly? If so we can transfer
this issue to there

**Comment by Wasabi375** [comment]
I never used kotlinpoet metadata myself directly so I don't really know where to start with that. I guess I will have to get the Metadata annotation and than I should probably be able to extract the rest of what I need from the moshi sources. I can look into it if you want.

**Comment by ZacSweers** [comment]
Moved to KotlinPoet: https://github.com/square/kotlinpoet/issues/812

**Comment by ZacSweers** [comment]
Whoops didn't mean to close this yet
