### ISSUE TITLE
R8 shakes values(), which is required for the standard enum serializer

### ISSUE THREAD

**Issue by jzbrooks** [square/moshi#962]
Our team is in the process of moving from hand-rolled enum adapters to using the standard enum adapter. It seems like others might run into something similar. We use kotlin codegen for our non-enum classes and the built-in handling for enums.

```
    java.lang.AssertionError: impossible
        at java.lang.Enum$1.create(Enum.java:272)
        at java.lang.Enum$1.create(Enum.java:262)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2423)
        at java.lang.Class.getEnumConstants(Class.java:2409)
        at com.squareup.moshi.B$k.<init>(StandardJsonAdapters.java:3)
        at com.squareup.moshi.B$b.a(StandardJsonAdapters.java:24)
        at com.squareup.moshi.A.a(Moshi.java:27)
        at <internal stuff>
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.squareup.moshi.E.a.a(Util.java:103)
        at com.squareup.moshi.B$b.a(StandardJsonAdapters.java:22)
        at com.squareup.moshi.A.a(Moshi.java:27)
        at l.J.a.a.a(MoshiConverterFactory.java:13)
        at l.E.a(Retrofit.java:32)
        at l.C$a.a(RequestFactory.java:298)
        at l.F.a(ServiceMethod.java:1)
        at l.E.a(Retrofit.java:11)
        at l.E$a.invoke(Retrofit.java:5)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy0.a(Unknown Source)
        at f.c.a.c.a(Repository.kt:77)
        at <internal stuff>
        at j.p.g.a.a.a(ContinuationImpl.kt:3)
        at kotlinx.coroutines.N.run(Dispatched.kt:15)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.a(CoroutineScheduler.kt:54)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.a(CoroutineScheduler.kt:4)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$a.run(CoroutineScheduler.kt:40)
     Caused by: java.lang.NoSuchMethodException: values []
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at java.lang.Enum$1.create(Enum.java:268)
        at java.lang.Enum$1.create(Enum.java:262) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58) 
        at java.lang.Enum.getSharedConstants(Enum.java:289) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2423) 
        at java.lang.Class.getEnumConstants(Class.java:2409) 
        at com.squareup.moshi.B$k.<init>(StandardJsonAdapters.java:3) 
        at com.squareup.moshi.B$b.a(StandardJsonAdapters.java:24) 
        at com.squareup.moshi.A.a(Moshi.java:27) 
```

I've reproduced with full mode both on and off.

To address the problem I've added the following rule, which seems to help r8 keep the synthetic method.

```
-keepclassmembers @com.squareup.moshi.JsonClass enum * {
    public static **[] values();
}
```

Would this be something beneficial to add to the library provided keep rules?

**Comment by ZacSweers** [comment]
Yes absolutely, happy to accept a PR with that rule 👍
