### ISSUE TITLE
Can I apply Moshi @JsonQualifier to a type parameter?

### ISSUE THREAD

**Issue by dscoppelletti** [square/moshi#971]
This is my code:

```
import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonClass
import com.squareup.moshi.JsonDataException
import com.squareup.moshi.JsonQualifier
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import java.math.BigDecimal
import kotlin.test.Test
import kotlin.test.assertEquals

class LocationDataAdapterTest {

    @Test
    fun toJsonWithQualifier() {
        val moshi: Moshi
        val adapter: JsonAdapter<LocationData>

        moshi = Moshi.Builder()
                .add(BigDecimal::class.java, JsonCoordinates::class.java,
                        DecimalAdapter())
                .build()
        adapter = moshi.adapter(LocationData::class.java)

        val data = LocationData(listOf(BigDecimal(10), BigDecimal(20)))
        assertEquals("{\"coordinates\":[\"10\",\"20\"]}", adapter.toJson(data))
    }

    @Test
    fun toJsonWithoutQualifier() {
        val moshi: Moshi
        val adapter: JsonAdapter<LocationData>

        moshi = Moshi.Builder()
                .add(BigDecimal::class.java, DecimalAdapter())
                .build()
        adapter = moshi.adapter(LocationData::class.java)

        val data = LocationData(listOf(BigDecimal(10), BigDecimal(20)))
        assertEquals("{\"coordinates\":[\"10\",\"20\"]}", adapter.toJson(data))
    }
}

@JsonQualifier
@Target(AnnotationTarget.TYPE)
@Retention(AnnotationRetention.RUNTIME)
annotation class JsonCoordinates

@JsonClass(generateAdapter = true)
data class LocationData(
        val coordinates: List<@JvmSuppressWildcards @JsonCoordinates BigDecimal>
)

class DecimalAdapter : JsonAdapter<BigDecimal>() {
    override fun fromJson(reader: JsonReader): BigDecimal? {
        val value: String?

        value = reader.nextString()
        if (value.isNullOrBlank()) {
            return null
        }

        return try {
            BigDecimal(value)
        } catch (ex: NumberFormatException) {
            throw JsonDataException(ex)
        }
    }

    override fun toJson(writer: JsonWriter, value: BigDecimal?) {
        if (value == null) {
            writer.nullValue()
        } else {
            writer.value(value.toPlainString())
        }
    }
}
```

The test `toJsonWithoutQualifier` has success.
The test `toJsonWithQualifier` fails with the following exception:

```
java.lang.IllegalArgumentException: Platform class java.math.BigDecimal (with no annotations) requires explicit JsonAdapter to be registered
for class java.math.BigDecimal
for java.util.List<java.math.BigDecimal> coordinates
for class app.klosed.api.model.LocationData

	at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:348)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:149)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:67)
	at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:52)
	at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:36)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
	at app.klosed.api.model.LocationDataJsonAdapter.<init>(LocationDataJsonAdapter.kt:19)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:478)
	at com.squareup.moshi.StandardJsonAdapters$1.create(StandardJsonAdapters.java:60)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:97)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:71)
	at app.klosed.api.model.LocationDataAdapterTest.toJsonWitQualifier(LocationDataAdapterTest.kt:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: Platform class java.math.BigDecimal (with no annotations) requires explicit JsonAdapter to be registered
	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:60)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:137)
	... 38 more
```

**Comment by ZacSweers** [comment]
Right now this isn't possible. I do think we should try to though!

For Java - requires Java 8.
For Kotlin - type annotations are serialized directly to the metadata and retrievable from that. The bigger question is how we can get or create instances to pass to Moshi. We would need something like AutoAnnotation for Kotlin.

**Comment by JakeWharton** [comment]
2.x should require Java 8

**Comment by ZacSweers** [comment]
Agreed. Though I don't think this is covered by desugar, so I think android users would be left in the dust by this

**Comment by JakeWharton** [comment]
Yes, they are removed at dexing time. Dex has no way to model type annotations.

**Comment by dscoppelletti** [comment]
Can I suggest a new feature?  
A new Moshi annotation `@JsonItemQualifier` could be applied to my annotation `@JsonCoordinates` and the annotation `@JsonCoordinate` applied to the property `coordinates` could specify which adapter to use for the items `BigDecimal` of the `List`.

```
@JsonClass(generateAdapter = true)
data class LocationData(
       @JsonCoordinates
        val coordinates: List<BigDecimal>
)

@JsonItemQualifier
@Retention(AnnotationRetention.RUNTIME)
annotation class JsonCoordinates 
```

**Comment by ZacSweers** [comment]
That would be far too narrow of a use-case for the library itself, but you could write your own adapter that behaves like this and just annotate `JsonCoordinates` with `JsonQualifier` as well

**Comment by swankjesse** [comment]
Not likely to implement this without support for the underlying platform.

**Comment by dscoppelletti** [comment]
I wrote my own adapter. I undestand that is not a common use case.
